* 地址

** 概要

本节介绍一些一般模式，与后面几节有重复

*** 固定行号

只在144行操作：

#+BEGIN_SRC bash
sed '144s/hello/world/' input.txt > output.txt
#+END_SRC

*** 用 ~,~ 来连接范围

4-17行：

#+BEGIN_SRC bash
sed '4,17s/hello/world/' input.txt > output.txt
#+END_SRC

*** 省略address

不指定address就是全部操作：

#+BEGIN_SRC bash
sed 's/hello/world/' input.txt > output.txt
#+END_SRC

*** 由regExp来决定

案例为某行出现 ~apple~ 时进行操作：
#+BEGIN_SRC bash
sed '/apple/s/hello/world/' input.txt > output.txt
#+END_SRC

*** 在address后面加 ~!~ 来取反

只在不出现 ~apple~ 的那一行操作：

#+BEGIN_SRC bash
sed '/apple/!s/hello/world/' input.txt > output.txt
#+END_SRC

在1-3行和18行以后操作：

#+BEGIN_SRC bash
sed '4,17!s/hello/world/' input.txt > output.txt
#+END_SRC

** 数字地址

*** number

具体数字代表那一行

*** $

最后一行

*** first~step

~first~ 为起始行号， ~step~ 为步进数

#+BEGIN_SRC bash
seq 10 | sed -n '0~4p'
# 4
# 8

seq 10 | sed -n '1~3p'
# 1
# 4
# 7
# 10
#+END_SRC

** 正则地址

*** ~/regexp/~

正则匹配

*** ~\%regexp%~

The % may be replaced by any other single character. 上面的 ~%~  可以用任何单个字符串所替代

#+BEGIN_SRC bash
$ cat file.txt
a
b
/usr/bin/systemctrl
/sbin/ifup
d

$ sed  -n '\@/sbin@p' file.txt
/sbin/ifup
#+END_SRC


*** ~/regexp/I~ 或  ~\%regexp%I~

Ignore 忽略大小写

*** ~/regexp/M~ 或  ~\%regexp%M~

The ~M modifier~ to regular-expression matching is a GNU sed extension which directs GNU sed to match the regular expression in multi-line mode. The modifier causes ^ and $ to match respectively (in addition to the normal behavior) the empty string after a newline, and the empty string before a newline. There are special character sequences (\` and \') which always match the beginning or the end of the buffer. In addition, the period character does not match a new-line character in multi-line mode.


** 范围地址 Range Address

*** 一般的

**** start,end 由 ~,~ 所连接的范围

#+BEGIN_SRC bash
$ seq 10 | sed -n '4,6p'
4
5
6
#+END_SRC

**** start,/regexp/

开始位置到正则所符号的位置，正则所符合的位置，最小为 ~start+1~ ，此设置下range至少有两行

#+BEGIN_SRC bash
$ seq 10 | sed -n '4,/9/p'
4
5
6
7
8
9
#+END_SRC

**** start, end  当end少于start时，只match一行

#+BEGIN_SRC bash
$ seq 10 | sed -n '4,1p'
4
#+END_SRC

*** GNU地址扩展

~GNU sed~ also supports some special two-address forms; all these are GNU extensions:

GUN sed 也支持一些两个地址形式的扩展，这些扩展是：

**** 0,/regexp/

与 ~1,/regexp/~ 类似，但如果第一行就符合 regexp， 那么立即停止。

#+BEGIN_SRC bash
$ seq 10 | sed -n '1,/[0-9]/p'
1
2

$ seq 10 | sed -n '0,/[0-9]/p'
1
#+END_SRC


**** addr1, +N

~+N~  在 addr1 基础上追加 N 行

#+BEGIN_SRC bash
$ seq 10 | sed -n '6,+2p'
6
7
8
#+END_SRC

**** addr1, ~N

~~N~  N的整数倍数字作为结尾

#+BEGIN_SRC bash
$ seq 40 | sed -n '13,~11p'
13
14
15
16
17
18
19
20
21
22
#+END_SRC
