* smtp, imap, pop3 协议之间的差异

** 前言

电子邮箱是一种方便、快捷的通信工具，可对于我这样拥有 3、4 个邮箱的人而言，整天都要在各种邮箱客户端之间切换，很是麻烦。使用 IMAP/POP3 可以帮助可以集中管理自己的所有邮箱账号，可能网上会有许多的教程教我们如何去配置，很简单，照着做就行了。不过今天我想讨论的是，SMTP、POP3 和 IMAP 的来龙去脉，以及它们之间到底是一种怎样的关系。

** 概念介绍

SMTP、POP3 和 IMAP 是 3 款不同的提供电子邮箱服务的网络协议，它们都位于 TCP/IP 体系结构的应用层之上。下面给出它们的概念，还是比较通俗易懂的，实在不想看的，可以先跳过这一节，看完后面有了抽象的理解之后再来看也不迟。

SMTP（Simple Mail Transfer Protocol）
中文译作简单邮箱传输协议。它规定了邮件怎样从源地址传输到目的地址，主要用于邮件服务器间的连接与数据传输；更具体地来说，SMTP 协议可以帮助计算机在发送或中转邮件时找到下一个目的地，整个参与邮件的全部转发过程，它的主要特点如下：

协议基于文本格式，隶属于 TCP/IP 协议簇。

主要用于中继和中转传输。

注：中继和中转之间的区别在于，中继指的是在同一家公司的服务器上传递邮件，中转指的是在多家公司的服务器上传递邮件。

POP3（Post Office protocol 3）
中文译作邮局协议 版本3。平时我们在邮局可以取信件，也可以发信件，但 POP3 协议是名不符实的，它只允许我们取信件。POP3 协议规定了我们的计算机是如何连接邮箱服务器并下载邮件的，利用 POP3，我们可以将位于邮箱服务器上的邮件下载到本地并存储起来，同时将服务器上的邮件副本给删除了（现在使用的都是改进过的 POP3 协议，大多都不再自动删除服务器上的邮件了），但不允许用户对服务器上的邮件进行诸如移动、标记等操作，或许我们可以在本地进行这些操作，但绝不可能会反馈到服务器上，因为协议不支持。它的主要特点如下：

协议基于文本格式，隶属于 TCP/IP 协议簇。

主要用于本地计算机从服务器上下载邮件，并存储之。

本地进行的移动、标记、删除等操作不会反馈到云端。

常用端口号：110/995，其中 995 是 SSL/TSL 加密的。

是面向无连接的。

IMAP(Internet Mail Access Protocol)
中文译作交互邮件访问协议。它规定了计算机如何与邮箱服务器之间进行双向通信，这一点是与 POP3 协议之间最大的不同。IMAP 协议在功能上是 POP3 的加强，增加了摘要浏览、分类文件夹、打标签等功能。

摘要浏览功能指的是可以让用户在阅读完整邮件之前，通过提前浏览邮件到达时间、主题、发件人、大小等信息，然后再决定是否进行下载的决定，它的主要特点如下：

隶属于 TCP/IP 协议簇。

主要用于主机与服务器之间进行双向通信。

本地进行的移动、标记、删除等操作默认反馈到云端。

常用端口号：143/993，其中 993 是 SSL/TSL 加密的。

相较于 POP3 协议，它增加了摘要浏览、分类文件夹、打标签等功能。

面向连接，时刻保持，直到邮件客户端下载完邮件以后自动退出连接。

** 邮件收发流程

假设你正在使用QQ邮箱向朋友的谷歌邮箱发送一封邮件，它走的将会是这样一个流程：

你使用QQ邮箱客户端写了一封邮件，通过SMTP投递到 Tencent 服务器上。

Tencent 那边的服务器收到邮件后，发现不是给自己的，于是转发给 Google 的服务器。

Google 那边的服务器收到后，发现是给自己的，选择先把邮件存起来，等待朋友来取信，如果还支持消息推送的话，会给朋友发个消息，说我这边有你的信，你赶紧来取吧。



(图片来源于网络)
朋友吃完饭玩电脑时，看到有新邮件发过来，一顿操作通过IMAP或者POP3从服务器上下载邮件。至此，邮件的交付就完成了。


(图片来源于网络)
朋友看完后发现你这人还是老样子，净说废话，咔嚓一下把这封信给删了。这时候，如果他使用的是 POP3 协议，那么邮件就真的没了，无法被找回，友谊的小船说翻就翻。如果他用的是 IMAP 协议，那就没关系了，以后还可以再到邮箱服务器上去找回来，友谊地久天长hhh，这两种方案没有一定的优劣之分，各有利弊。

** IMAP比POP3强大

IMAP 和 POP3 实现的功能十分相似（前者几乎实现了后者的所有功能），不过 IMAP 更强大一点，当年 Google 的 Gmail 就是靠率先支持 IMAP 协议才会变得如此流行，倘若允许一些不严谨的表达，我更愿意说 IMAP 是 POP3 的加强版，但实际上它们之间是一种不是同源但后者发扬光大的关系。最后做个总结，整理以下 IMAP 比 POP3 完善的地方：

IMAP 提供 Webmail 与电子邮件客户端之间的双向通信，客户端收取的邮件仍然保留在服务器上，同时在客户端上的操作都会反馈到服务器上（如删除邮件，标记已读等，服务器上的邮件也会做相应的动作。所以无论从浏览器登录邮箱或者客户端软件登录邮箱，看到的邮件以及状态都是一致的）。而 POP3 在客户端的操作不会同步到服务器上。
IMAP 更好地支持了从多个不同设备中随时访问新邮件。
IMAP 提供的摘要浏览功能可以让你在阅读完所有的邮件到达时间、主题、发件人、大小等信息后才作出是否下载的决定。
POP3 需要下载未阅读的邮件，IMAP 可以不用把所有的邮件全部下载，而是通过客户端直接对服务器上的邮件进行操作。所有通过 IMAP 传输的数据都会被加密，从而保证通信的安全性。
IMAP 整体上为用户带来更为便捷和可靠的体验。POP3 更易丢失邮件或多次下载相同的邮件。

** POP3一无是处吗？

这两个协议能并存，就说明 POP3 肯定是有用的，不然早就被就物竞天择，适者生存了：

更安全。这是最重要的一点，不把邮件保存在服务器上，可以最大程度上地保证我们的隐私不被泄露、我们的数据不被那些搞大数据的拿去分析。

对存储要求低。服务器的存储空间是宝贵的，POP3无需把邮件保存在服务器上，极大地节省了存储空间。这一点邮件服务提供商会考虑得更多，个人用户无需太过关心。当然，自建服务器的同学得关心一下。

计算资源要求低。IMAP 功能虽全，但相应地实现起来更困难，对计算资源的要求也更高。POP3 正好与之相反，推荐个人用户使用。

有时下载速度更快。IMAP 可以选择任意邮件进行下载，无疑是比较快的解决方案。但是当我们需要下载所有邮件的时候，POP3 更轻量，数据量小，下载起来自然会更快一些。

参考文章：https://www.jscape.com/blog/smtp-vs-imap-vs-pop3-difference
