* Zypper Cheat Sheet

  - zypper #列出可用的全局选项和命令

  - zypper help search# 列出 search 命令的帮助

  - zypper lp# 列出需要的补丁更新

  - zypper patch# 安装所需的补丁

  - zypper se sqlite# 搜索 sqlite 软件

  - zypper rm sqlite2# 删除 sqlite2 软件

  - zypper in sqlite3# 安装 sqlite3 软件

  - zypper in yast*# 安装所有符合 yast* 名称的软件

  - zypper up# 更新所有软件包到可用的新版本

** Querying

*** Searching Packages

  - zypper search

  - zypper se

#+BEGIN_SRC bash
# Examples:
zypper se -dC --match-words RSI #look for RSI acronym
(case-sensitively), also in summaries and descriptions
zypper se 'yast*' #show all packages starting with 'yast'
zypper se -r upd #list all packages from 'upd' repository
zypper se -i sqlite #show all 'sqlite' installed packages
zypper se -t pattern -r upd #list all patterns available inthe 'upd' repository
#+END_SRC

*** Getting Information about Packages

  - zypper info

  - zypper if

#+BEGIN_SRC bash
#Examples:
zypper info amarok
zypper info -t patch amarok #show info for 'amarok' patch
zypper patch-info amarok #same as above
zypper info -t pattern lamp_server #info 'lamp_server' pattern
#+END_SRC

*** Getting Information about Dependencies

  - zypper what-provides

  - zypper wp

Command 'what-provides' is replaced by 'search --provides --match-exact'.

#+BEGIN_SRC bash
Examples:
zypper wp firefox
#+END_SRC

** Utilities

*** Verify Dependencies

  - zypper verify

  - zypper ve

Note: This is useful in cases of a broken system

*** Install New Recommended Packages

  - zypper install-new-recommends

  - zypper inr

** Package Locks

*** Lock Packages

  - zypper addlock

  - zypper al

#+BEGIN_SRC bash
Examples:
zypper al 'yast2*' #lock all packages starting with 'yast2'
#+END_SRC

*** List Locks

  - zypper locks

  - zypper ll

*** Remove Locks

  - zypper removelock

  - zypper rl

#+BEGIN_SRC bash
Examples:
zypper rl 'yast2*' #remove locks to all packages starting with 'yast2'
#+END_SRC


** Update Management

*** Listing Needed Patches

zypper list-patches or zypper lp


*** Applying Patches

zypper patch


*** Listing All Patches

zypper patches


*** Checking Patches
zypper patch-check or zypper pchk


*** Getting Information About Patches
zypper patch-info
zypper info -t patch

*** Packages Updates

zypper list-updates or zypper lu
zypper update or zypper up

** Distribution Upgrade

zypper dist-upgrade or zypper dup

Note:
When doing a distribution update, the best is to work only with the repositories of the distribution you want to install.

** Vocabulary

***  Repositories

HTTP or FTP server, DVD, or a folder on a local disc. where a group or set of packages are located.

*** Resource Identfiers (URI)

To specify locations of repositories or other resources(RPM files, .repo files) you can use any type of URIs supported

*** Refresh

Refreshing a repository means downloading metadata of packages from the medium (if needed), storing it in local cache (typically under _/var/cache/zypp/raw/<alias>_  directory) and preparsing the metadata into .solv files (building the solv cache), typically under _/var/cache/zypp/solv/<alias>_.

*** Services

Services are one level above repositories and serve to manage repositories or to do some special tasks. Libzypp currently supports only one type of services, the Repository Index Service (RIS).

*** Package Types

zypper works with several types of resource objects, called resolvables. A resolvable is a package, patch, pattern, or a product.

*** package - an ordinary RPM package

*** patch - update of one or more packages.

*** pattern - group of packages required or recommended to install some functionality

*** product - group of packages which are necessary to install a product
