* Single UNIX Specification

本章梳理自维基百科 https://en.wikipedia.org/wiki/Single_UNIX_Specification


** SUSv1

In 1995, the Open Group released the Single UNIX Specification Version 1, 1995 Edition.[1]

This specification consisted of:

- System Interface Definitions, Issue 4, Version 2,

- System Interfaces and Headers, Issue 4, Version 2,

- Commands and Utilities, Issue 4, Version 2,

- X/Open Curses, Issue 4 Version 2,

- Networking Services, Issue 4,

and was at the core of the UNIX 95 brand.

*** 关键点

- Open Group 主导了 SUSv1

- SUSv1 也称为 UNIX 95

- ~X/Open~ X/Open Company, Ltd., originally the Open Group for Unix Systems, was a consortium founded by several ~European UNIX systems manufacturers~ in 1984 to identify and promote open standards in the field of information technology.

- ~OSF~ The Open Software Foundation (OSF) was a ~not-for-profit~ organization founded in 1988 under the U.S. National Cooperative Research Act of 1984 to create an open standard for an implementation of the ~UNIX operating system~

- ~The Open Group~  The Open Group is an industry consortium that seeks to "enable the achievement of business objectives" by developing "open, vendor-neutral technology standards and certifications". It has over 625 members and provides a number of services, including strategy, management, innovation and research, standards, certification, and test development. It was established in 1996 when ~X/Open~ merged with the ~Open Software Foundation~.

- ~The Open Group~ 由 ~X/Open~ 和 ~OSF~ 合并而成


** SUSv2

1997: Single UNIX Specification version 2

In 1997, the Open Group released the Single UNIX Specification Version 2.[3][4]

This specification consisted of:

- the Base Definitions, Issue 5,

- the System Interfaces and Headers, Issue 5,

- the Commands and Utilities, Issue 5,

- the Networking Services, Issue 5,

- the X/Open Curses, Issue 4, Version 2

and was at the core of the ~UNIX 98~ brand.

*** 关键点

- Open Group 主导

- 也称为 UNIX 98


** SUSv3 POSIX:2001

2001: Single UNIX Specification version 3, POSIX:2001

Beginning in 1998, a joint working group known as the Austin Group began to develop the combined standard that would be known as the
Single UNIX Specification Version 3 and as POSIX:2001 (formally: IEEE Std 1003.1-2001). It was released on January 30, 2002.[6]

This standard consisted of:

- the Base Definitions, Issue 6,

- the System Interfaces and Headers, Issue 6,

- the Commands and Utilities, Issue 6,

and is at the core of the ~UNIX 03 brand~.


*** 2004: POSIX:2004

In 2004, a new edition of the POSIX:2001 standard was released, incorporating two technical corrigenda. It is called POSIX:2004 (formally: IEEE Std 1003.1-2004).[8][9]

2004年，新一版的POSIX:2001出现，加入了一些修改。


SUSv3 (IEEE Std 1003.1, 2004 Edition)


*** 关键点

- 奥斯丁公共标准修订工作组 The Austin Common Standards Revision Group https://www.opengroup.org/austin/

2008: Single UNIX Specification version 4, POSIX:2008

- UNIX 03 是指 SUSv3


** SUSv4

In December 2008, the Austin Group published a new major revision, known as ~POSIX:2008~ (formally: ~IEEE Std 1003.1-2008~ ).

This is the core of the Single UNIX Specification, Version 4 (SUSv4).This standard consists of:

- the Base Definitions, Issue 7,

- the System Interfaces and Headers, Issue 7,

- the Commands and Utilities, Issue 7.

*** 2013 Edition

The Technical Corrigendum 1 is mostly targeting internationalization and it introduces a role-based access model. It was published in
2012 for the Unix Base specification and it is registered as the 2013 Edition of POSIX 2008. A trademark ~UNIX V7~ (not to be confused
with V7 UNIX, the version of Research Unix from 1979) has been created to mark compliance with SUS Version 4.

*** 2016 Edition

The Technical Corrigendum 2 has been published in September 2016, leading into IEEE Std 1003.1-2008, 2016 Edition and Single UNIX
Specification, Version 4, 2016 Edition.

2018 Edition

*** In January 2018 an "administrative rollup" edition, susv4-2018, was released. It incorporates Single UNIX Specification version 4 TC1
and TC2, and is technically identical to the 2016 edition.[15]

*** 关键点

- UNIX V7 是指 SUSv4
