* proc

proc文件系统是一个伪文件系统，它只存在内存当中，而 不占用外存空间。

它以文件系统的方式为访问系统内核数据的操作提供接口。用户和应用程序可以通过proc得到系统的信息，并可以改变内核的某些参数。

由于系统的信息，如进程，是动态改变的，所以用户或应用程序读取proc文件时，proc文件系统是动态从系统内核读出所需信息并提交的。


1. apm 高级电源管理信息

1. cmdline 内核命令行

1. Cpuinfo 关于Cpu信息

1. Devices 可以用到的设备（块设备/字符设备）

1. Dma 使用的DMA通道

1. Filesystems 支持的文件系统

1. Interrupts 中断的使用

1. Ioports I/O端口的使用

1. Kcore 内核核心印象

1. kmsg 内核消息

1. ksyms 内核符号表

1. Loadavg 负载均衡

1. Locks 内核锁

1. Meminfo 内存信息

Misc 杂项

1. modules 加载模块列表

1. mounts 加载的文件系统

1. partitions 系统识别的分区表

1. rtc 实时时钟

1. slabinfo Slab池信息

1. stat 全面统计状态表

1. swaps 对换空间的利用情况

1. version 内核版本

1. uptime 系统正常运行时间



并不是所有这些目录在你的系统中都有，这取决于你的内核配 置和装载的模块。另外，在/proc下还有三个很重要的目录：net，scsi和sys。 Sys目录是可写的，可以通过它来访问或修改内核的参数（如释放内存），而net和scsi则依赖于内核配置。例如，如果系统不支持scsi，则scsi 目录不存在。



除了以上介绍的这些，还有的是一些以数字命名的目录，它们 是进程目录。系统中当前运行的每一个进程都有对应的一个目录在/proc下，以进程的 PID号为目录名，它们是读取进程信息的接口。而self目录则是读取进程本身的信息接口，是一个link。Proc文件系统的名字就是由之而起。进程目 录的结构如下：



目录名称 目录内容

Cmdline  命令行参数

Environ    环境变量值

Fd             一个包含所有文件描述符的目录

Mem         进程的内存被利用情况

Stat          进程状态

Status     进程当前状态，以可读的方式显示出来

Cwd        当前工作目录的链接

Exe          指向该进程的执行命令文件

Maps      内存映象

Statm     进程内存状态信息

Root       链接此进程的root目录



用户如果要查看系统信息，可以用cat命令。例如：



# cat /proc/interrupts

CPU0

0: 8728810 XT-PIC timer

1: 895 XT-PIC keyboard

2: 0 XT-PIC cascade

3: 531695 XT-PIC aha152x

4: 2014133 XT-PIC serial

5: 44401 XT-PIC pcnet_cs

8: 2 XT-PIC rtc

11: 8 XT-PIC i82365

12: 182918 XT-PIC Mouse

13: 1 XT-PIC fpu PS/2

14: 1232265 XT-PIC ide0

15: 7 XT-PIC ide1

NMI: 0



用户还可以实现修改内核参数。在/proc文件系统中有一 个有趣的目录：/proc/sys。它不仅提供了内核信息，而且可以通过它修改内核参数，来优化你的系统。但是你必须很小心，因为可能会造成系统崩溃。最 好是先找一台无关紧要的机子，调试成功后再应用到你的系统上。



要改变内核的参数，只要用vi编辑或echo参数重定向到文件中即可。下面有一个例子：



# cat /proc/sys/fs/file-max

4096

# echo 8192 > /proc/sys/fs/file-max

# cat /proc/sys/fs/file-max

8192



如果你优化了参数，则可以把它们写成添加到文件rc.local中，使它在系统启动时自动完成修改。



/proc文件系统中网络参数



在/proc/sys/net/ipv4/目录下，包含的是和tcp/ip协议相关的各种参数，下面我们就对这些网络参数加以详细的说明。



ip_forward 参数类型：BOOLEAN

0 - 关闭(默认值)

not 0 - 打开ip转发



在网络本地接口之间转发数据报。该参数非常特殊，对该参数的修改将导致其它所有相关配置参数恢复其默认值(对于主机参阅RFC1122，对于路由器参见RFC1812)



ip_default_ttl 参数类型：INTEGER

默认值为 64 。表示IP数据报的Time To Live值。



ip_no_pmtu_disc 参数类型：BOOLEAN

关闭路径MTU探测，默认值为FALSE



ipfrag_high_thresh 参数类型：整型

用来组装分段的IP包的最大内存量。当ipfrag_high_thresh数量的内存被分配来用来组装IP包，则IP分片处理器将丢弃数据报直到ipfrag_low_thresh数量的内存被用来组装IP包。



ipfrag_low_thresh 参数类型：整型

参见ipfrag_high_thresh。



ipfrag_time 参数类型：整型

保存一个IP分片在内存中的时间。



inet_peer_threshold 参数类型：整型

INET对端存储器某个合适值，当超过该阀值条目将被丢弃。该阀值同样决定生存时间以及废物收集通过的时间间隔。条目越多﹐存活期越低﹐GC 间隔越短



inet_peer_minttl 参数类型：整型

条目的最低存活期。在重组端必须要有足够的碎片(fragment)存活期。这个最低存活期必须保证缓冲池容积是否少于 inet_peer_threshold。该值以 jiffies为单位测量。
