* 为什么pipe 必须关闭

#+BEGIN_SRC C
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>


int main(int argc, const char* argv[]) {
  int fd[2];
  int ret = pipe(fd);

  if (ret == -1) {
    perror("pipe error");
    exit(1);
  }

  pid_t pid = fork();
  if (pid == -1) {
    perror("fork error");
    exit(1);
  }

  if (pid > 0) {
    pid_t myid = getpid();
    //    printf("Parent ID is %ld\n", (long) myid);
    //    printf("pid is %ld\n", (long) pid);

    close(fd[0]);
    dup2(fd[1], STDOUT_FILENO);
    execlp("ps", "ps", "aux", NULL);
    perror("execclp");
    exit(1);
  } else if (pid == 0) {
    pid_t myid2 = getpid();
    //    printf("child ID is %ld\n", (long) myid2);
    printf("pid is %ld\n", (long) myid2);

    close(fd[1]);   // POS A
    dup2(fd[0], STDIN_FILENO);
    execlp("grep", "grep", "--color", "bash", NULL);
    printf("-----------------------\n");
    exit(1);
  }

  return 0;
}
#+END_SRC

答案参考： https://stackoverflow.com/questions/19265191/why-should-you-close-a-pipe-in-linux

If you connect two processes - parent and child - using a pipe, you create the pipe before the fork.

The fork makes the both processes have access to both ends of the pipe. This is not desirable.

The reading side is supposed to learn that _the writer has finished if it notices an ~EOF~ condition_ . This can only happen _if all writing sides are closed_ . So it is best if it closes its writing FD ASAP.


write端尽可以早些关闭

The writer should close its reading FD just in order not to have too many FDs open and thus reaching a maybe existing limit of open FDs. Besides, if the then only reader dies, the writer gets notified about this by getting a SIGPIPE or at least an EPIPE error (depending on how signals are defined). If there are several readers, the writer cannot detect that "the real one" went away, goes on writing and gets stuck as the writing FD blocks in the hope, the "unused" reader will read something.

So here in detail what happens:

- parent process calls pipe() and gets 2 file descriptors: let's call it ~rd~ and ~wr~ .

- parent process calls fork(). Now both processes have a ~rd~ and a ~wr~ .

Suppose the child process is supposed to be the reader.

Then

- the parent should close its reading end (for not wasting FDs and for proper detection of dying reader) and

- the child must close its writing end (in order to be possible to detect the EOF condition).
