#+TITLE: 操作系统

* intro

操作系统整理


* 整理说明

1. 不要尝试把一些shell命令放入到webtech repo中，曾尝试过，但文件更加混乱，一些底层的机制和命令息息相关。


“在我成长的过程中，我曾花了许多气力来把自己锻炼成钢铁。锻炼的方法，不论是东海圣人的，还是西海圣人的，我都一网兜收，从摸索和试验中，求得安身立命。这种自我炼钢，是很用心的。我今天能有一些个性、一些独来独往的气魄、一些“虽千万人，吾往矣”的决绝，追溯起来，都跟我早年的刻苦自励有密切关系。”

第一等人

躺在床上冥想“第一等人”的境界(如富兰克林见到伏尔泰，胡适见到罗素)，的确使我胸怀宏伟，多想想“第一等人”自处与对人的态度，会使我心中长存着第一等念头，而把第二等以下的思想、言论与行为全抹去了。凡是属于“第一等人”的人，他们应付欢乐与不幸的态度几乎都是一样的。

老罗斯福总统曾说他每逢遇着困难的问题时，就抬起头来望着挂在墙上的林肯的相片，并且问自己道：“倘若林肯遇到这个问题时，他将怎样做呢？”这是给自己去从取舍的一个好标准。遇事能学得用“第一等人”的观点去看事情，不但是一种伟大的作风，并且还会给自己带来许多自慰与安静。

亚里士多德说：“气度宽宏的人无论遭遇命运为善为恶，皆能适度以应之。成功不以为喜，失败不以为悲，外界的毁誉褒贬，一不介怀，只是为所当为，为所可为而已。”这是何等恢弘的胸襟与素养！

英雄之气的意志

我做人在方法上的两大元素：理智与意志。理智为常，为体；意志为变，为用。

钱思亮说：“胡博士虽然一身有好几种病，但毕竟是一个意志非常坚强的人，他之能够吃苦耐劳，向为朋友们所最钦佩。”但是胡适的意志是长者化了的，未免缺乏英雄之气，如今我所要求自己的是一种有“英雄之气的意志”。

有条件地回想

事情过去了就总算是过去了，我虽不愿遗忘，但也的确不愿再回想，一切欢乐、眼泪与名分都已逐渐成为往事。既然都成为往事，“我们该不要回头望，除非是要从过去错误中吸取有用的教训，和为了从经验中获得益处”(华盛顿)，否则对既往的缅怀与回想都将是我目前的戕贼与毒素，我为自己订了一个严格的标准：凡是对“现在”有害的回想与想象，我都要一律不去想它。

毒蛇喻

在你意想不到地突然被一条毒蛇咬了一口的时候，你该立刻用各种办法去解毒，而不该继续震撼于这种意外，以致扩大你中毒的程度。你要告诉你自己说：不要研究你为什么会被咬了，也不要研究你怎样被咬了，也不要感慨你被咬得如何重……这些都是无益之举，它们除了拖延你中毒的时间，使你中毒更深以外，对你一点好处都没有。

论懒惰

我发现我若用苏格拉底的标准来衡量自己，我也和这些男人们无异———也是一个五十步笑百步的懒蛋。苏格拉底的标准是：“不单只是不做事的人，还有那些原可做得更好的人，也算是懒惰的。”直到今天午后，我才真正地发现自己的确是一个懒惰习惯甚深的人！追想起来，我的读书生活，即使有许多地方我还是比别人高明，可是我还是非常不满意的，因为我“原可做得更好”。詹姆士说：“若拿我们应当成就的标准，我们只是半醒着，我们只用了我们自己身体和智力的富源的一小部分。广泛地说，人们现在的生活距他们的限度尚远，我们具有许多力量平常不会利用。”……

懒惰不是一种清福而是一种不安和不幸(对内心说来是不安，对事业说来是不幸)，内心的快乐与事业的成功，都不是懒惰所能造成的。吕坤说：“体懈、神昏、志消、气沮，天下事不是这般人干的。”好逸恶劳、怕吃苦、贪容易，都不是成大事者的气象。

做个宁静的人
    自图书馆做工回来，心中真是恬静极了，这可说全是“不做自了汉”的胸怀与志愿带给我的安宁，养成一种恬静安宁的习惯，对我来说这漫长的生活将是一个十分必要的事。弥尔顿说“宁静是克己的王冠”，克己的功夫到了炉火纯青的地步时，我便会得到一个永远平稳和谐的心境了。

“宁静的人，虽然遇到人生的大恐慌，心底也是一波不起。他们在日常生活中，盖已培养了一种伟大的定力，任何刺激，可以不为所动。”
