* date

** command

#+BEGIN_SRC bash
# Set date from the command line
date +%Y%m%d -s "20120418"

# Set time from the command line
date +%T -s "11:14:00"

# Set time and date from the command line
date -s "19 APR 2012 11:14:00"
#+END_SRC

Linux check date from command line

date

Will show you something like this:

Thu Apr 19 15:17:34 BOT 2012



** Set the timezone

To set the timezone of your system clock do the following:

cp /usr/share/zoneinfo/America/La_Paz /etc/localtime

Choose the right timezone for you.

Automatically adjust your computer clock

To have your system to automatically adjust time we need to install ntp. Get it from your repository. Once installed you can configure it this way:

Edit the file /etc/ntpd.conf. It will look like this:

# With the default settings below, ntpd will only synchronize your clock.
#
# For details, see:
# - the ntp.conf man page
# - http://support.ntp.org/bin/view/Support/GettingStarted
# - https://wiki.archlinux.org/index.php/Network_Time_Protocol_daemon

# Associate to public NTP pool servers; see http://www.pool.ntp.org/
server 0.pool.ntp.org
server 1.pool.ntp.org
server 2.pool.ntp.org

# Only allow read-only access from localhost
restrict default noquery nopeer
restrict 127.0.0.1
restrict ::1

# Location of drift and log files
driftfile /var/lib/ntp/ntp.drift
logfile /var/log/ntp.log

# NOTE: If you run dhcpcd and have lines like 'restrict' and 'fudge' appearing
# here, be sure to add '-Y -N' to the dhcpcd_ethX variables in /etc/conf.d/net

** -d, --data=STRING

使用字符串来表达时间

date -d 'tommorrow'

date -d 'today 16:00:00' '+%s'


date -d 'tommorrow' 命令输出时的时间，再加24小时，即明天的此刻

date -d 'tommorrow 00:00:00'

tomorrow=$(( today + 86400 ))

** FORMAT

在crontab中 =%= 需要转义

%%
