#+TITLE: 进程组

*  进程组、会话、控制终端

** 进程组

shell里的每个进程都属于一个进程组，创建进程组的目的是用于简化向组内所有进程发送信号的操作，即如果一个信号是发给一个进程组，则这个组内的所有进程都会受到该信号【方便管理】。

PGID进程组ID

进程组内的所有进程都有相同的PGID，等于该组组长的PID。（进程组组长：进程组中有一个进程担当组长。进程组ID（PGID）等于进程组组长的进程ID。已知一个进程，要得到该进程所属的进程组ID可以调用getpgrp。一个进程可以通过另一个系统调用setpgrp来加入一个已经存在的进程组或者创建一个新的进程组。

如果内核支持_POSIX_JOB_CONTROL（该宏被定义）则内核会为Shell 上的每一条命令行（可能由多个命令通过管道等连接）创建一个进程组。从这点上看，进程组不是进程的概念，而是shell上才有，所以在task_struct里并没有存储进程组id之类的变量。

进程组的生命周期到组中最后一个进程终止或其加入其他进程组（离开本进程组）为止。

** 会话

一般一个用户登录后新建一个会话，每个会话也有一个ID来标识（SID）。登录后的第一个进程叫做会话领头进程（session leader），通常是一个shell/bash。对于会话领头进程，其PID=SID。

控制终端
一个会话一般会拥有一个控制终端用于执行IO操作。会话的领头进程打开一个终端之后, 该终端就成为该会话的控制终端。与控制终端建立连接的会话领头进程也称为控制进程 (controlling process) 。一个会话只能有一个控制终端。

前台进程组

该进程组中的进程能够向终端设备进行读、写操作的进程组。例如登陆shell（例如bash）通过调用int tcsetpgrp(int fd, pid_t pgrp); 函数设置为某个进程组pgrp关联终端设备fd，该函数执行成功后，该进程组pgrp成为前台进程组。

后台进程组

该进程组中的进程只能够向终端设备写。

终端进程组ID
每个进程还有一个属性，终端进程组ID(TPGID)，用来标识一个进程是否处于一个和终端相关的进程组中。前台进程组中的进程的TPGID=PGID，后台进程组的PGID≠TPGID。若该进程和任何终端无关，其值为-1。通过比较他们来判断一个进程是属于前台进程组，还是后台进程组。

进程组、对话期和控制终端关系

进程组、对话期和控制终端关系
每个会话有且只有一个前台进程组，但会有0个或者多个后台进程组。
产生在控制终端上的输入（Input）和信号（Signal）将发送给会话的前台进程组中的所有进程。对于输出（Output）来说，则是在前台和后台共享的，即前台和后台的打印输出都会显示在屏幕上。
终端上的连接断开时 (比如网络断开或 Modem 断开), 挂起信号将发送到控制进程(controlling process) 。
一个用户登录后创建一个会话。一个会话中只存在一个前台进程组，但可以存在多个后台进程组。第一次登陆后第一个创建的进程是shell，也就是会话的领头进程，该领头进程缺省处于一个前台进程组中并打开一个控制终端可以进行数据的读写。当在shell里运行一行命令后（不带&）创建一个新的进程组，命令行中如果有多个命令会创建多个进程，这些进程都处于该新建进程组中，shell将该新建的进程组设置为前台进程组并将自己暂时设置为后台进程组。
举例
打开第一个终端执行命令：）
