* uname & lsb_release

** ref

https://www.patchesoft.com/learning-linux-how-to-find-what-version-of-linux-youre-running-command-uname-and-lsb_release


uname -a

Output:

Linux myhost.com 3.2.0-4-amd64 #1 SMP Debian 3.2.41-2+deb7u2 x86_64 GNU/Linux

This command tells you all the information about the server you're running. Using the -a option, it will output all available
information in the following order: kernel-name nodename kernel-release kernel-version machine processor hardware platform
operating system There are other commands also that can help you obtain specific information:

| Command      | Information                                             |
|--------------+---------------------------------------------------------|
| uname --help |  Returns the help manual for the uname command, including all available options. |
| uname -a  | Prints all information for the server/system you're on. |
| uname -s  | Prints the kernel name                                  |
| uname -n  | Prints the node name                                    |
| uname -r  | Prints the kernel release data                          |
| uname -v  | Prints the kernel version data                          |
| uname -m  | Prints the machine data                                 |
| uname -p  | Prints the processor information                        |
| uname -i  | Prints the platform hardware information                |
| uname -o  | Prints the operating system information                 |

Sometimes using uname -a isn't enough. You might need to know the exact ~linux distro~ . You can do that by using the lsb_release command:

lsb_release -a

Output:

No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 7.6 (wheezy)
Release: 7.6
Codename: wheezy

Now you can see what version of the linux distro you're using and see if there are any upgrades/updates available for it.
