* plugin

#+BEGIN_SRC bash
plugins=(
    git
    gradle
    jenv
    autojump
    zsh-autosuggestions
    zsh-syntax-highlighting
)
#+END_SRC


fuck 进行命令查询

fzf

ctop




1. thefuck	Magnificent app which corrects your previous console command.

1. fzf	A command-line fuzzy finder

1. bat	A cat(1) clone with wings.

1. ripgrep	ripgrep recursively searches directories for a regex pattern while respecting your gitignore

1. powerlevel10k	A Zsh theme

1. zsh-autosuggestions	Fish-like autosuggestions for zsh

1. solarized	precision color scheme for multiple applications (terminal, vim, etc.) with both dark/light modes

1. diff-so-fancy	Good-lookin’ diffs. Actually… nah… The best-lookin’ diffs.

1. z	z - jump around

1. powerlevel9k	Powerlevel9k was a tool for building a beautiful and highly functional CLI, customized for you. P9k had a substantial impact on CLI UX, and its legacy is now continued by P10k.

1. autojump	A cd command that learns - easily navigate directories from the command line

1. zsh-syntax-highlighting	Fish shell-like syntax highlighting for Zsh.

1. asdf	Extendable version manager with support for Ruby, Node.js, Elixir, Erlang & more

1. ctop	Top-like interface for container metrics

1. kubectx	Faster way to switch between clusters and namespaces in kubectl

1. tmuxinator	Manage complex tmux sessions easily

1. tig	Text-mode interface for git

1. navi	An interactive cheatsheet tool for the command-line

1. peco	Simplistic interactive filtering tool
