* 快捷键

** Win键

win+ e；explorer。

win+ d；显示桌面，再按一次恢复窗口。

win+ r；运行对话框，这个运行如果用的好，基本上你就可以告别鼠标；

  1. 在运行对话框中输入cmd，进入命令行模式。

  1. 在运行对话框中输入control，进入控制面板。

  1. 在运行对话框中输入appwiz.cpl,进入程序与功能。

  1. 在运行对话框中输入msconfig，进入系统配置。

  1. 在运行对话框中输入chrome，打开谷歌浏览器，前提是你安装了chrome。同理这个可以用来快捷的打开一些应用程序。如果是经常使用的应用程序可以将它固定到任务栏，然后通过快捷键，win+ 1、win + 2、win + 3来进行快捷访问。

  1. 在运行对话框中输入shutdown-s -t 0；立刻关机，后面的0代表0秒后关机，可以修改为600，就是十分钟后关机。

  1. 在运行对话框中输入shutdown-a，取消定时关机。

win+ x；这应该是window 8之后才有的快捷键，可以呼出很多相关设置。

win+ space；切换输入法；shift可以快速切换中英文。

win+ l；锁定屏幕。

win+ q；呼出小娜，文字输入。

win+ c；呼出小娜，语音输入。

win+ s；搜索。

win 与桌面相关

  1. win+ tab；切换桌面。

  1. win+ ctrl + d；创建新桌面；

  1. win+ ctrl + f4；关闭当前桌面，已经打开的应用程序不会丢失，会回到默认的桌面。

  1. win+ ctrl + 方向键；快速切换桌面。

  1. win键组合方向键可以控制窗口的大小，这个你可以自己试一下。

  1. win+ 向上方向键；窗口最大化。

  1. win+ 向左 + 向上；左上角四分之一窗口。

** Ctrl键和Alt键，Ctrl键和Alt键大多数会配合应用程序使用。

ctrl+ shift + esc；呼出任务管理器。

在edge浏览器中的一些快捷键，chrom里也是适用的。

ctrl+ w；关闭标签。

ctrl+ shift + t;恢复刚关闭的标签。

ctrl+ h；历史纪录。

ctrl+ j；下载列表。

ctrl+ f；在页面内查找。

ctrl+ n；新窗口

ctrl+ 1到ctrl +8；打开对应的标签。

ctrl+ 9；打开最后的那个标签。

ctrl+ tab；切换到下一个标签。

ctrl+ shift + tab；切换到上一个标签。

ctrl+ r；重新加载当前页。

ctrl+ d；加入书签。

alt+ d；输入定位到地址栏。f6、ctrl + l都有同样的效果。

alt+ f4；关闭应用程序。

alt+ space；呼出窗口控制的菜单

ctrl+ c，ctrl + v这些都很常用我就不多说了。

如果你使用的浏览器是chrome或者firefox推荐使用Vimium，这个简直就是效率神器，上网从此就摆脱鼠标了。

很多应用程序中有自己的一套功能的快捷键，只能靠题主自己去搜索了。

** 键盘上一的一些功能键

了解这些功能键的使用方法。

F1键；帮助

F2键；选择文件或文件夹的情况下，重命名该文件文件夹。

F3键；搜索

F4键；IE中的地址栏。

F5键；刷新。

F10键；shift+ f10显示右键菜单

F11键；浏览器或者资源管理器的全屏显示

capslock键；锁定大写。

home键；光标移动到句首。shift+ home，选择从光标位置到句首的字符，也可以使用方向键逐个字符的选择，end键同理。

end键；光标移动到句尾。

pgdown键；向下翻页。

pgup键；向上翻页。

backspace键；向前删除字符。

delete；删除键。向后删除字符。

prtsc；这个按键可以用来快速截屏。按下按键之后咋一看没啥反应，这时候你可以打开windows自带的画图程序，按ctrl + v粘贴，你就可以另存为图片格式了。


fn键；笔记本上的功能键，组合f1到f12有不同的功能。自己试试吧，每台电脑都不一样。

还有一个按键很有用，但是我叫不出名字。一般会安排在右ctrl旁边。像功能列表一样的按键，这个按键可以代替鼠标右键。

基本上把上述的快捷键弄熟练的话，很大程度上就能减少对鼠标的依赖了。
