* 总线

** 总结分类

按总线的层次结构可分为：

  - CPU总线：包括地址线(CAB)、数据线(CDB)和控制线(CCD)，它用来连接CPU和控制芯片。

  - 存贮总线：包括地址线(MAB)、数据线(MDB)和控制线(MCD)，用来连接存储控制器和DRAM。

  - 系统总线：也称为I/O通道总线，包括地址线(SAB)、数据线(SDB)和控制线(SCB)，用来与扩充插槽上的各扩充板卡相连接。系统总线有多种标准，以适用于各种系统。

  - 外部总线：用来连接外设控制芯片，如主机板上的I/O控制器和键盘控制器。包括地址线(XAB)、数据线(XDB)和控制线(XCB)。

  CPU总线、存储总线、外部总线在系统板上，不同的系统采用不同的芯片集。这些总线不完全相同，也不存在互换性问题。系统总线是与I/O扩充插槽相连的，I/O插槽中可插入各式各样的扩充板卡，作为各种外设的适配器与外设连接。系统总线必须有统一的标准，以便按照这些标准设计各类适配卡。因此，我们实际上要讨论的总线就是系统总线，各种总线标准也主要是指系统总线的标准。

** 系统总线的标准

一般说的总结是 =系统总线= ，它有以下标准：

  - ISA(Industry Standard Architecture)是IBM公司为286/AT电脑制定的总线工业标准。也称为AT标准。

  - MCA(Micro Channel Architecture)，是IBM公司专为其PS/2系统开发的微通道总线结构。由于执行的是使用许可证制度，因此未能得到有效推广。

  - EISA(Extended Industry Standard Architecture)，是EISA集团(1988年由Compaq、HP、AST、NEC、Olivetti、Zenith、Tandy等组成)为32位CPU设计的总线扩展工业标准。

  - VESA(Video Electronics Standards Association)，是VESA组织(1992年由IBM、Compaq等发起，有120多家公司参加)按Local Bus(局部总线)标准设计的一种开放性总线。

  - PCI(Peripheral Component Interconnect)，是SIG(Special Interest Group)集团推出的总线结构。1992年起，先后有Intel、HP、IBM、Apple、DEC、Compaq、NEC等著名的厂商加盟重新组建。

  - AGP（Accelerated Graphics Port）即加速图形端口。它是一种为了提高视频带宽而设计的总线规范。因为它是点对点连接，即连接控制芯片和AGP显示卡，因此严格说来，AGP也是一种接口标准。

** PCI总线

*** 概述

90年代，随着图形处理技术和多媒体技术的广泛应用，在以Windows为代表的图形用户接口(GUI)进入PC机之后，要求有高速的图形描绘能力和I/O处理能力。这不仅要求图形适配卡要改善其性能，也对总线的速度提出了挑战。实际上当时外设的速度已有了很大的提高，如硬磁盘与控制器之间的数据传输率已达10MB/s以上，图形控制器和显示器之间的数据传输率也达到69MB/s。通常认为I/O总线的速度应为外设速度的3-5倍。因此原有的ISA、EISA已远远不能适应要求，而成为整个系统的主要瓶颈。因此对总线提出了更高的性能要求，从而促使了总线技术进一步发展。

1991年下半年，Intel公司首先提出了PCI的概念，并联合IBM、Compaq、AST、HP、DEC等100多家公司成立了PCI集团，其英文全称为：Peripheral Component Interconnect Special Interest Group(外围部件互连专业组)，简称PCISIG。PCI是一种先进的局部总线，已成为局部总线的新标准。PCI总线插槽如图4所示。

*** PCI局部总线的主要性能和特点

PCI总线是一种不依附于某个具体处理器的局部总线。从结构上看，PCI是在CPU和原来的系统总线之间插入的一级总线，具体由一个桥接电路实现对这一层的管理，并实现上下之间的接口以协调数据的传送。管理器提供了信号缓冲，使之能支持10种外设，并能在高时钟频率下保持高性能。PCI总线也支持总线主控技术，允许智能设备在需要时取得总线控制权，以加速数据传送。

  1. PCI总线的主要性能

    - 支持10台外设

    - 总线时钟频率33.3MHz/66MHz

    - 最大数据传输速率133MB/s

    - 时钟同步方式

    - 与CPU及时钟频率无关

    - 总线宽度 32位（5V）/64位（3.3V）

    - 能自动识别外设

    - 特别适合与Intel的CPU协同工作

  1. 其它特点

    - 具有与处理器和存储器子系统完全并行操作的能力

    - 具有隐含的中央仲裁系统

    - 采用多路复用方式（地址线和数据线）减少了引脚数

    - 支持64位寻址

    - 完全的多总线主控能力

    - 提供地址和数据的奇偶校验

    - 可以转换5V和3.3V的信号环境

*** PCI总线信号定义

  要引脚 主控设备49条 目标设备47条

  可选引脚 51条（主要用于64位扩展、中断请求、高速缓存支持等）

  总引脚数 120条（包含电源、地、保留引脚等）

*** PCI总线结构连接方式 

PCI总线的基本连接方式如图5所示。从图中可以看到CPU总线和PCI总线由桥接电路（习惯上称为北桥芯片）相连。芯片中除了含有桥接电路外，还有Cache控制器和DRAM控制器等其它控制电路。PCI总线上挂接高速设备，如图形控制器、IDE设备或SCSI设备、网络控制器等。PCI总线和ISA/EISA总线之间也通过桥接电路（习惯上称为南桥芯片）相连，ISA/EISA上挂接传统的慢速设备，继承原有的资源。

此外，PCI总线还有其它一些连接方式，如双PCI总线 方式、PCI TO PCI方式、多处理器服务器方式等。鉴于篇幅关系不再详细介绍。

*** PCI总线的新发展

当前PCI总线的最高版本是2.1版，虽然在理论上达到66MHz的时钟频率，但对于新型的CPU（如Xeon、Katmai等）和高总线频率主板是完全不能适应的。Intel推出的新一代PCI总线规范称为PCI－X，主要适用于133MHz总线时钟频率的台式机主板。此外Intel还准备推出一种称为MINI PCI的总线标准。MINI PCI对原来的PCI总线在控制线路和功能上作了改进，减小了外形尺寸，使之适用于便携式机器。
