* Tutorial

** Basic

想要书写一个完整的 Makefile文件，需要了解 Makefile 的相关的书写规则。我们已经知道了 Makefile 描述的是文件编译的相关规则，它的规则主要是两个部分组成，分别是依赖的关系和执行的命令，其结构如下所示：

#+BEGIN_SRC makefile
targets : prerequisites
    command
#+END_SRC

或者是

#+BEGIN_SRC makefile
targets : prerequisites; command
    command
#+END_SRC

相关说明如下：

- targets：规则的目标，可以是 Object File（一般称它为中间文件），也可以是可执行文件，还可以是一个标签；

- prerequisites：是我们的依赖文件，要生成 targets 需要的文件或者是目标。可以是多个，也可以是没有；

- command：make 需要执行的命令（任意的 shell 命令）。可以有多条命令，每一条命令占一行。

注意：我们的目标和依赖文件之间要使用冒号分隔开，命令的开始一定要使用Tab键。

通过下面的例子来具体使用一下 Makefile 的规则，Makefile文件中添代码如下：

#+BEGIN_SRC makefile
test:test.c
    gcc -o test test.c
#+END_SRC

上述代码实现的功能就是编译 test.c 文件，通过这个实例可以详细的说明 Makefile 的具体的使用。其中 test 是的目标文件，也是我们的最终生成的可执行文件。依赖文件就是 test.c 源文件，重建目标文件需要执行的操作是gcc -o test test.c。这就是 Makefile 的基本的语法规则的使用。

使用 Makefile 的方式：首先需要编写好 Makefile 文件，然后在 shell 中执行 make 命令，程序就会自动执行，得到最终的目标文件。

通过上面的例子我们可以了解到，Makefile 的规则很简单，但这并不是 Makefile 的全部，这个仅仅是它的冰山一角。仅仅靠一个规则满足不了我们对于大的工程项目的编译。甚至几个文件的编译都会出现问题，所以要学习的东西还有很多。


*** 格式注意点

makefile是由一组规则组成的，分为3个部分： 一个目标，一个先决条件，一个命令

  - Makefile 使用 =TAB= 作为缩进，而非空格。

  - 目标和条件之间用 =:= 格开

  - 如果make执行时没有指定目标，会从 =all= 开始

其他注意点：

  假目标：它不代表文件，如clean, all，install等，只是一个标签

*** 五个部分

简单的概括一下Makefile 中的内容，它主要包含有五个部分，分别是：

- ~显式规则~ 显式规则说明了，如何生成一个或多的的目标文件。这是由 Makefile 的书写者明显指出，要生成的文件，文件的依赖文件，生成的命令。

- ~隐晦规则~ 由于我们的 make 命名有自动推导的功能，所以隐晦的规则可以让我们比较粗糙地简略地书写 Makefile，这是由 make 命令所支持的。

- ~变量的定义~ 在 Makefile 中我们要定义一系列的变量，变量一般都是字符串，这个有点像C语言中的宏，当 Makefile 被执行时，其中的变量都会被扩展到相应的引用位置上。

- ~文件指示~ 其包括了三个部分:

  1. 一个是在一个 Makefile 中引用另一个 Makefile，就像C语言中的 include 一样；

  1. 另一个是指根据某些情况指定 Makefile中的有效部分，就像C语言中的预编译 #if 一样；

  1. 还有就是定义一个多行的命令。

- ~注释~ Makefile 中只有行注释，和 UNIX 的 Shell 脚本一样，其注释是用“#”字符，这个就像 C/C++ 中的“//”一样。如果你要在你的 Makefile 中使用“#”字符，可以用反斜框进行转义，如：“\#”。


** 通配符

Makefile 是可以使用 shell 命令的，所以 shell 支持的通配符在 Makefile 中也是同样适用的。

shell 中使用的通配符有："*"，"?"，"[...]"。具体看一下这些通配符的表示含义和具体的使用方法。

- ~*~  匹配0个或者是任意个字符

- ~?~  匹配任意一个字符

- ~[]~ 我们可以指定匹配的字符放在 "[]" 中

通配符可以出现在模式的规则中，也可以出现在命令中，详细的使用情况如下。

实例 1：

#+BEGIN_SRC makefile
.PHONY:clean
clean:
    rm -rf *.o test
#+END_SRC

这是在 Makefile 中经常使用的规则语句。这个实例可以说明通配符可以使用在规则的命令当中，表示的是任意的以 .o 结尾的文件。

实例 2：

#+BEGIN_SRC makefile
test:*.c
    gcc -o $@ $^
#+END_SRC

这个实例可以说明我们的通配符不仅可以使用在规则的命令中，还可以使用在规则中。用来表示生所有的以 .c 结尾的文件。

但是如果我们的通配符使用在依赖的规则中的话一定要注意这个问题： _不能通过引用变量的方式来使用_ ，如下所示。

#+BEGIN_SRC makefile
OBJ=*.c
test:$(OBJ)
    gcc -o $@ $^
#+END_SRC

我们去执行这个命令的时候会出现错误，提示我们没有 "*.c" 文件，实例中我们相要表示的是当前目录下所有的 ".c" 文件，但是我们在使用的时候并没有展开，而是直接识别成了一个文件。文件名是 "*.c"。

如果我们就是相要通过引用变量的话，我们要使用一个函数 "wildcard"，这个函数在我们引用变量的时候，会帮我们展开。我们把上面的代码修改一下就可以使用了。

#+BEGIN_SRC makefile
OBJ=$(wildcard *.c)
test:$(OBJ)
    gcc -o $@ $^
#+END_SRC

这样我们再去使用的时候就可以了。调用函数的时候，会帮我们自动展开函数。

还有一个和通配符 "*" 相类似的字符，这个字符是 "%"，也是匹配任意个字符，使用在我们的的规则当中。

#+BEGIN_SRC makefile
test:test.o test1.o
    gcc -o $@ $^
%.o:%.c
    gcc -o $@ $^
#+END_SRC

"%.o" 把我们需要的所有的 ".o" 文件组合成为一个列表，从列表中挨个取出的每一个文件，"%" 表示取出来文件的文件名（不包含后缀），然后找到文件中和 "%"名称相同的 ".c" 文件，然后执行下面的命令，直到列表中的文件全部被取出来为止。

这个属于 Makefile 中静态模规则：规则存在多个目标，并且不同的目标可以根据目标文件的名字来自动构造出依赖文件。跟我们的多规则目标的意思相近，但是又不相同。

** 变量的定义和使用

变量可以用来保存一个值，或者是使用变量进行运算操作。

*** 变量的定义

#+BEGIN_SRC makefile
变量的名称=值列表
#+END_SRC

Makefile 中的变量的使用其实非常的简单，因为它并没有像其它语言那样定义变量的时候需要使用数据类型。

变量的名称可以由大小写字母、阿拉伯数字和下划线构成。等号左右的空白符没有明确的要求，因为在执行 make 的时候多余的空白符会被自动的删除。至于值列表，既可以是零项，又可以是一项或者是多项。如：

#+BEGIN_SRC makefile
VALUE_LIST = one two three
#+END_SRC

调用变量的时候可以用 "$(VALUE_LIST)" 或者是 "${VALUE_LIST}" 来替换，这就是变量的引用。实例：

#+BEGIN_SRC makefile
OBJ=main.o test.o test1.o test2.o
test:$(OBJ)
      gcc -o test $(OBJ)
#+END_SRC

这就是引用变量后的 Makefile 的编写，比我们之前的编写方式要简单的多。当要添加或者是删除某个依赖文件的时候，我们只需要改变变量"OBJ" 的值就可以了。

*** 基本赋值

-  ~简单赋值 ( := )~ 编程语言中常规理解的赋值方式， _只对当前语句的变量有效_ 。

-  ~递归赋值 ( = )~  赋值语句可能影响多个变量，所有目标变量相关的其他变量都受影响。

-  ~条件赋值 ( ?= )~ 如果变量未定义，则使用符号中的值定义变量。如果该变量已经赋值，则该赋值语句无效。

-  ~追加赋值 ( += )~ 原变量用空格隔开的方式追加一个新值。

**** 简单赋值

#+BEGIN_SRC makefile
x:=foo
y:=$(x)b
x:=new
test：
      @echo "y=>$(y)"
      @echo "x=>$(x)"
#+END_SRC

#+BEGIN_SRC bash
# 执行 make test 我们会看到:
y=>foob
x=>new
#+END_SRC

**** 递归赋值

#+BEGIN_SRC bash
x=foo
y=$(x)b
x=new
test：
      @echo "y=>$(y)"
      @echo "x=>$(x)"
#+END_SRC

#+BEGIN_SRC bash
# 执行make test我们会看到:
y=>newb
x=>new
#+END_SRC

**** 条件赋值

#+BEGIN_SRC makefile
x:=foo
y:=$(x)b
x?=new
test：
      @echo "y=>$(y)"
      @echo "x=>$(x)"
#+END_SRC

#+BEGIN_SRC bash
# 执行make test 我们会看到:
y=>foob
x=>foo
#+END_SRC

**** 追加赋值

#+BEGIN_SRC makefile
x:=foo
y:=$(x)b
x+=$(y)
test：
      @echo "y=>$(y)"
      @echo "x=>$(x)"
#+END_SRC

#+BEGIN_SRC bash
# 在 shell 命令行执行make test我们会看到:
y=>foob
x=>foo foob
#+END_SRC


** 自动化变量

关于自动化变量可以理解为由 Makefile 自动产生的变量。在模式规则中，规则的目标和依赖的文件名代表了一类的文件。规则的命令是对所有这一类文件的描述。我们在 Makefile 中描述规则时，依赖文件和目标文件是变动的，显然在命令中不能出现具体的文件名称，否则模式规则将失去意义。

- ~$@~  表示规则的目标文件名。如果目标是一个文档文件（Linux 中，一般成 .a 文件为文档文件，也称为静态的库文件），那么它代表这个文档的文件名。在多目标模式规则中，它代表的是触发规则被执行的文件名。

- ~$%~  当目标文件是一个静态库文件时，代表静态库的一个成员名。

- ~$<~  规则的第一个依赖的文件名。如果是一个目标文件使用隐含的规则来重建，则它代表由隐含规则加入的第一个依赖文件。

- ~$?~  所有比目标文件更新的依赖文件列表，空格分隔。如果目标文件时静态库文件，代表的是库文件（.o 文件）。

- ~$^~  代表的是所有依赖文件列表，使用空格分隔。如果目标是静态库文件，它所代表的只能是所有的库成员（.o 文件）名。一个文件可重复的出现在目标的依赖中，变量“$^”只记录它的第一次引用的情况。就是说变量“$^”会去掉重复的依赖文件。

- ~$+~  类似“$^”，但是它保留了依赖文件中重复出现的文件。主要用在程序链接时库的交叉引用场合。

- ~$*~  在模式规则和静态模式规则中，代表“茎”。“茎”是目标模式中“%”所代表的部分（当文件名中存在目录时，“茎”也包含目录部分）。


#+CAPTION: 自动变量
#+NAME:   tab:basic-data
| 名称  | 描述           |
|-------+---------------------------------------------|
| $*   | 目标文件名没有文件扩展名。                   |


#+BEGIN_SRC makefile
all: hello.exe

hello.exe: hello.o
    gcc -o $@ $<
# 上面的 $< 指的是 hello.o $@是指 hello.exe

hello.o: hello.c
    gcc -c $<
#+END_SRC

*** D, F

GNU make 中在这些变量中加入字符 "D" 或者 "F" 就形成了一系列变种的自动化变量，这些自动化变量可以对文件的名称进行操作。

下面是一些详细的描述：


 $(@D)  表示文件的目录部分（不包括斜杠）。如果 "$@" 表示的是 "dir/foo.o" 那么 "$(@D)" 表示的值就是 "dir"。如果 "$@" 不存在斜杠（文件在当前目录下），其值就是 "."。
 $(@F)  表示的是文件除目录外的部分（实际的文件名）。如果 "$@" 表示的是 "dir/foo.o"，那么 "$@F" 表示的值为 "dir"。
 $(*D)  分别代表 "茎" 中的目录部分和文件名部分
 $(*F)
 $(%D)  当以 "archive(member)" 形式静态库为目标时，分别表示库文件成员 "member" 名中的目录部分和文件名部分。踏进对这种新型时
 $(%F)  的目标有效。
 $(<D)  表示第一个依赖文件的目录部分和文件名部分。
 $(<F)
 $(^D)  分别表示所有依赖文件的目录部分和文件部分。
 $(^F)
 $(+D)  分别表示所有的依赖文件的目录部分和文件部分。
 $(+F)
 $(?D)  分别表示更新的依赖文件的目录部分和文件名部分。
 $(?F)



** 模式匹配

模式匹配使用字符串 =%= 作为文件名。

#+BEGIN_SRC makefile
OBJS =  \
Test1.o \
Test2.o \
Main.o

REBUILDABLES = $(OBJS) $(LINK_TARGET)

clean :
  rm -f $(REBUILDABLES)
  echo Clean done

all : $(LINK_TARGET)
  echo All done

$(LINK_TARGET) : $(OBJS)
  g++ -g -o $@ $^

%.o : %.cpp
  g++ -g -o $@ -c $<

Main.o : Main.h Test1.h Test2.h
Test1.o : Test1.h Test2.h
Test2.o : Test2.h
#+END_SRC

** ref


https://devhints.io/makefile
