* builtin

builtin shell-builtin [arguments]

调用 ~shell-builtin~ 命令，并传 arguments

Execute the specified shell builtin, passing it arguments, and return its exit status.  This is useful when defining a function whose name is the same as a shell builtin, retaining the functionality of the builtin within the function.  The cd builtin is commonly redefined this  way. The return status is false if shell-builtin is not a shell builtin command.


*** There are three levels of built-in utilities:

**** Some utilities are really part of the shell as a programming language, even though they are not reserved words.

They are control flow utilities (., :, break, continue, return, trap, exit, exec, eval), parameter-related utilities (set, unset, shift, export, readonly, local¹, typeset¹), alias utilities (alias², unalias²) and times³. These special built-ins get special treatment:

1. If you pass the wrong arguments to a special built-in, the shell itself may abort, rather than just skipping to the next command after displaying an error message.

1. The pre-assignment syntax foo=bar utility has a different meaning: it's an ordinary parameter assignment (i.e. equivalent to foo=bar; utility), instead of assigning to the environment for the duration of the utility only.

**** Some utilities need to be implemented inside the shell because they act on the shell's internal settings.

This includes:

1. utilities that act on the shell's current directory such as cd, dirs, pushd, popd;

1. job control utilities such as bg, disown, fg, jobs, wait;

1. utilities that read or manipulate other shell attributes such as builtin, command, hash, read, type, ulimit, umask;

1. utilities related to interactive features, when they're present, such as fc, history, bind.

**** Some utilities are typically implemented as built-ins purely for performance: echo, printf, test, true, false


Advanced shells such as bash, ksh and zsh typically have more built-ins, often to implement non-standard features (usually for interaction). The manual of each shell will tell you what commands are built-in, though some shells (zsh, at least) support dynamically-loadable modules that can provide more built-ins.


** ref

https://unix.stackexchange.com/questions/11454/what-is-the-difference-between-a-builtin-command-and-one-that-is-not
