* grep



** 选项

*** -B, -A  前后若干行

#+BEGIN_SRC bash
#The -B 4 tells grep to also show the 4 lines before the match.
grep -B 4 'keyword' /path/to/file.log

#Alternatively, to show the log lines that match after the keyword, use the -A parameter.
grep -A 2 'keyword' /path/to/file.log
#+END_SRC

*** -h 省略文件名

hide

#+BEGIN_SRC bash
find ./ -type f | xargs grep -oh "http*.png"
#+END_SRC


*** -o --only-math

只拿到符合的字符串，而非整行，非常有用。

https://www.digitalocean.com/community/tutorials/using-grep-regular-expressions-to-search-for-text-patterns-in-linux

https://www.geeksforgeeks.org/regular-expression-grep/

GNU grep has the ~-P~ option for ~perl-style regexes~ , and the -o option to print only what matches the pattern. These can be combined using look-around assertions (described under Extended Patterns in the perlre manpage) to remove part of the grep pattern from what is determined to have matched for the purposes of -o.

#+BEGIN_SRC bash
$ grep -oP 'foobar \K\w+' test.txt
bash
happy
#+END_SRC

The ~\K~ is the short-form (and more efficient form) of (?<=pattern) which you use as a zero-width look-behind assertion before the text you want to output. (?=pattern) can be used as a zero-width look-ahead assertion after the text you want to output.

For instance, if you wanted to match the word between foo and bar, you could use:

#+BEGIN_SRC bash
$ grep -oP 'foo \K\w+(?= bar)' test.txt

# or (for symmetry)
$ grep -oP '(?<=foo )\w+(?= bar)' test.txt
#+END_SRC

*** -P perl格式的正则

** Demos

*** 空行

#+BEGIN_SRC bash
grep '^$' file
grep '^[[:space:]]*$' file # include white spaces
#+END_SRC

*** window 回车符

grep to find files that contain ^M (Windows carriage return)

#+BEGIN_SRC bash
grep  $'\r'
#+END_SRC
