* Kernel Locking Mechanisms

**  Atomic Operations on Integers

**  Spinlocks



**  Semaphores 信号量

内核使用的信号量定义如下。用户空间信号量的实现有所不同。

#+BEGIN_SRC C
// <asm-arch/semaphore.h>
struct semaphore {
  atomic_t count;
  int sleepers;
  wait_queue_head_t wait;
};
#+END_SRC

1. count指定了可以同时处于信号量保护的临界区中进程的数目。count == 1用于大多数情况（此类信号量又名互斥信号量，因为它们用于实现互斥）。

1. sleepers指定了等待允许进入临界区的进程的数目。不同于自旋锁，等待的进程会进入睡眠状态，直至信号量释放才会被唤醒。这意味着相关的CPU在同时可以执行其他任务。

1.  wait用于实现一个队列，保存所有在该信号量上睡眠的进程的task_struct（第14章讲述了相关的底层机制）

~Δ 与自旋锁相比较~

1. 与自旋锁相比，信号量适合于保护更长的临界区，以防止并行访问。

1. 但它们不应该用于保护较短的代码范围，因为竞争信号量时需要使进程睡眠和再次唤醒，代价很高。

~Δ DECLARE_MUTEX宏~

大多数情况下，不需要使用信号量的所有功能，只是将其用作 ~互斥量~ ，这不过是一种二值信号量。

为简化代码书写，内核提供了DECLARE_MUTEX宏，可以声明一个二值信号量，初始情况下未锁定，COUNT=1

#+BEGIN_SRC C
DECLARE_MUTEX(mutex)

// ...
down(&mutex);

/* 临界区 */
up(&mutex);
#+END_SRC

**  The Read-Copy-Update Mechanism

RCU（read-copy-update)是一个相当新的同步机制，在内核版本2.5开发期间被添加，并且非常顺利地被内核社区接纳。现在它的使用已经遍及内核各处。RCU的性能很好，不过对内存有一定的开销，但大多数情况下可以忽略。这是个好事情，但好事总伴随着一些不那么好的事情。下面是RCU对潜在使用者提出的一些约束）

~♠ RCU的原理~

1. 记录了指向共享数据结构的指针的所有使用者。

1. 在该结构将要改变时，则首先创建一个副本（或一个新的实例，填充适当的内容，这没什么差别），在副本中修改。

1. 在所有进行读访问的使用者结束对旧副本的读取之后，指针可以替换为指向新的、修改后副本的指针。请注意，这种机制允许读写并发进行！

~♠ RCU约束~

1. 对共享资源的访问在大部分时间应该是只读的，写访问应该相对很少。

1. 在RCU保护的代码范围内，内核 _不能_ 进入睡眠状态。

1. 受保护资源必须通过指针访问。

~♠ 受保护资源必须通过指针访问~

假定指针ptr指向一个被RCU保护的数据结构。

1. 直接反引用指针是禁止的，首先必须调用 rcu_read_lock和rcu_read_unlock调用保护起来

1. 被反引用的指针不能在rcu_read_lock()和rcu_read_unlock()保护的代码范围之外使用，也不能用于写访问

1. 如果必须修改ptr指向的对象，则需要使用rcu_assign_pointer：

#+BEGIN_SRC C
rcu_read_lock();

p = rcu_dereference(ptr);  // 反引用

if (p != NULL) {
  awesome_function(p);
}

rcu_read_unlock();
#+END_SRC

按RCU的术语，rcu_assign_pointer操作公布了这个指针，后续的读取操作将看到新的结构，而不是原来的。

#+BEGIN_SRC C
struct super_duper *new_ptr = kmalloc(...);
new_ptr->meaning = xyz;

new_ptr->of = 42;
new_ptr->life = 23;
rcu_assign_pointer(ptr, new_ptr);  //
#+END_SRC

如果更新可能来自内核中许多地方，那么必须使用普通的同步原语防止并发的写操作，如自旋锁。

~♠~ 尽管RCU能保护读访问不受写访问的干扰，但它不对写访问之间的相互干扰提供防护！

~♠ 在新值已经公布之后，旧的结构实例会怎么样呢？~

在所有的读访问完成之后，内核可以释放该内存，但它需要知道何时释放内存是安全的。为此，RCU提供了另外两个函数。

  1. ~synchronize_rcu()~ 等待所有现存的读访问完成。在该函数返回之后，释放与原指针关联的内存是安全的。

  1. ~call_rcu~ 可用于注册一个函数，在所有针对共享资源的读访问完成之后调用。这要求将一个rcu_head实例嵌入（不能通过指针）到RCU保护的数据结构：

#+BEGIN_SRC C
struct super_duper {
  struct rcu_head head;
  int meaning, of, life;
}
#+END_SRC

该回调函数可通过参数访问对象的rcu_head成员，进而使用container_of机制访问对象本身。
