* Threads

** src

#+BEGIN_SRC bash
- Ch11.Threads
  + include 符号链接
  + lib     符号链接
  + src
   Threads.org
#+END_SRC

- threadid.c 新建线程

- exitstatus.c 退出

** Introduction

** Thread Concepts

- pthread_t        线程ID类型

- pthread_mutex_t  互斥对象

- pthread_mutexattr_t

- pthread_cond_t   条件变量

- pthread_condattr_t

- pthread_key_t    线程特有数据的健(key)

- pthread_once_t   一次性初始化控制上下文

- pthread_attr_t   线程的属性对象

** Thread Identification

** Thread Creation

** Thread Termination

*** 程序清单

**** 程序清单11-4 exitstatus.c

演示了退出的基本用法。

**** 程序清单11-3 badexit.c

不能使用 exit 线程的函数局部变量

#+BEGIN_SRC cpp
void * thr_fn1(void *arg)
{
  struct foo	foo = {1, 2, 3, 4};

  printfoo("thread 1:\n", &foo);
  pthread_exit((void *)&foo);
}
#+END_SRC

**** 程序清单11-4 cleanup.c

pthread_cleanup_push & pthread_cleanup_pop

*** exit


1. 线程调用了 ~exit~, ~_Exit~ 或者 ~_exit~

1. 假定信号默认动作为终止进程，那么发送信号给线程也会终止线程


*** pthread_join

1. 函数 ~pthread_join~ 等待由 thread 标识的线程终止，如果线程已经终止，它就会立即返回，这种操作称之为“连接”

1. 调用 ~pthread_join~ 的线程将一直阻塞，直到指定线程调用了 ~pthread_exit~

1. ~pthread_join~ 可以获取线程的状态

1. ~pthread_join~ 已经结束的线程，也是有意义的——可以获取 ~线程的退出状态~ —— 即，如果是可join的，那么一定为这个线程分配了资源（如何实现暂时不讨论），而detached 时能够自动清理、并移除。

~pthread_join~ 与针对线程的 ~waitpid~ 相似，但也有一些差异：

1. 线程只在当前进程中有效，因而无法对任意线程连接。

1. 多个线程的关系是类似的，而

The pthread_join() function shall suspend execution of the calling thread until the target thread terminates, unless the target thread has already terminated.

为什么叫join？想像线程是一根线，join的意思就是将两根线接成一根线，当然是前一个执行后，才执行到现在这个。

*** 主线程 return, exit 退出后，整个process 也退出

When the main thread ~returns~ (i.e., you return from the main function), it terminates the entire process. This includes all other threads. The same thing happens when you call exit.

You can avoid this by calling ~pthread_exit~.

The purpose of pthread_detach is to make it so you don't need to join with other threads in order to release their resources. Detaching a thread does not make it exist past process termination, it will still be destroyed along with all the other threads.

https://stackoverflow.com/questions/11875956/when-the-main-thread-exits-do-other-threads-also-exit

leo 按：编译中 return 0 或者 exit 必然调用了系统调用的exit，退出了整个进程。

本质上关键不在于是否是主线程，而在于，是否调用了系统调用 exit

*** detach

~pthread_detached~ 就希望在线程结束后，自动清理、并移除。

detach有“分离、卸下”的含义。

一量线程处于分离状态，就不能再使用 pthread_join 来获取其状态，也无法使其重返“可链接”状态（因为资源已经释放了）。

*** pthread_cancel

可以调用 pthread_cancel 来取消其他线程

*** pthread_cleanup_push 为线程退出时添加方法， pthread_cleanup_pop用来删除它


** Thread Synchronization 线程同步

*** 本节程序清单

**** 程序清单11-5 mutex1.c

演示了基本的 pthread_mutex_init, pthread_mutex_lock, pthread_mutex_unlock 方法

**** 程序清单11-6 mutex2.c

演示了多个互斥量时，总要以相同顺序加锁，以防死锁

- foo_find 找到元素

- foo_rele 释放元素的hash引用（没有实现free元素，应该是这个操作后要进行的）

- foo_find 根据id找到元素

多个线程修改数据，引发不一致。

*** mutex 互斥量

pthread_mutex_t

*** 避免死锁

- 对互斥量加锁两次，会坠入死锁状态

- 两个互斥量mutexA与mutexB，线程T1, T2。T1占用了MutexA，尝试获得mutexB，而T2获得了mutexB，正尝试获取mutexA

**** 第二种情况的解决方法

控制互斥量加锁顺序。

第二种情况都是由于互斥量获取顺序不同引起的。

*** 读写锁

适用场景：对数据结构读的次数远大于写

它有3种状态

- 不加锁状态

- 写模式加锁状态：所有试图对这个锁加锁的线程都会被阻塞。

- 读模式加锁状态：

  1. 所有试图以读模式对它进行加锁的线程都可以得到访问权，但如果线程希望以写模式对此锁进行加锁，它必须阻塞，直到其他线程都释放了读锁

  1. 但上一种情况可能会造成写线程饿死，一些实现中，如何处于读模式锁住状态时，有新的线程试图拿到写模式锁，读写锁会阻塞后面的请求读模式锁请求。

更多请参考： [[./rwlock.org]] 展示了读写锁的实现方法

*** 条件变量




** Summary
