** Unix v6 基本配置

参见 [如何在simh中安装 unixv6 操作系统](http://www.gunkies.org/wiki/Installing_Unix_v6_(PDP-11)_on_SIMH)

### 系统的安装

```
$ pdp11
PDP-11 simulator V3.8-1
sim> set cpu 11/40
Disabling XQ
sim> set tm0 locked
sim> attach tm0 dist.tap
sim> attach rk0 rk0
RK: creating new file
sim> attach rk1 rk1
RK: creating new file
sim> attach rk2 rk2
RK: creating new file
sim> d cpu 100000 012700
sim> d cpu 100002 172526
sim> d cpu 100004 010040
sim> d cpu 100006 012740
sim> d cpu 100010 060003
sim> d cpu 100012 000777
sim> g 100000
# <Ctrl> E  here
Simulation stopped, PC: 100012 (BR 100012)
sim> g 0
=tmrk
disk offset
0
tape offset
100
count
1
=tmrk
disk offset
1
tape offset
101
count
3999
=
Simulation stopped, PC: 137274 (TSTB @#177560)
sim> q
Goodbye
$ ~/v6$ ll # 进程文件查看 rk0
total 8160
drwxr-xr-x  3 leo user    4096 Nov 18 18:37 ./
drwxr-xr-x 56 leo user    4096 Nov 18 12:50 ../
-rw-r--r--  1 leo user 6291996 Nov 18 13:52 dist.tap
-rw-r--r--  1 leo user 2048000 Nov 18 18:39 rk0
-rw-r--r--  1 leo user       0 Nov 18 18:37 rk1
-rw-r--r--  1 leo user       0 Nov 18 18:37 rk2
```




执行下一命令,让终端以小写字母进行显示

```
# STTY -LCASE
```

### 重新构建内核

我们必须去重新构建内核,以使它适应SIMH所提供的硬件, 第一步就是我们必须生成 mkconf这一个程序

```
chdir /usr/sys/conf
cc mkconf.c
mv a.out mkconf
```

### 正常启动 start normally


```
set cpu 11/40
set cpu idle
set tto 7b
set tm0 locked
attach rk0 rk0
attach rk1 rk1
attach rk2 rk2
attach lpt printer.txt
set dci en
set dci lines=8
set dco 7b
att dci 5555
boot rk0
PDP-11 simulator V3.8-1
Disabling XQ
Listening on port 5555 (socket 108)
@unix
login: root  // 以root身份登陆
```

## Unix v6 分析

### 存储管理

#### 核心态下,进程的虚拟地址空间

核心态中`0-5`页存放的是`unix`操作系统的代码,不同系统配置的unix代码的长度是不相同的,`PDP-11/40`这一机型,代码长度不能超过`48KB`,如果小于这个长度,那么一些虚拟空间就弃而不用.这里装载的是内核程序

最后一页是*输入,输出页*,实际上就是对应的最高地址上的`8KB`空间.

只有第6页是非常特殊的,它对应的是当前进程的ppda区,实际长度是1024字节,它随着进程的变化而变化.

```
-----------------------------------------
| 0         |                           |
| 1         |                           |
| 2         |  这六页存放 unix 内核代码      |
| 3         |                           |
| 4         |                           |
| 5         |                           |
-----------------------------------------
| 6         | 当前进程的PPDA               |
-----------------------------------------
| 7         | 输入,输出页                  |
-----------------------------------------
```

`ppda` is `Pre Process Data Area` 有以下特性

1. 由`user`结构体和内核栈区域构成
1. 上面讲的内核栈区域,是内核处理这一进程时的临时工作区域,每个进程都有供内核使用的工作区域
1. 这个区域是用户空间无法访问的,它的长度为USIZE * 64字节,即 1KB


#### 用户态下,进程的虚拟地址空间

用户态下,进程的虚拟地址空间的分布没有核心态下那么泾渭分明,它在逻辑上可以分为三段,顺序上也是下面这样:

1. 共享正文段
1. 数据段
1. 栈段

每段都必须占用整数页,比如正文段实际使用长度为2.5页,那么就必须使用3页


#### 内存中进程图像的分布


虚拟地址空间上述的分配规则不能照搬到物理内存当中去.具体参见**unix 操作系统教程**中的第96页

** unix 代码段是从地址0开始的低地址区

** `ppda`,数据段,栈段三者在物理空间中是紧靠在一起的.

** 共享正文段是多个进程共享的


### 进程管理


#### proc结构体

`/root/usr/sys/proc.h`下代码

```
struct	proc
{
    char	p_stat;
    char	p_flag;
    char	p_pri;		/* priority, negative is high */
    char	p_sig;		/* signal number sent to this process */
    char	p_uid;		/* user id, used to direct tty signals */
    char	p_time;		/* resident time for scheduling */
    char	p_cpu;		/* cpu usage for scheduling */
    char	p_nice;		/* nice for scheduling */
    int	p_ttyp;		/* controlling tty */
    int	p_pid;		/* unique process id */
    int	p_ppid;		/* process id of parent */
    int	p_addr;		/* address of swappable image */
    int	p_size;		/* size of swappable image (*64 bytes) */
    int	p_wchan;	/* event process is awaiting */
    int	*p_textp;	/* pointer to text structure */
} proc[NPROC];
/* stat codes */
#define	SSLEEP	1		/* sleeping on high priority */
#define	SWAIT	2		/* sleeping on low priority */
#define	SRUN	3		/* running */
#define	SIDL	4		/* intermediate state in process creation */
#define	SZOMB	5		/* intermediate state in process termination */
#define	SSTOP	6		/* process being traced */
/* flag codes */
#define	SLOAD	01		/* in core */
#define	SSYS	02		/* scheduling process */
#define	SLOCK	04		/* process cannot be swapped */
#define	SSWAP	010		/* process is being swapped out */
#define	STRC	020		/* process is being traced */
#define	SWTED	040		/* another tracing flag */
```

`proc.h`中元素的含义


| member | desc                                                          |
| ------ | ------------------------------------------------------------- |
| p_stat | 状态.等于NULL意味着proc[]数组中这个元素为空,也就是没有这个进程              |
| p_flag | 标志变量.                                                       |
| p_pri  | 执行优先级.                                                      |
| p_sig  | 信号                                                           |
| p_uid  | user id                                                       |
| p_time | 在内存中或交换空间中存在的时间                                         |
| p_cpu | 占用CPU的累计时间                                                   |
| p_nice | 用来降低执行优先级的补正系数                                           |
| p_ttyp | 正在操作进程的终端                                                  |
| p_pid | 进程ID                                                          |
| p_ppid | 父进程ID                                                          |
| p_addr | 数据段的物理地址 (单位为64字节)                                        |
| p_size | 数据段的长度 (单位为64字节)                                           |
| p_wchan | 使进程进入休眠状态的原因                                             |
| *p_textp | 使用的代码段                                                     |


在`/root/usr/sys/param.h`中定义了一个最大进程数量,就是说不可能创建`50`个以上的进程

```
#define	NPROC	50		/* max number of processes */
```


#### 进程状态概述

进程有以下状态,即 `proc` 中 `p_statu`

- SRUN 运行状态

- SSLEEEP 高优先权的睡眠状态

- SWAIT 低优先权的睡眼状态

- SSTOP 暂停状态,等待被跟踪(trace)

- SZOMB 等待善后的处理状态

- SIDL 创建子进程的状态




#### user.h


```
struct user
{
    int	u_rsav[2];		/* save r5,r6 when exchanging stacks */
    int	u_fsav[25];		/* save fp registers */
                                                                    /* rsav and fsav must be first in structure */
    char	u_segflg;		/* flag for IO; user or kernel space */
    char	u_error;		/* return error code */
    char	u_uid;			/* effective user id */
    char	u_gid;			/* effective group id */
    char	u_ruid;			/* real user id */
    char	u_rgid;			/* real group id */
    int	u_procp;		/* pointer to proc structure */
    char	*u_base;		/* base address for IO */
    char	*u_count;		/* bytes remaining for IO */
    char	*u_offset[2];		/* offset in file for IO */
    int	*u_cdir;		/* pointer to inode of current directory */
    char	u_dbuf[DIRSIZ];		/* current pathname component */
    char	*u_dirp;		/* current pointer to inode */
    struct	{			/* current directory entry */
                    int	u_ino;
                    char	u_name[DIRSIZ];
    } u_dent;
    int	*u_pdir;		/* inode of parent directory of dirp */
    int	u_uisa[16];		/* prototype of segmentation addresses */
    int	u_uisd[16];		/* prototype of segmentation descriptors */
    int	u_ofile[NOFILE];	/* pointers to file structures of open files */
    int	u_arg[5];		/* arguments to current system call */
    int	u_tsize;		/* text size (*64) */
    int	u_dsize;		/* data size (*64) */
    int	u_ssize;		/* stack size (*64) */
    int	u_sep;			/* flag for I and D separation */
    int	u_qsav[2];		/* label variable for quits and interrupts */
    int	u_ssav[2];		/* label variable for swapping */
    int	u_signal[NSIG];		/* disposition of signals */
    int	u_utime;		/* this process user time */
    int	u_stime;		/* this process system time */
    int	u_cutime[2];		/* sum of childs' utimes */
    int	u_cstime[2];		/* sum of childs' stimes */
    int	*u_ar0;			/* address of users saved R0 */
    int	u_prof[4];		/* profile arguments */
    char	u_intflg;		/* catch intr from sys */
                                                                    /* kernel stack per user
                                                                     * extends from u + USIZE*64
                                                                     * backward not to reach here
                                                                     */
} u;
```


| member      | desc                                                      |
| ----------- | --------------------------------------------------------- |
| u_rsav[]    | 用来保存 r5, r6 当前值,即记录环境指针,栈指针                       |
| u_fsav[]    | pdp-11/40 不使用这一属性                                     |
| u_segflg    | 读写文件时,使用的标志变量                                       |
| u_procp     | user结构体对应的数据proc[]中的表示这一进程的元素,这是一个指针类型 |

系统中的一个全局变量 u,因为所以汇编程序(以`.s`结尾)中的数据都是八进制

```
.globl	_u
_u	= 140000
```

下面我们看一下计算,我们回复一下前面讲到的存储管理,去想一想内核态的第六页存的是什么数据?

```
_u = 014000 // 49152
49152 / (1024 * 8)  // 值为6, 就是说user.h这个结构永远是内核态读取第六页时得到的
```

是当前进程的`ppda`区


#### 进程标志概述

进程标准有以下状态

- SLOAD 进程图像在内存当中

- SSYS 系统进程,不会被交换至交换空间,在UNIX V6中只有proc[0]是系统进程

- SLOCK 进程调度锁,不允许进程被换出至交换空间

- SSWAP 进程图像已经被换出至交换空间,由于被换出至交换空间, user.u_rsav[]的值不再有效,必须从user.ussav[]中恢复r5,r6的值

- STRC 处理被跟踪的状态

- SWTED 在被跟踪时使用


#### 进程状态分析


可以概括为三种状态

1. 运行状态
1. 睡眠状态
1. 其他状态


##### 运行状态

###### 1, 运行状态 ---- 现运行状态和执行状态

处理器上当前时间内运行的进程,它有以下特性:

1. p_stat 为 SRUN
1. p_flag 为 SLOAD
1. 核心态内存管理寄存器 KISA6, KISD6指向这一进程的`ppda`区.
1. 用户态的内存管理寄存器 UISA0 ~ UISA7, UISD0 ~ UISD7指向这一进程的用户态图像占用的内存区
1. 这个进程如果是核心态运行的话,就在核心态存储区活动,执行系统的代码.如果是用户态,就执行的是用户程序或系统提供的其他类非内核程序

###### 2, 运行状态 ---- 就绪状态

这种进程就是在等待处理器的占用,所以称为就绪状态

1. p_stat 为 SRUN
1. p_flag 可能是 SLOAD,也可能不是,这个状态下,不能保证进程图像一定在内存中,也可能是在交换空间当中
1. 即使它的进程图像在内存中,但mmu中的数据与这一进程不相关

##### 睡眼状态

###### 睡眼状态 ---- 进入睡眠状态的特点

1. p_stat 为 `SSLEEP` 或 `SWAIT`
1. p_flag 可能是 SLOAD,也可能不是,这个状态下,不能保证进程图像一定在内存中,也可能是在交换空间当中

###### 睡眼状态 ---- 进入睡眠状态的原因

1. 资源使用互斥

1. 同步等待输出/输出操作的结束

1. 同步等待出现处理对象

1. 进程间的其他同步

1. 临界区互斥



#### fork的实现

下面是 C 标准库中的fork()

```
.globl	_fork, cerror, _par_uid

_fork:                   // 提供给C标准库的,因为是汇编程序,所以以_开头
        mov	r5,-(sp)     // 保存 环境指令到栈顶,因为栈是由高位向低位走的,所以是先执行-1
        mov	sp,r5        // 将新的sp给r5
        sys	fork         // 系统调用
                br 1f    //
        bec	2f           //
        jmp	cerror
1:
        mov	r0,_par_uid
        clr	r0
2:
        mov	(sp)+,r5
        rts	pc
.bss
_par_uid: .=.+2
```


`/root/usr/sys/ken/sys1.c` 下面是系统调用时用到的`fork`方法

```
fork()
{
        register struct proc *p1, *p2;

        p1 = u.u_procp;                    //u_procp是0 ~ 49,代表的是全局变量u的第几个元素
        for(p2 = &proc[0]; p2 < &proc[NPROC]; p2++)
                if(p2->p_stat == NULL)     // 找到未被使用的进程空间
                        goto found;
        u.u_error = EAGAIN;                // 无法新建进程
        goto out;

found:
        if(newproc()) {
                u.u_ar0[R0] = p1->p_pid;   这一
                u.u_cstime[0] = 0;        // 子进程在内核模式下占用的cpu时间(时针tick数)
                u.u_cstime[1] = 0;
                u.u_stime = 0;            // 进程在内核模式下占用的cpu时间(时针tick数)
                u.u_cutime[0] = 0;        // 子进程在用户模式下占用的cpu时间(时针tick数)
                u.u_cutime[1] = 0;
                u.u_utime = 0;
                return;
        }
        u.u_ar0[R0] = p2->p_pid;

out:
        u.u_ar0[R7] =+ 2;
}
```

`/root/usr/sys/ken/slp.c` 中的`newproc()`方法


```
newproc()
{
        int a1, a2;
        struct proc *p, *up;
        register struct proc *rpp;
        register *rip, n;

        p = NULL;
        /*
         * First, just locate a slot for a process
         * and copy the useful info from this process into it.
         * The panic "cannot happen" because fork has already
         * checked for the existence of a slot.
         */
retry:
        mpid++;
        if(mpid < 0) {
                mpid = 0;
                goto retry;
        }
        for(rpp = &proc[0]; rpp < &proc[NPROC]; rpp++) {
                if(rpp->p_stat == NULL && p==NULL)
                        p = rpp;
                if (rpp->p_pid==mpid)
                        goto retry;
        }
        if ((rpp = p)==NULL)
                panic("no procs");   // 无法分配新进程
        /*
         * make proc entry for new proc
         */
        rip = u.u_procp;    // u是当前的进程的user结构体,它的u_procp指向的是当前进程
        up = rip;
        rpp->p_stat = SRUN;  // rpp 是新进程
        rpp->p_flag = SLOAD;
        rpp->p_uid = rip->p_uid;     // p_uid 是用户ID
        rpp->p_ttyp = rip->p_ttyp;   // p_ttyp 是运行的终端 TTY
        rpp->p_nice = rip->p_nice;   // p_nice 用来降低执行优先级的补正系数
        rpp->p_textp = rip->p_textp; // 指向代码段
        rpp->p_pid = mpid;           // 新进程的id
        rpp->p_ppid = rip->p_pid;    // 新进程的父id
        rpp->p_time = 0;             // 执行时间

        /*
         * make duplicate entries
         * where needed
         */

        for(rip = &u.u_ofile[0]; rip < &u.u_ofile[NOFILE];)   //
                if((rpp = *rip++) != NULL)
                        rpp->f_count++;
        if((rpp=up->p_textp) != NULL) {
                rpp->x_count++;
                rpp->x_ccount++;
        }
        u.u_cdir->i_count++;
        /*
         * Partially simulate the environment
         * of the new process so that when it is actually
         * created (by copying) it will look right.
         */
        savu(u.u_rsav);
        rpp = p;
        u.u_procp = rpp;
        rip = up;
        n = rip->p_size;
        a1 = rip->p_addr;
        rpp->p_size = n;
        a2 = malloc(coremap, n);
        /*
         * If there is not enough core for the
         * new process, swap out the current process to generate the
         * copy.
         */
        if(a2 == NULL) {
                rip->p_stat = SIDL;
                rpp->p_addr = a1;
                savu(u.u_ssav);
                xswap(rpp, 0, 0);
                rpp->p_flag =| SSWAP;
                rip->p_stat = SRUN;
        } else {
        /*
         * There is core, so just copy.
         */
                rpp->p_addr = a2;
                while(n--)
                        copyseg(a1++, a2++);
        }
        u.u_procp = rip;
        return(0);
}
```

`/root/usrsys/system.h` mpid 是用于分成进程序列号的一个数字,也是一个系统全局变量


```
int	mpid;			/* generic for unique process id's */
```

mpid是一个一直在增长的数,它不一定要小于50,实现上可以是最大的int,进程的pid不一定是0~50之个范围之内,因为这样增长,更利于执行效率

`u_error` 用于定义系统错误的

```
/* u_error codes */
#define	EFAULT	106
#define	EPERM	1
#define	ENOENT	2
#define	ESRCH	3
#define	EINTR	4
#define	EIO	5
#define	ENXIO	6
#define	E2BIG	7
#define	ENOEXEC	8
#define	EBADF	9
#define	ECHILD	10
#define	EAGAIN	11
#define	ENOMEM	12
#define	EACCES	13
#define	ENOTBLK	15
#define	EBUSY	16
#define	EEXIST	17
#define	EXDEV	18
#define	ENODEV	19
#define	ENOTDIR	20
#define	EISDIR	21
#define	EINVAL	22
#define	ENFILE	23
#define	EMFILE	24
#define	ENOTTY	25
#define	ETXTBSY	26
#define	EFBIG	27
#define	ENOSPC	28
#define	ESPIPE	29
#define	EROFS	30
#define	EMLINK	31
#define	EPIPE	32
```

| 名称    | 描述                                                     |
| ------ | ------------------------------------------------------- |
| EFAULT | 在用户态和内核态之间传递数据失败                                 |
| EPERM  | 当前用户不是超级用户                                          |


#### panic

`UNIX`没有将自己定义为一个具备"容错","个别部件发生故障时仍能工作"等特性的系统,但一些情况下,通过调用"painc()"可以解决一定的问题,在某些情况下,调用这一方法行之有效.

什么情况下会使用到这一方法呢?

- 资源匮乏时,导致内核处理无法继续进行.

它的工作原理,是不停地调用`idle()`以阻止程序继续进行,同时,idle()将处理器优先级设为0,这样它就可以响应所有优先级的中断

```
/*
 * prdev prints a warning message of the
 * form "mesg on dev x/y".
 * x and y are the major and minor parts of
 * the device argument.
 */
panic(s)
char *s;
{
    panicstr = s;
    update();
    printf("panic: %s\n", s);
    for(;;)
        idle();
}
```


## Unix v6 manuals unix v6用户手册

### Unix v6 基本命令

参见本文档中的[unixv6_commands.md](./unixv6_commands.md)


### Unix v6 系统调用


## ASM  汇编指令


对于单操作数指令,其操作数通常称为“目的操作数”;在双操作数指令中,两个操作数分别被称为“源操作数”和“目的操作数”

### 一些汇编指令及其说明

参见本文档中的[pdp11_asm.md](./pdp11_asm.md).

## Simh


## 术语索引

### A

- APR

`APR` 是`active page register` 它由一个`PAR`和一个`PDR`组成, `PAR`有16位,`PDR`也是16位, PDP--11/40 只使用`PAR`的中低12位,这12位被称为页地址字段(`PAF` is `page address field`),它说明的是虚拟地址中相应的页对应的物理地址空间中的起始地址,

### K

- KISA

`KISA` 核心态下的`PAR`

- KISD

`KISD` 核心态下的`PDR`

### M

`MMU` is `Memory Management Unit` 内存控制单元

`MSB` is "Most Significant bit"最重要的一位。一般指符号位。

### P

- PAF

`PAF`见 APR

- PAR

`PAR`见 APR

- PCB

`PCB` is `process control block`进程控制块,也叫做`process descriptor`

- PDR

`PDR`见 APR

- PPDA

`pre process data area`

- PS

`PS`寄存器

```
mov PS, -(sp) 向栈顶存放了PSW
```

- PSW

`PSW` is `processor status word`是处理器状态字,`PSD`是一个被称为处理器状态字的16位寄存器，Processor Status Word PSW (at 0777776)

下面的描述出自于 **unix内核源码剖析**

|  比特位    |              含义                                               |
| --------- | ---------------------------------------------------------------|
|   15-14   | 处理器当前模式, 00为内核模式, 11为用户模式,永远不出现01或10的情况           |
|   13-12   | 处理器先前模式, 00为内核模式, 11为用户模式,永远不出出现01或10的情况           |
|   7-5     | 处理器优先级, 因为是3位，所以优先级是0-7                                                     |
|   4       | trap位                                                        |
|   3       | N 负位                                                        |
|   2       | Z 零位                                                        |
|   1       | V 溢出位                                                       |
|   0       | C 借位                                                        |





下面的描述出自于 **unix manual**

| name  |  width |  meaning                                            |
| ----- | ------ | --------------------------------------------------- |
| CM    | 2      | current operation mode, 00 is kernel mode, 11 user mode |
| PM    | 2      | previous operation mode                             |
| **    | 4      | not used                                            |
| IPL   | 3      | interrupt priority level                            |
| T     | 1      | enable trace trap                                   |
| NZVC  | 4      | condition codes                                     |


###

### U

- UISA

`UISA` 用户态下的`PAR`

- UISD

`UISD` 用户态下的`PDR`


## 重要工具
