* 中断与陷入

** 概念

中断是主存、I/O 设备等外部设备向 CPU 发起的事件通知信号。该信号通知 CPU 某外设 需要获取总线(Bus Request)，进行特定任务的处理。该任务包括如下两种:

  - 实现一个没有 CPU 参与的数据传送。比如 DMA 数据传输。一个例子是:磁盘数据直接传送至 =CRT= 显示器，从而实现屏幕的刷新。

  - 打断当前程序的执行，强制 CPU 实现某个服务请求。

** DMA

直接内存访问（Direct Memory Access，DMA）是计算机科学中的一种内存访问技术。它允许某些电脑内部的硬件子系统（电脑外设），可以独立地直接读写系统内存，而不需中央处理器（CPU）介入处理 。在同等程度的处理器负担下，DMA是一种快速的数据传送方式。很多硬件的系统会使用DMA，包含硬盘控制器、绘图显卡、网卡和声卡。


** 中断优先级

unix只实现了 4 ~ 7 级中断

#+CAPTION: 中断与陷入
#+NAME:   tab:basic-data
| 中断(自陷)产生源           | 类别(中断/自陷)   | 优先级  | 中断向量地址(10 进制)   |
|--------------------------+-----------------+--------+-----------------------|
| 线性时钟(Line Clock)      | 中断            |      6 |                   100  |
| 实时时钟(Realtime Clock)  | 中断            |      6 |                   104  |
| 磁盘                     | 中断             |      5 |                   220 |
| KL-11/DL-11              | 中断            |      4 |                    60 |
| PC-11                    | 中断            |      4 |                    70 |
| LP-11                    | 中断            |      4 |                   200 |
| 总线错误(bus error)       | 自陷            |      7 |                     4 |
| 非法指令                  | 自陷            |      7 |                     8 |
| 断点                     | 自陷            |      7 |                    12 |
| I/O 自陷                 | 自陷            |      7 |                    16 |
| 供电异常                  | 自陷            |      7 |                    20 |
| 仿真器                   | 自陷            |      7 |                    24  |
| 系统调用                  | 自陷            |      7 |                    28 |
| 奇偶错                   | 自陷             |      7 |                   114 |
| 程序中断                 | 自陷             |      7 |                   240 |
| 浮点运算异常              | 自陷            |      7 |                   244 |
| 段违例                   | 自陷            |      7 |                   248 |


=PSW= 指 =processor status word= 是处理器状态字, =PSD= 是一个被称为处理器状态字的16位寄存器，Processor Status Word PSW 在内核地址最高处 0777776

#+CAPTION: PSW 处理器状态字各字段的含义
#+NAME:   tab:basic-data
|  比特位    |              含义                                               |
| --------- | ---------------------------------------------------------------|
|   15-14   | 处理器当前模式, 00为内核模式, 11为用户模式,永远不出现01或10的情况           |
|   13-12   | 处理器先前模式, 00为内核模式, 11为用户模式,永远不出出现01或10的情况           |
|   11-8    | 保留位                                                       |
|   7-5     | 处理器优先级, 因为是3位，所以优先级是0-7                          |
|   4       | trap位                                                        |
|   3       | N 负位                                                        |
|   2       | Z 零位                                                        |
|   1       | V 溢出位                                                       |
|   0       | C 借位                                                        |



** 重要概念

*** 陷入更为重要

  - 陷入是由 =CPU内部的事件引起的= ,即psw[4]被设置了。

  - 用户触发的陷入最终被作为 =信号= 来处理。一道用户程序可以执行一条 =trap= 以故障的形式造成一次中断，借此来获取操作系统的注意和帮助。

  - 用户进程切换到内核进程都是通过陷入处理的。

** 硬件中断

中断的作用是：让CPU从当前所执行的指令序列转移到另一道程序。

过程如下：

  1. 外部设备通过所连接的 =中断请求线= 向 =CPU= 发送信号来请求获得数据总线。(中断请求线是外部设备连接在CPU上的)

  1. =CPU= 接收到该信号后，和当前 =PSW= 寄存器的中断屏蔽优先级相比较，如果高于中断屏蔽优先级，则接受该请求，否则忽略。

  1. 一旦 CPU 接受该请求，则外部设备获得总线，并通过总线向 CPU 发送中断命令和唯一的中断向量地址 （理论上就是要把中断向量地址传过去，其他不传送任何地址了）。中断向量地址是指向内核虚存中的一个地址，它的第一个字是中断服务函数地址，第二个字是新的 PSW 值，中断向量的指向如图 6-2 所示。

#+BEGIN_COMMENT
# 错误认识
  - 这里学习时有个认识错误，认为新的PSW也是外部设备传寄的，因为我以为鼠标、键盘这类设备都会传送具体的数据，这些是错误的，外部中断只传递中断向量地址， unixv6可能是通过MAPPED IO读取具体的数据的。



#+END_COMMENT

  1. CPU 把当前的 PC 和 PSW 值存放到临时寄存器中。

  1. CPU 读出中断向量中的中断服务函数地址，作为新的 =PC= 值，读出新的 =PSW= 值， 把老的 =PC= 和 =PSW= 值存放在新的 =PSW= 中指示的当前模式所对应的栈上，比如，如果新的 =PSW= 位 15-14 等于 00，指示是内核模式，则老的 =PC= 和 PSW 值被存放到内核栈上; =CPU= 再把老的当前模式(老 PSW 的位 15-14)存放到新 PSW 的位 13-12 中，这样，新 的 PSW 就设定完毕。然后指令跳转到新的 PC 值，也就是中断服务函数中运行，中断向 量含义图如图 6-3 所示。


当中断服务函数返回时(rti)，按照和上面相反的顺序处理:

  1. =CPU= 从栈中读出老的 =PC= 和 =PSW= 值，放置在 =PC= 和 =PSW= 寄存器中;

  1. =CPU= 根据 =PSW= 位 15、14 所指示的当前模式，跳转到相应空间的 =PC= 地址处执行。 中断是可以被打断的。在中断执行过程中，如果新产生了一个中断，并且它的优先级高于当前 =PSW= 所指示的中断屏蔽优先级，那么当前执行的中断就会被打断， =CPU= 跳转到新的中断服务函数中运行，在该服务函数返回后，再继续打断当前的中断执行。这种情形又叫做“中断嵌套”。UNIX 允许中断嵌套处理，但是对嵌套的中断处理过程加以一定的限制。





下面看这段程序

br 代表的是 =bus request= 。


这些向量在系统启动时被设置，可以参见 =mkconf.c= 文件

发现这里出现了一个理解的问题，其实没有中断对应的汇编指令，因为中断是外部设备引起的。只有trap指令，trap本身就相当于最高优先级，它只关心向量就行。

全局函数 =spln= 用于设置优先级
#+BEGIN_SRC C
.globl	_spl0, _spl1, _spl4, _spl5, _spl6, _spl7
#+END_SRC


#+BEGIN_SRC asm
// mkconf.c文件
/ low core

br4 = 200
br5 = 240                            / 二进制 10100000
br6 = 300                            / 二进制 11000000
br7 = 340                            / 二进制 11100000  第5-7位是处理器优先级

. = 0^.                              / 当读入内存时，此处的地址为0 这里使用的是八进制
     br       1f

 / trap vectors
    trap; br7+0.                        / bus error  向量004 总结超时
                                        /Br7+0放入到psw之中, 这里的`trap`是处理函数地址，不是什么汇编指令，因为是中断向量，它代表的是pc指向trap那个标号 看上面的表，这个向量是 004 是因为前面已经有一个指令`br 1f`了  本质上是加 4
    trap; br7+1.                        / illegal instruction 向量010 指令错误
    trap; br7+2.                        / bpt-trace trap 向量014 断点跟踪
    trap; br7+3.                        / iot trap  向量014 输入输出陷 IO trap
    trap; br7+4.                        / power fail 电源异常
    trap; br7+5.                        / emulator trap 模拟陷入指令
    trap; br7+6.                        / system entry  sys 指令

 . = 40^.
 .globl  start, dump
 1: jmp     start       /
    jmp     dump        /

 . = 60^.
    klin; br4
    klou; br4

 . = 70^.
    pcin; br4
    pcou; br4

 . = 100^.
    kwlp; br6           / 电源频率时钟
    kwlp; br6           / 可编程时钟

 . = 114^.
    trap; br7+7./ 11/70 parity

 . = 200^.
    lpou; br4           / 行打印机时钟

 . = 220^.
    rkio; br5           / 块设备RK-11

 . = 240^.
    trap; br7+7./ programmed interrupt        //
    trap; br7+8./ floating point              // 浮点小数点错误
    trap; br7+9./ segmentation violation      // 段错误

//////////////////////////////////////////////////////
// interface code to C 中断处理函数一些标号
//////////////////////////////////////////////////////
.globl call, trap

.globl _klrint
klin: jsr r0,call; _klrint
.globl _klxint
klou: jsr r0,call; _klxint

.globl _clock
kwlp: jsr r0,call; _clock

.globl _tcintr
tcio: jsr r0,call; _tcintr

.globl _tmintr
tmio: jsr r0,call; _tmintr

.globl _hpintr
hpio: jsr r0,call; _hpintr
#+END_SRC


#+BEGIN_COMMENT
学习时遇到的困惑:
下面一段代码在学习时遇到困难。
#+BEGIN_SRC asm
 .globl    _clock
 kwlp:     jsr     r0,call; _clock
#+END_SRC

  - =jsr r0, call= 应该就是完整的一个指令了,那么 =_clock= 是用来做什么的呢,功能看得明白,但代码层是怎么跑的?

mfpi	sp

这个指令我想了好久，第一次看文档上发现完全不太明白，后来发现是我粗心，在看 mtpi指令了，
sp 的用法是 -(sp) (sp)+ 因为sp是和内存打交道最密切的，所以它的用法中，必然是要与sp所指向的内存。
#+END_COMMENT


Trap & call 函数


我们用指令 =klou: jsr r0,call; _clock= 来举例，它的栈地址会有以下情况。

#+BEGIN_SRC ditaa :file assets/trap_stack.png :cmdline -r :exports results
+----------------------------------------------------+
| PSW                     | call中, mov 4(sp),-(sp)  |
| 被中断进程的sp          | call中, mfpi sp          |
| 旧的r1                  | call中                   |
| PSW                     | call中                   |
| 旧的r0                  | jsr r0, call时发生       |
| 被中断进程的pc          | 同下                     |
| 被中断进程的PSW         | 进程中断时发生           |
+----------------------------------------------------+
#+END_SRC

#+BEGIN_SRC asm

#+BEGIN_SRC asm
.globl	trap, call
.globl	_trap
trap:
        mov	PS,-4(sp)   // psw放在栈顶两个字长的地方，为的是和下面的call的调用栈保持一致，方便代码复用
        tst	nofault     //检查nofault是否被设置，如果设置了，说明nofault是出错处理函数的地址
        bne	1f          // bne branch if not equal to zero 如果nofault被设置了，就跳到1f处
        mov	SSR0,ssr    // 没有设置nofault, 保存MMU出错寄存器SSR0和SSR2的值至全局数据ssr之中
        mov	SSR2,ssr+4  //
        mov	$1,SSR0     // SSR0的值已经设置了，现在初始化SSR0
        jsr	r0,call1; _trap  // 跳转到call1之中
        / no return
1:
        mov	$1,SSR0     // nofault已经被设置了，那么直接初始化SSR0
        mov	nofault,(sp)  // 栈顶放一下 nofault
        rtt                 //

.globl	_runrun, _swtch
call1:
        tst	-(sp)
        bic	$340,PS
        br	1f

call:                   // 函数调用
        mov	PS,-(sp)
1:
        mov	r1,-(sp)  // 保存r1的值在栈顶
        mfpi	sp        // 把
        mov	4(sp),-(sp)
        bic	$!37,(sp)
        bit	$30000,PS
        beq	1f
        jsr	pc,*(r0)+  // *(r0)+ 是什么寻址模式？
2:
        bis	$340,PS
        tstb	_runrun
        beq	2f
        bic	$340,PS
        jsr	pc,_swtch
        br	2b
2:
        tst	(sp)+
        mtpi	sp
        br	2f
1:
        bis	$30000,PS  // 如果之前是内核模式，把之前的模式设置为用户模式
        jsr	pc,*(r0)+
        cmp	(sp)+,(sp)+
2:
        mov	(sp)+,r1
        tst	(sp)+
        mov	(sp)+,r0
        rtt
#+END_SRC

#+BEGIN_COMMENT
mov	$1,SSR0 #SSR0的作用是什么？


#+END_COMMENT


*** 时钟中断处理

#+BEGIN_SRC C
clock(dev, sp, r1, nps, r0, pc, ps)
{
        register struct callo *p1, *p2;
        register struct proc *pp;

        /*
         * restart clock 重设时钟中断
         */

        *lks = 0115;

        /*
         * display register 操作显示器寄存器，只对pdp 11/45 pdp 11/70有效
         */

        display();

        /* 触发内核定时器，或更新各定时器的触发时间
         * callouts
         * if none, just return
         * else update first non-zero time
         */

        if(callout[0].c_func == 0)
                goto out;
        p2 = &callout[0];
        while(p2->c_time<=0 && p2->c_func!=0)
                p2++;
        p2->c_time--;

        /* 如果之前模式下的中断屏蔽位被设置，则表明程序不希望被某些中断打断，所以不触发定时器
         * if ps is high, just return
         */

        if((ps&0340) != 0)
                goto out;

        /* 触发定时器
         * callout
         */

        spl5();
        if(callout[0].c_time <= 0) {
                p1 = &callout[0];
                while(p1->c_func != 0 && p1->c_time <= 0) {
                        (*p1->c_func)(p1->c_arg);
                        p1++;
                }
                p2 = &callout[0];
                while(p2->c_func = p1->c_func) {
                        p2->c_time = p1->c_time;
                        p2->c_arg = p1->c_arg;
                        p1++;
                        p2++;
                }
        }

        /*
         * lightning bolt time-out
         * and time of day
         */

out:
        if((ps&UMODE) == UMODE) {
                u.u_utime++;
                if(u.u_prof[3])
                        incupc(pc, u.u_prof);
        } else
                u.u_stime++;
        pp = u.u_procp;
        if(++pp->p_cpu == 0)
                pp->p_cpu--;
        if(++lbolt >= HZ) {
                if((ps&0340) != 0)
                        return;
                lbolt =- HZ;
                if(++time[1] == 0)
                        ++time[0];
                spl1();
                if(time[1]==tout[1] && time[0]==tout[0])
                        wakeup(tout);
                if((time[1]&03) == 0) {
                        runrun++;
                        wakeup(&lbolt);
                }
                for(pp = &proc[0]; pp < &proc[NPROC]; pp++)
                if (pp->p_stat) {
                        if(pp->p_time != 127)
                                pp->p_time++;
                        if((pp->p_cpu & 0377) > SCHMAG)
                                pp->p_cpu =- SCHMAG; else
                                pp->p_cpu = 0;
                        if(pp->p_pri > PUSER)
                                setpri(pp);
                }
                if(runin!=0) {
                        runin = 0;
                        wakeup(&runin);
                }
                if((ps&UMODE) == UMODE) {
                        u.u_ar0 = &r0;
                        if(issig())
                                psig();
                        setpri(u.u_procp);
                }
        }
}
#+END_SRC


#+BEGIN_SRC C
int	sysent[]
{
        0, &nullsys,			/*  0 = indir */
        0, &rexit,			/*  1 = exit */
        0, &fork,			/*  2 = fork */
        2, &read,			/*  3 = read */
        2, &write,			/*  4 = write */
        2, &open,			/*  5 = open */
        0, &close,			/*  6 = close */
        0, &wait,			/*  7 = wait */
        2, &creat,			/*  8 = creat */
        2, &link,			/*  9 = link */
        1, &unlink,			/* 10 = unlink */
        2, &exec,			/* 11 = exec */
        1, &chdir,			/* 12 = chdir */
        0, &gtime,			/* 13 = time */
        3, &mknod,			/* 14 = mknod */
        2, &chmod,			/* 15 = chmod */
        2, &chown,			/* 16 = chown */
        1, &sbreak,			/* 17 = break */
        2, &stat,			/* 18 = stat */
        2, &seek,			/* 19 = seek */
        0, &getpid,			/* 20 = getpid */
        3, &smount,			/* 21 = mount */
        1, &sumount,			/* 22 = umount */
        0, &setuid,			/* 23 = setuid */
        0, &getuid,			/* 24 = getuid */
        0, &stime,			/* 25 = stime */
        3, &ptrace,			/* 26 = ptrace */
        0, &nosys,			/* 27 = x */
        1, &fstat,			/* 28 = fstat */
        0, &nosys,			/* 29 = x */
        1, &nullsys,			/* 30 = smdate; inoperative */
        1, &stty,			/* 31 = stty */
        1, &gtty,			/* 32 = gtty */
        0, &nosys,			/* 33 = x */
        0, &nice,			/* 34 = nice */
        0, &sslep,			/* 35 = sleep */
        0, &sync,			/* 36 = sync */
        1, &kill,			/* 37 = kill */
        0, &getswit,			/* 38 = switch */
        0, &nosys,			/* 39 = x */
        0, &nosys,			/* 40 = x */
        0, &dup,			/* 41 = dup */
        0, &pipe,			/* 42 = pipe */
        1, &times,			/* 43 = times */
        4, &profil,			/* 44 = prof */
        0, &nosys,			/* 45 = tiu */
        0, &setgid,			/* 46 = setgid */
        0, &getgid,			/* 47 = getgid */
        2, &ssig,			/* 48 = sig */
        0, &nosys,			/* 49 = x */
        0, &nosys,			/* 50 = x */
        0, &nosys,			/* 51 = x */
        0, &nosys,			/* 52 = x */
        0, &nosys,			/* 53 = x */
        0, &nosys,			/* 54 = x */
        0, &nosys,			/* 55 = x */
        0, &nosys,			/* 56 = x */
        0, &nosys,			/* 57 = x */
        0, &nosys,			/* 58 = x */
        0, &nosys,			/* 59 = x */
        0, &nosys,			/* 60 = x */
        0, &nosys,			/* 61 = x */
        0, &nosys,			/* 62 = x */
        0, &nosys			/* 63 = x */
};
#+END_SRC



** leo总结思考

  - 中断的目的似乎就是为了获取总线，以让 CPU 做一些事情 或者 让CPU以外的外设做某些事情。

  - NPR请求，非处理器请求，指没有处理器参与的请求，优先级比较高

  - br不是 break的意思，是 =bus request!!=
