#+TITLE: awk

* 原理与用法

** 格式

#+BEGIN_SRC bash
awk ' BEGIN{ print "start" } pattern { commands } END{ print "end" } file
#+END_SRC

以下 ~awk脚本~ 被包含在单引号或双引号之间：

#+BEGIN_SRC bash
awk 'BEGIN { statements } { statements } END { end statements }'
# or
awk "BEGIN { statements } { statements } END { end statements }"
#+END_SRC

*** 不要使用双引号

#+BEGIN_SRC bash
$ echo "line1 a b c" | awk '{ print $2 }'
a
$ echo "line1 a b c" | awk "{ print $1 }"
line1 a b c
$ echo "line1 a b c" | awk "{ print $2 }"
line1 a b c
$ echo "line1 a b c" | awk "{ print $3 }"
line1 a b c
#+END_SRC


** 选项

-F 指定分隔符 delimiter

The delimiter can be a regular expression.

#+BEGIN_SRC bash
# 正则中用字符组
awk -F'[/=]' '{print $3 "\t" $5 "\t" $8}' file

# 正则中用或
awk -F"/|=" '{print $3, $5, $NF}' file
#+END_SRC


-f 指定脚本文件

#+BEGIN_SRC bash
$ cat script1
# {print $1 "'s home directory is " $6}
$ gawk -F : -f script1 /etc/passwd

# avahi's home directory is /run/avahi-daemon
# bin's home directory is /bin
# chrony's home directory is /var/lib/chrony
# daemon's home directory is /sbin
# dnsmasq's home directory is /var/lib/empty
# lightdm's home directory is /var/lib/lightdm

# script 也可以定义为:
$ cat script2
{
    text = "'s home directory is"
    print $1 text $6
}
#+END_SRC

** 工作原理

awk命令的工作方式如下所注。

1. 执行BEGIN { commands } 语句块中的语句。

1. 从文件或stdin中读取一行，然后执行pattern { commands }。重复这个过程，直到文件全部被读取完毕。

1. 当读至输入流末尾时，执行END { commands } 语句块。

即分为三个部分， ~BEGIN~, ~END~, 和 ~通用命令~

BEGIN语句块在awk开始从输入流中读取行之前被执行。这是一个可选的语句块，诸如变量初始化、打印输出表格的表头等语句通常都可以写入BEGIN语句块中。

END语句块和BEGIN语句块类似。END语句块在awk从输入流中读取完所有的行之后即被执行。像打印所有行的分析结果这类汇总信息，都是在END语句块中实现的常见任务（例如，在比较过所有的行之后，打印出最大数）。它也是一个可选的语句块。

最重要的部分就是pattern语句块中的通用命令。这个语句块同样是可选的。如果不提供该语句块，则默认执行{ print }，即打印所读取到的每一行。awk对于每一行，都会执行这个语句块。这就像一个用来读取行的while循环，在循环体中提供了相应的语句。

每读取一行，awk就会检查该行和提供的样式是否匹配。样式本身可以是正则表达式、条件语句以及行匹配范围等。如果当前行匹配该样式，则执行{ }中的语句。

** 补充内容

***  特殊变量

以下是可以用于awk的一些特殊变量。

-  ~NR~ 表示记录数量，在执行过程中对应于当前行号。

-  ~NF~ 表示字段数量，在执行过程中对应于当前行的字段数。

-  ~$0~ 这个变量包含执行过程中当前行的文本内容。

-  ~$1~ 这个变量包含第一个字段的文本内容。

-  ~$2~ 这个变量包含第二个字段的文本内容。

#+BEGIN_SRC bash
echo -e "line1 f2 f3\nline2 f4 f5\nline3 f6 f7" |\
awk '{
print "Line no:"NR ",No of fields:"NF, "$0="$0, "$1="$1,"$2="$2,"$3="$3

}'

#################### out put ####################
Line no:1,No of fields:3 $0=line1 f2 f3 $1=line1 $2=f2 $3=f3
Line no:2,No of fields:3 $0=line2 f4 f5 $1=line2 $2=f4 $3=f5
Line no:3,No of fields:3 $0=line3 f6 f7 $1=line3 $2=f6 $3=f7
#+END_SRC


#+BEGIN_SRC bash
seq 5 | awk 'BEGIN{ sum=0; print "Summation:"} { print $1 "+"; sum+=$1 } END { print "=="; print sum }'
Summation:
1+
2+
3+
4+
5+
==
15
#+END_SRC


*** 将外部变量值传递给awk

借助选项 -v，我们可以将外部值（并非来自stdin）传递给awk：

#+BEGIN_SRC bash
$ VAR=10000
$ echo | awk -v VARIABLE=$VAR '{ print VARIABLE }'
10000
#+END_SRC

还有另一种灵活的方法可以将多个外部变量传递给awk，例如：

#+BEGIN_SRC bash
$ var1= "hello" ; var2= "world"
$ echo | awk '{ print v1, v2 }' v1=$var1 v2=$var2
# hello world
$ echo | awk '{ print v1,", ",v2 }' v1=$var1 v2=$var2
# hello, world
#+END_SRC


*** 用getline读取行

awk通常默认读取一个文件的所有行。如果只想读取某一行，可以使用getline函数。

有时候，我们需要从BEGIN语句块中读取第一行。

语法：getline var。变量var就包含了特定行的内容。如果调用不带参数的getline，我们可以用 $0、$1和$2访问文本行的内容。

#+BEGIN_SRC bash
$ seq 5 | awk 'BEGIN { getline; print "Read ahead first line", $0} { print $0 }'
Read ahead first line 1
2
3
4
5
#+END_SRC

#+BEGIN_SRC bash
$ cat fileA
wan
tew
free
phore

awk '{
    if ((getline tmp) > 0) {
      print tmp;
      print $0;
    } else {
      print $0
    }
}'
#+END_SRC


*** 使用过滤模式对awk处理的行进行过滤

#+BEGIN_SRC bash
我们可以为需要处理的行指定一些条件，例如：
$ awk 'NR < 5' # 行号小于5的行
$ awk 'NR==1,NR==4' # 行号在1到5之间的行
$ awk '/linux/' # 包含样式linux的行（可以用正则表达式来指定模式）
$ awk '!/linux/' # 不包含包含模式为linux的行>
#+END_SRC


*** 设置字段定界符

默认的字段定界符是空格。我们也可以用 -F "delimiter"明确指定一个定界符：

#+BEGIN_SRC bash
$ awk -F: '{ print $NF }' /etc/passwd

# 或者
$ awk 'BEGIN { FS=":" } { print $NF }' /etc/passwd
#+END_SRC

#+BEGIN_SRC bash
# 显示passwd中的用户名
$ awk -F: '{print $1}' /etc/passwd;

avahi
bin
daemon
mail
man
...
#+END_SRC
