* SSID & BSSID & ESSID

SSID（Service Set Identifier）　

  　SSID，AP唯一的ID码,许多人认为可以将SSID写成ESSID，其实不然，SSID是个笼统的概念，包含了ESSID和BSSID，用来区分不同的网络，最多可以有32个字符，无线网卡设置了不同的SSID就可以进入不同网络，无线终端和AP的SSID必须相同方可通信。无线网卡设置了不同的SSID就可以进入不同网络。

　　SSID通常由AP广播出来，通过终端自带的扫描功能可以相看当前区域内的SSID。出于安全考虑可以不广播SSID，此时用户就要手工设置SSID才能进入相应的网络。这就是有时候为什么我们明明站在无线路由器的旁边却搜不到信号的原因。简单说，SSID就是一个局域网的名称，只有设置为名称相同SSID的值的设备才能互相通信。 

　　通俗地说，SSID便是你给自己的无线网络所取的名字。需要注意的是，同一生产商推出的无线路由器或AP都使用了相同的SSID，一旦那些企图非法连接的攻击者利用通用的初始化字符串来连接无线网络，就极易建立起一条非法的连接，从而给我们的无线网络带来威胁。因此，建议最好能够将 SSID命名为一些较有个性的名字。
　　无线路由器一般都会提供“允许SSID广播”功能。如果不想让自己的无线网络被别人通过SSID名称搜索到，那么最好“禁止SSID广播”。你的无线网络仍然可以使用，只是不会出现在其他人所搜索到的可用网络列表中。

PS: 通过禁止SSID广播设置后，无线网络的效率会受到一定的影响。
中文SSID无线网络设置的好处

　　默认情况下在进行无线网络设置时都要针对SSID（无线网络名称）进行配置，很多读者都会使用D-Link、TP-Link、Linksys、DD-WRT等默认名称，即使进行了修改，SSID也还是由字母和数字组成。

　　然而，通过字母和数字组成的SSID即使没有设置“广播”，入侵者通过bt3、bt4、网络蚂蚁等工具也可扫描到对应的无线网络并顺利入侵。只有将SSID信息修改为中文才能彻底避免上述问题出现。究其原因，一方面是因为中文字符在这些软件中会显示乱码；另一方面是因为很多入侵工具都是国外开发者开发的，对中文不支持、不兼容。

BSSID

　　是一种特殊的Ad-hoc LAN的应用，一个无线网络至少由一个连接到有线网络的AP和若干无线工作站组成，这种配置称为一个基本服务装置BSS (Basic Service Set)。一群计算机设定相同的BSS名称，即可自成一个group，而此BSS名称，即所谓BSSID

ESSID
　　是infrastructure的应用，一个扩展的服务装置ESS (Extended service set)由二个或多个BSS组成，形成单一的子网。使用者可于ESS上roaming及存取BSSs中的任何资料，其中Access Points必须设定相同的ESSID及channel才能允许roaming。 


备注：通常，手机WLAN中，bssid其实就是无线路由的MAC地址.

　　ESSID 也可认为是SSID, WIFI 网络名
