* samples

** s中match的理解

#+BEGIN_SRC bash
echo "foobarbaz" | sed 's/^foo\(.*\)baz$/\1/'
# bar
echo "foobarbaz" | sed 's/o\(.*\)baz$/\1/'
# fobar
echo "foobarbaz" | sed 's/oo\(.*\)baz$/\1/'
# fbar
#+END_SRC

为什么会出现后面两种情况呢，s的意思是把 ~正则所匹配的内容~ ，用replace打印出来

~o\(.*\)baz$~ 匹配到了 ~obarbaz~ ，前面还剩下 fo， replacement是\1 所以 fo + \1 为 ~fobar~



** 【重要】正则相关的案例 ~不在此处~

正则相关的请参考 ~regular_expression~ 中的 ~appendix-faq.org~

** 多个文件

#+BEGIN_SRC bash
for file in *org; do
   sed -i
done
#+END_SRC

** 简单结合

#+BEGIN_SRC bash
$ seq 6 | sed -n 'N;l;D'
1\n2$
2\n3$
3\n4$
4\n5$
5\n6$
#+END_SRC

- sed starts by reading the first line into the pattern space (i.e. ‘1’).

- At the beginning of every cycle, the N command appends a newline and the next line to the pattern space (i.e. ‘1’, ‘\n’, ‘2’ in the first cycle).

- The l command prints the content of the pattern space unambiguously.

- The D command then removes the content of pattern space up to the first newline (leaving ‘2’ at the end of the first cycle).

- At the next cycle the N command appends a newline and the next input line to the pattern space (e.g. ‘2’, ‘\n’, ‘3’).


** 多行合并，不包含有空行

#+BEGIN_SRC bash
sed '/./{:a;N;s/\n\(.\)/ \1/;ta}'
#+END_SRC

If the line is not empty read the following line and if that is not empty replace the newline by a space and repeat, otherwise print the pattern space. If the line was empty in the first place print the empty line: this caters for an empty first line, if this is not the case then and there is only one empty line between non-blank lines:

#+BEGIN_SRC bash
sed ':a;N;s/\n\(.\)/ \1/;ta' file
#+END_SRC

参考 https://stackoverflow.com/questions/39734125/sed-to-combine-n-text-lines-separated-by-blank-lines


** 有规律的文字

#+BEGIN_SRC bash
$ cat books2.txt
A Storm of Swords
George R. R. Martin
The Two Towers
J. R. R. Tolkien
The Alchemist
Paulo Coelho
The Fellowship of the Ring
J. R. R. Tolkien
The Pilgrimage
Paulo Coelho
A Game of Thrones
George R. R. Martin

$ sed -n '
h;n;H;x
s/\n/, /
Paulo/!b Print
s/^/- /
:Print
p' books2.txt

A Storm of Swords , George R. R. Martin
The Two Towers , J. R. R. Tolkien
- The Alchemist , Paulo Coelho
The Fellowship of the Ring , J. R. R. Tolkien
- The Pilgrimage , Paulo Coelho
A Game of Thrones , George R. R. Martin
#+END_SRC

乍看来上述的代码非常神秘，让我们逐步拆解一下

- 第一行是`h;n;H;x`这几个命令，记得上面我们提到的 **保持空间** 吗？第一个`h`是指将当前模式空间中的内容覆盖到 **保持空间**中，`n`用于提前读取下一行，并且覆盖当前模式空间中的这一行，`H`将当前模式空间中的内容追加到 **保持空间** 中，最后的`x`用于交换模式空间和**保持空间**中的内容。因此这里就是指每次读取两行放到模式空间中交给下面的命令进行处理

- 接下来是 **s/\n/, /** 用于将上面的两行内容中的换行符替换为逗号

- 第三个命令在不匹配的时候跳转到**Print**标签，否则继续执行第四个命令

- **:Print**仅仅是一个标签名，而`p`则是print命令


** Join backslash-continued lines:

#+BEGIN_SRC bash
$ cat 1.txt
this \
is \
a \
long \
line
and another \
line

$ sed -e ':x /\\$/ { N; s/\\\n//g ; bx }'  1.txt
this is a long line
and another line
#+END_SRC


** m 能用来验证其他命令

#+BEGIN_SRC bash
$ seq 10 | sed -n  'N;N;s/.*/b/;p'
b
b
b
#+END_SRC

#+BEGIN_SRC bash
$ seq 10 | sed -n  'N;N;s/.*/b/m;p'
b
2
3
b
5
6
b
8
9
#+END_SRC
