前言

本篇文章就记录一下我在Linux安装配置的vsftpd服务的过程，踩过的坑以及ftp相关的内容！

FTP传输模式

文件传输协议（File Transfer Protocol，FTP），基于该协议FTP客户端与服务端可以实现共享文件、上传文件、下载文件。
FTP基于C/S模式，FTP客户端与服务器端有两种传输模式，分别是FTP主动模式、FTP被动模式。主被动模式均是以FTP服务器端为参照。

* FTP主动模式：客户端从一个任意的端口N（N>1024）连接到FTP服务器的port 21命令端口，客户端开始监听端口N+1，并发送FTP命令“port N+1”到FTP服务器，FTP服务器以数据端口（20）连接到客户端
 指定的数据端口（N+1）。


* FTP被动模式：客户端从一个任意的端口N（N>1024）连接到FTP服务器的port 21命令端口，客户端开始监听端口N+1，客户端提交 PASV命令，服务器会开启一个任意的端口（P >1024），并发送PORT P命
 令给客户端。客户端发起从本地端口N+1到服务器的端口P的连接用来传送数据。


在企业实际环境中，如果FTP客户端与FTP服务端均开放防火墙，FTP需以主动模式工作，这样只需要在FTP服务器端防火墙规则中，开放20、21端口即可。

以上内容来自：http://www.linuxidc.com/Linux/2017-06/144886.htm

Vsftp安装与配置

安装

在linux环境下，使用最多的FTP服务端软件就是Vsftpd！
安装Vsftpd，运行一下命令需要在root用户下进行！

yum install vsftpd

启动服务

service vsftpd start
//或者
systemctl start vsftpd.service

重启服务使用restart

配置

配置文件说明

①/etc/vsftpd/vsftpd.conf这个文件是vsftpd服务的核心配置文件！
我们在修改配置文件的时候，最好先备份一份！

cp /etc/vsftpd/vsftpd.conf /etc/vsftpd/vsftpd.conf.bak

我们先来了解一下里边可以配置的大致内容：

#+BEGIN_SRC conf
# 是否允许匿名登录FTP服务器，默认设置为YES允许
# 用户可使用用户名ftp或anonymous进行ftp登录，口令为用户的E-mail地址。
# 如不允许匿名访问则设置为NO
anonymous_enable=YES
# 是否允许本地用户(即linux系统中的用户帐号)登录FTP服务器，默认设置为YES允许
# 本地用户登录后会进入用户主目录，而匿名用户登录后进入匿名用户的下载目录/var/ftp/pub
# 若只允许匿名用户访问，前面加上#注释掉即可阻止本地用户访问FTP服务器
local_enable=YES
# 是否允许本地用户对FTP服务器文件具有写权限，默认设置为YES允许
write_enable=YES
# 掩码，本地用户默认掩码为077
# 你可以设置本地用户的文件掩码为缺省022，也可根据个人喜好将其设置为其他值
#local_umask=022
# 是否允许匿名用户上传文件，须将全局的write_enable=YES。默认为YES
#anon_upload_enable=YES
# 是否允许匿名用户创建新文件夹
#anon_mkdir_write_enable=YES
# 是否激活目录欢迎信息功能
# 当用户用CMD模式首次访问服务器上某个目录时，FTP服务器将显示欢迎信息
# 默认情况下，欢迎信息是通过该目录下的.message文件获得的
# 此文件保存自定义的欢迎信息，由用户自己建立
#dirmessage_enable=YES
# 是否让系统自动维护上传和下载的日志文件
# 默认情况该日志文件为/var/log/vsftpd.log,也可以通过下面的xferlog_file选项对其进行设定
# 默认值为NO
xferlog_enable=YES
# Make sure PORT transfer connections originate from port 20 (ftp-data).
# 是否设定FTP服务器将启用FTP数据端口的连接请求
# ftp-data数据传输，21为连接控制端口
connect_from_port_20=YES
# 设定是否允许改变上传文件的属主，与下面一个设定项配合使用
# 注意，不推荐使用root用户上传文件
#chown_uploads=YES
# 设置想要改变的上传文件的属主，如果需要，则输入一个系统用户名
# 可以把上传的文件都改成root属主。whoever：任何人
#chown_username=whoever
# 设定系统维护记录FTP服务器上传和下载情况的日志文件
# /var/log/vsftpd.log是默认的，也可以另设其它
#xferlog_file=/var/log/vsftpd.log
# 是否以标准xferlog的格式书写传输日志文件
# 默认为/var/log/xferlog，也可以通过xferlog_file选项对其进行设定
# 默认值为NO
#xferlog_std_format=YES
# 以下是附加配置，添加相应的选项将启用相应的设置
# 是否生成两个相似的日志文件
# 默认在/var/log/xferlog和/var/log/vsftpd.log目录下
# 前者是wu_ftpd类型的传输日志，可以利用标准日志工具对其进行分析；后者是vsftpd类型的日志
#dual_log_enable
# 是否将原本输出到/var/log/vsftpd.log中的日志，输出到系统日志
#syslog_enable
# 设置数据传输中断间隔时间，此语句表示空闲的用户会话中断时间为600秒
# 即当数据传输结束后，用户连接FTP服务器的时间不应超过600秒。可以根据实际情况对该值进行修改
#idle_session_timeout=600
# 设置数据连接超时时间，该语句表示数据连接超时时间为120秒，可根据实际情况对其个修改
#data_connection_timeout=120
# 运行vsftpd需要的非特权系统用户，缺省是nobody
#nopriv_user=ftpsecure
# 是否识别异步ABOR请求。
# 如果FTP client会下达“async ABOR”这个指令时，这个设定才需要启用
# 而一般此设定并不安全，所以通常将其取消
#async_abor_enable=YES
# 是否以ASCII方式传输数据。默认情况下，服务器会忽略ASCII方式的请求。
# 启用此选项将允许服务器以ASCII方式传输数据
# 不过，这样可能会导致由"SIZE /big/file"方式引起的DoS攻击
#ascii_upload_enable=YES
#ascii_download_enable=YES
# 登录FTP服务器时显示的欢迎信息
# 如有需要，可在更改目录欢迎信息的目录下创建名为.message的文件，并写入欢迎信息保存后
#ftpd_banner=Welcome to blah FTP service.
# 黑名单设置。如果很讨厌某些email address，就可以使用此设定来取消他的登录权限
# 可以将某些特殊的email address抵挡住。
#deny_email_enable=YES
# 当上面的deny_email_enable=YES时，可以利用这个设定项来规定哪些邮件地址不可登录vsftpd服务器
# 此文件需用户自己创建，一行一个email address即可
#banned_email_file=/etc/vsftpd/banned_emails
# 用户登录FTP服务器后是否具有访问自己目录以外的其他文件的权限
# 设置为YES时，用户被锁定在自己的home目录中，vsftpd将在下面chroot_list_file选项值的位置寻找chroot_list文件
# 必须与下面的设置项配合
#chroot_list_enable=YES
# 被列入此文件的用户，在登录后将不能切换到自己目录以外的其他目录
# 从而有利于FTP服务器的安全管理和隐私保护。此文件需自己建立
#chroot_list_file=/etc/vsftpd/chroot_list
# 是否允许递归查询。默认为关闭，以防止远程用户造成过量的I/O
#ls_recurse_enable=YES
# 是否允许监听。
# 如果设置为YES，则vsftpd将以独立模式运行，由vsftpd自己监听和处理IPv4端口的连接请求
listen=YES
# 设定是否支持IPV6。如要同时监听IPv4和IPv6端口，
# 则必须运行两套vsftpd，采用两套配置文件
# 同时确保其中有一个监听选项是被注释掉的
#listen_ipv6=YES
# 设置PAM外挂模块提供的认证服务所使用的配置文件名，即/etc/pam.d/vsftpd文件
# 此文件中file=/etc/vsftpd/ftpusers字段，说明了PAM模块能抵挡的帐号内容来自文件/etc/vsftpd/ftpusers中
#pam_service_name=vsftpd
# 是否允许ftpusers文件中的用户登录FTP服务器，默认为NO
# 若此项设为YES，则user_list文件中的用户允许登录FTP服务器
# 而如果同时设置了userlist_deny=YES，则user_list文件中的用户将不允许登录FTP服务器，甚至连输入密码提示信息都没有
#userlist_enable=YES/NO
# 设置是否阻扯user_list文件中的用户登录FTP服务器，默认为YES
#userlist_deny=YES/NO
# 是否使用tcp_wrappers作为主机访问控制方式。
# tcp_wrappers可以实现linux系统中网络服务的基于主机地址的访问控制
# 在/etc目录中的hosts.allow和hosts.deny两个文件用于设置tcp_wrappers的访问控制
# 前者设置允许访问记录，后者设置拒绝访问记录。
# 如想限制某些主机对FTP服务器192.168.57.2的匿名访问，编缉/etc/hosts.allow文件，如在下面增加两行命令：
# vsftpd:192.168.57.1:DENY 和vsftpd:192.168.57.9:DENY
# 表明限制IP为192.168.57.1/192.168.57.9主机访问IP为192.168.57.2的FTP服务器
# 此时FTP服务器虽可以PING通，但无法连接
tcp_wrappers=YES
#+END_SRC

~/etc/vsftpd/ftpusers~ 这个文件是禁止使用vsftpd的用户列表文件。记录不允许访问FTP服务器的用户名单，管理员可以把一些对系统安全有威胁的用户账号记录在此文件中，以免用户从FTP登录后获得大
于上传下载操作的权利，而对系统造成损坏。

~/etc/vsftpd/user_list~ 这个文件禁止或允许使用vsftpd的用户列表文件。这个文件中指定的用户缺省情况（即在/etc/vsftpd/vsftpd.conf中设置userlist_deny=YES）下也不能访问FTP服务器，在设置了
userlist_deny=NO时,仅允许user_list中指定的用户访问FTP服务器。

传输模式配置

开启被动模式：

connect_from_port_20=NO(默认为YES) #设置是否允许主动模式
pasv_enable=YES(默认为YES) #设置是否允许被动模式
pasv_min_port=50000(default:0(use any port))
pasv_max_port=60000(default:0(use any port))

开启主动模式：

connect_from_port_20=YES
pasv_enable=NO

上边配置只是开启所需模式要求的，其他配置看实际需求！

用户访问模式配置

vsftpd服务访问模式有三种：匿名用户模式，系统用户模式和虚拟用户模式！

匿名用户配置

Vsftpd默认以匿名用户访问，匿名用户默认访问的FTP服务器端路径为：/var/ftp/pub，匿名用户只有查看权限，无法创建、删除、修改。
这种模式下，不需改动配置文件，直接启动服务即可访问！

如果想要允许匿名用户能够上传、下载、删除文件，需修改/etc/vsftpd/vsftpd.conf配置文件中：

anon_upload_enable=YES               #允许匿名用户上传文件；
anon_mkdir_write_enable=YES          #允许匿名用户创建目录；
anon_other_write_enable=YES          #允许匿名用户其他写入权限。

另外默认Vsftpd匿名用户有两个：anonymous、ftp，所以匿名用户如果需要上传文件、删除及修改等权限，需要ftp用户对/var/ftp/pub目录有写入权限，使用如下chown和chmod任意一种即可，设置命令如
下：

chown -R ftp pub/

如果要关闭匿名用户登录，只需设置：

anonymous_enable=NO

系统用户配置

匿名模式可以让任何人使用ftp服务，比较公开！多适用于共享文件！如果我们想要特定用户使用，就需要使用系统用户登录访问！这种模式，需要我们新建不同用户，linux创建用户：

useradd 新的用户名
passwd 新的用户名

然后需要修改配置文件：

anonymous_enable=NO   #禁止匿名用户登录
chown_uploads=NO      #设定禁止上传文件更改宿主
nopriv_user=ftptest   #设定支撑Vsftpd服务的宿主用户为新建用户
ascii_upload_enable=YES
ascii_download_enable=YES #设定支持ASCII模式的上传和下载功能。
userlist_enable=YES
userlist_deny=NO

最后打开/etc/vsftpd/user_list文件，将新建的用户添加到最后一行（一个用户一行）

这种模式下，登录访问的目录就是/home/新建用户/

虚拟用户配置

系统用户模式虽然可以控制访问，但是如果用户过多，就会影响服务器系统的管理，对服务器安全造成威胁！而且我们需要的仅仅是可以使用搭建在服务器的FTP服务而已！
那么就需要我们设置虚拟用户进行登录，这也是推荐的方式！这种方式更加安全！

虚拟用户就是没有实际的真实系统用户，而是通过映射到其中一个真实用户以及设置相应的权限来实现访问验证，虚拟用户不能登录Linux系统，从而让系统更加的安全可靠。

一、首先需要我们新建一个虚拟宿主用户，也就是上边说的要映射的真实用户：

useradd virtualhost -s /sbin/nologin

这里设置宿主用户也不允许登录系统！

二、然后修改配置文件，下边我给出我的设置：

anonymous_enable=NO  #设定不允许匿名访问
local_enable=YES  #设定本地用户可以访问。注意：主要是为虚拟宿主用户，如果该项目设定为NO那么所有虚拟用户将无法访问。
write_enable=YES  #设定可以进行写操作。
local_umask=022  #设定上传后文件的权限掩码。
anon_upload_enable=NO  #禁止匿名用户上传。
anon_mkdir_write_enable=NO  #禁止匿名用户建立目录。
dirmessage_enable=YES  #设定开启目录标语功能。
xferlog_enable=YES  #设定开启日志记录功能。
connect_from_port_20=YES #设定端口20进行数据连接。(主动模式)
chown_uploads=NO  #设定禁止上传文件更改宿主。
#chown_username=whoever
xferlog_file=/var/log/xferlog
#设定Vsftpd的服务日志保存路径。注意，该文件默认不存在。必须要手动touch出来，并且由于这里更改了Vsftpd的服务宿主用户为手动建立的Vsftpd。必须注意给与该用户对日志的写入权限，否则服务将启动失败。
xferlog_std_format=YES #设定日志使用标准的记录格式。
#idle_session_timeout=600 #设定空闲连接超时时间，单位为秒，这里默认。
#data_connection_timeout=120 #设定空闲连接超时时间，单位为秒，这里默认
#nopriv_user=ftptest

async_abor_enable=YES  #设定支持异步传输功能。

ascii_upload_enable=YES
ascii_download_enable=YES  #设定支持ASCII模式的上传和下载功能。

ftpd_banner=Welcome to blah FTP service.  #设定Vsftpd的登陆标语。

#deny_email_enable=YES
# (default follows)
#banned_email_file=/etc/vsftpd/banned_emails

chroot_list_enable=NO #禁止用户登出自己的FTP主目录。

# (default follows)
#chroot_list_file=/etc/vsftpd/chroot_list

ls_recurse_enable=NO  #禁止用户登陆FTP后使用"ls -R"的命令。该命令会对服务器性能造成巨大开销。如果该项被允许，那么挡多用户同时使用该命令时将会对该服务器造成威胁。
listen=YES 设定该Vsftpd服务工作在StandAlone模式下
#listen_ipv6=YES

userlist_enable=YES  #设定userlist_file中的用户将不得使用FTP。
#userlist_deny=NO
tcp_wrappers=YES  #设定支持TCP Wrappers

#下边是关于虚拟用户的重要配置
guest_enable=YES  #设定启用虚拟用户功能。
guest_username=virtualhost  #指定虚拟用户的宿主用户。
virtual_use_local_privs=YES  #设定虚拟用户的权限符合他们的宿主用户。
pam_service_name=vsftpd  #设定PAM服务下Vsftpd的验证配置文件名。因此，PAM验证将参考/etc/pam.d/下的vsftpd文件配置。
user_config_dir=/etc/vsftpd/virtualconf  #设定虚拟用户个人Vsftp的配置文件存放路径。也就是说，这个被指定的目录里，将存放每个Vsftp虚拟用户个性的配置文件，一个需要注意的地方就是这些配置文件名必须和虚拟用户名相同。

需要注意的地方：
①Vsftpd的日志文件不存在，建立Vsftpd的日志文件，并更该属主为Vsftpd的服务宿主用户。

touch /var/log/vsftpd.log
chown virtualhost.virtualhost /var/log/vsftpd.log

②建立虚拟用户配置文件存放路径：

mkdir /etc/vsftpd/virtualconf

这里是跟配置文件中的user_config_dir这一项是对应的！

三、接着制作虚拟用户数据库文件，这里需要先安装db4包，用来支持文件数据库。
安装：

yum install db4

然后建立虚拟用户名单文件：touch /etc/vsftpd/virtusers
建立了一个虚拟用户名单文件，这个文件就是来记录vsftpd虚拟用户的用户名和口令的数据文件，我这里给它命名为virtusers。为了避免文件的混乱，我把这个名单文件就放置在/etc/vsftpd/下。
接着编辑这个文件，将虚拟用户信息写入这个文件vi /etc/vsftpd/virtusers

virtual1
123456
virtual2
123456

类似上边的格式，一行用户名，一行密码！
接着生成虚拟用户数据文件：

db_load -T -t hash -f /etc/vsftpd/virtusers /etc/vsftpd/virtusers.db

四、设定PAM验证文件，并指定虚拟用户数据库文件进行读取
这里需要我们安装pam服务，一般系统都会有安装：

yum install pam

Vsftp的PAM验证配置文件：/etc/pam.d/vsftpd
这里对应的就是核心配置文件中的pam_service_name，它会去找/etc/pam.d/vsftpd这个文件！

那么我们需要编辑这个文件，同样的编辑前先备份一下：

cp /etc/pam.d/vsftpd /etc/pam.d/vsftpd.bak

然后编辑文件：vi /etc/pam.d/vsftpd

#%PAM-1.0
auth    sufficient      /lib/security/pam_userdb.so     db=/etc/vsftpd/virtusers
account sufficient      /lib/security/pam_userdb.so     db=/etc/vsftpd/virtusers

以上两条是手动添加的，内容是对虚拟用户的安全和帐户权限进行验证。
这里的auth是指对用户的用户名口令进行验证。
这里的accout是指对用户的帐户有哪些权限哪些限制进行验证。
其后的sufficient表示充分条件，也就是说，一旦在这里通过了验证，那么也就不用经过下面剩下的验证步骤了。相反，如果没有通过的话，也不会被系统立即挡之门外，因为sufficient的失败不决定整
个验证的失败，意味着用户还必须将经历剩下来的验证审核。
再后面的/lib/security/pam_userdb.so表示该条审核将调用pam_userdb.so这个库函数进行。
最后的db=/etc/vsftpd/virtusers则指定了验证库函数将到这个指定的数据库中调用数据进行验证。

这里有一个问题需要注意一下：
如果你的系统是64位的，那么这里要改成：

/lib64/security/pam_userdb.so

否则会验证失败！不能登录！

五、配置虚拟用户
1.规划好虚拟用户的主路径：mkdir /opt/vsftp/
2.建立测试用户的FTP用户目录：

mkdir /opt/vsftp/virtual1/  /opt/vsftp/virtual2/

3.建立虚拟用户配置文件模版：

cp /etc/vsftpd/vsftpd.conf.bak /etc/vsftpd/virtualconf/vconf.tmp

4.定制虚拟用户模版配置文件： vi /etc/vsftpd/virtualconf/vconf.tmp

local_root=/opt/vsftp/virtuser
指定虚拟用户的具体主路径。
anonymous_enable=NO
设定不允许匿名用户访问。
write_enable=YES
设定允许写操作。
local_umask=022
设定上传文件权限掩码。
anon_upload_enable=NO
设定不允许匿名用户上传。
anon_mkdir_write_enable=NO
设定不允许匿名用户建立目录。
idle_session_timeout=600
设定空闲连接超时时间。
data_connection_timeout=120
设定单次连续传输最大时间。
max_clients=10
设定并发客户端访问个数。
max_per_ip=5
设定单个客户端的最大线程数，这个配置主要来照顾Flashget、迅雷等多线程下载软件。
local_max_rate=50000
设定该用户的最大传输速率，单位b/s。

这里将原vsftpd.conf配置文件经过简化后保存作为虚拟用户配置文件的模版。这里将并不需要指定太多的配置内容，主要的框架和限制交由 Vsftpd的主配置文件vsftpd.conf来定义，即虚拟用户配置文件
当中没有提到的配置项目将参考主配置文件中的设定。而在这里作为虚拟用户的配置文件模版只需要留一些和用户流量控制，访问方式控制的配置项目就可以了。这里的关键项是local_root这个配置，用
来指定这个虚拟用户的FTP主路径。
5.更改虚拟用户的主目录的属主为虚拟宿主用户：

 chown -R virtualhost.virtualhost/opt/vsftp/

6.配置虚拟用户，从虚拟用户模版配置文件复制：
cp /etc/vsftpd/virtualconf/vconf.tmp /etc/vsftpd/virtualconf/virtual1

7.针对具体用户进行定制：vi /etc/vsftpd/virtualconf/virtual1

local_root=/opt/vsftp/virtual1
anonymous_enable=NO
write_enable=YES
local_umask=022
anon_upload_enable=NO
anon_mkdir_write_enable=NO
idle_session_timeout=300
data_connection_timeout=90
max_clients=1
max_per_ip=1
local_max_rate=25000

当然，如果很熟练的话3，4，6步骤都可以省略！不要设置！
这里主要是为了方便！可以在原来的基础的进行修改而已！

最后别忘了，开启或者重启服务！

测试

我们可以先在模板目录新建一个空文件

touch /opt/vsftp/virtual1/test.txt

登录一下，在windows打开cmd：(当然我们使用浏览器，或者使用windows文件浏览窗口都可以！)

ftp 192.168.164.133

使用用户virtual1和密码123456登录！
然后输入ls，展示该目录下文件列表。
看有没有我们刚才新建的test.txt文本？！
然后测试一下上传，使用put命令，然后看一下目录中是否有上传的文件？
接着测试一下建立目录操作：mkdir newdir,看是否有新目录被创建？！
然后测试一下下载：使用get test.txt，将test.txt文件下载到本地！注意默认的下载路径为windows用户目录c:\Users\xxxxx目录下`！
这里写图片描述

参考文章：
玩转vsftpd服务器的四大高级配置
我见过最好的vsftpd配置教程

非常感谢上边两篇文章的帮助，少走了很多弯路！

*
木大白易
关注

*
*
 34
 点赞
*
*
 踩
*
*
 7
 评论
*
*
 146
 收藏
*
打赏
 打赏
*
*
*

 扫一扫，分享海报

专栏目录
vsftpd详细配置解读
02-04
vsftpd详细配置解读,vsftpd详细配置解读,vsftpd详细配置解读,vsftpd详细配置解读
CentOS7安装配置vsftpd
david's Blog
11-30
*
4866
本文介绍了在CentOS7上安装FTP服务器vsFTPd的安装与配置。
评论 7 您还未登录，请先 登录 后发表或查看评论
vsftpd配置文件
loamier的专栏
02-09
*
559
vsftpd配置文件采用“#”作为注释符，以“#”开头的行和空白行在解析时将被忽略，其余的行被视为配置命令行，每个配置命令的“＝”两边不要留有空格。对于每个配置命令，在配置文件中还列出了相关的
配置说明，利用vi编辑器可实现对配置文件的编辑修改。方法如下：     #vi /etc/vsftpd/vsftpd.conf1．登录和对匿名用户的设置write_enable=yes            ...
linux vsftpd配置
weixin_30446613的博客
03-06
*
1040
vsftpd是一款在Linux发行版中最受推崇的FTP服务器程序。特点是小巧轻快，安全易用。 如果你想在你的Linux/Unix服务器上搭建一个安全、高性能、稳定性好的FTP 服务器，那么vsftpd可能是你的首选
应用。vsftpd意思为“very secure FTP daemon(非常安全的FTP进程)”，是一个基于GPL发布的类UNIX类操作系统上运行的服务器的名字（是一种守护进程...

vsftp的安装包以及安装方法
02-08
vsftp的安装包以及安装方法。。。。。。。。。。。。。。。
vsftpd安装与配置
Mr-KKO
06-06
*
3万+
简介 vsftpd(very secure FTP daemon)是 UNIX 操作系统中的一个开源的、免费的 FTP 服务软件。它具有以下特点： 安全性高，轻小易用 支持系统用户、匿名用户和虚拟用户的权限验证和相关操作，
但无论哪种用户，最终都会映射为一个对应的 系统用户 用户认证是基于 PAM 实现的 安装 yum 安装 vsftpd，并开启程序 # 安装 [root@instance-36...
linux安装及配置vsftpd
qq_35562664的博客
08-10
*
1万+
阿里云-centos7安装vsftpd  1. 安装vsftpd       yum install vsftpd 2. 新建vsftpd 用户文件夹（家目录）     mkdir /media/file 3. 新增vsftpd用户，并且指定用户的home目录    useradd –d
/media/file-g ftp –s /sbin/nologin ftpuser    ...
Ubuntu 16.04下vsftpd 安装配置实例（ftp服务器搭建）
Mr.韩的博客
05-23
*
2万+
看了网上很多关于Ubuntu下vsftpd的安装配置教程，发现很多都是不可以用的，经过多次尝试，总结了一个Ubuntu 16.04下最简单的设置方法。第一步：安装VSFTPDsudo apt-get install vsftpd　　 安
装完成后启动VSFTPD服务：service vsftpd start第二步：新建目录/home/uftp作为用户主目录sudo mkdir /home/uftp　...
Linux系统部署FTP之Vsftp的安装及应用
DoubleJing的博客
10-20
*
1652
1. Vsftp介绍 特点：安全、高速、稳定 模式：c/s 查看端口的使用，从下图可以看出20端口是用于ftp传数据的，而21端口用于传指令的，ftp分为被动模式和主动模式，被动模式时由远程端决定通信的
端口，主动模式时默认用本地发起ftp的端口，Vsftp是ftp的一种，顾名思义是很安全的ftp，我们就来将其部署在 Linux系统上. [root@node2 ~]# vim /etc/servic...
VSFTP安装总结
马赛克的博客
02-27
*
1099
1以root用户登录CentOS 7系统 2 安装vsftpd服务 yum install vsftpd -y 3 开启vsftpd服务 systemctl start vsftpd 4 配置vsftpd服务 4.1关闭匿名用户 vi /etc/vsftpd/vsftpd.conf 在
vsftpd.conf配置文件中修改以下三项： anonymous_enable=N...
史上最详细的vsftpd配置文件详解
09-30
vsftpd作为一个主打安全的FTP服务器，有很多的选项设置。下面介绍了vsftpd的配置文件列表，而所有的配置都是基于vsftpd.conf这个配置文件的。本文将提供完整的vsftpd.conf的中文说明
vsftpd 配置
qq_33782617的博客
03-10
*
75
1、sudo apt-get update 2、sudo apt-get install vsftpd 3、useradd -d /home/test test //增加用户test，并制定test用户的主目录为/home/test 4、passwd test //为test设置密码 5、usermod
-s /sbin/nologin test #限定用户test不能telnet，只能ftp 先...
vsftpd配置
qq_38984126的博客
12-20
*
398
local_root=/opt/vsftp/file #指定虚拟用户仓库的具路径 anonymous_enable=NO #设定不允许匿名访问 write_enable=YES #允许写的操作 local_umask=022 #上传文件的权限掩码
anon_upload_enable=NO #不允许匿名上传 anon_mkdir_write_enable=NO #不允许匿名用户建立目录 idle_...
linux下的vsftpd
技术小白
10-29
*
608
安装ftp   通过yum命令查看并安装ftp的vsftpd.x86_64版本   system enable vsftpd    //设为开机启动 通过firewall-config配置防火墙否则ftp为服务无法通过防火墙，如图首先选择为Permanent模
式，然后将ftp勾选，最后点击Options选项卡的第一个选项生效   关闭selinux服务 通过配置...
vsftpd的安装和使用
热门推荐
Aaron_Run的博客
04-08
*
5万+
目录 1、vsftpd的简介... 2 2、特点... 2 3、安装... 2 4、创建虚拟用户... 2 5、vsftpd服务器的配置... 4 6、vsftpd配置文件说明... 7 7、防火墙的配置... 8 8、vsftpd的验证... 9 9、vsftpd
的常用命令... 10 10、反复需要验证ftp身份问题解决... 10 1、vsftpd的简介 vsftpd...
linux安装vsftpd服务,Linux系统安装Vsftpd
最新发布
weixin_42373066的博客
05-02
*
105
本文讲解如何使用Yum安装Vsftpd，以Censtos 6.2 64位系统为例1.安装Vsftpd首先使用SSH登录到系统然后使用命令yum install vsftpd 安装，根据提示选择Y,如图1-1所示:图1-1安装完成后，使用命令
service vsftpd start启动FTP服务.编辑FTP配置文件vim /etc/vsftpd/vsftpd.conf，找到chroot_local_...
ftp&vsftpd服务
sky__man的博客
11-19
*
7966
一. ftp ftp即文件传输，它是INTERNET上仍然常用的最老的网络协议之一，它为系统提供了通过网络与远程服务器传输的简单方法，FTP服务器包的名称为vsftpd 二. 部署ftp服务 1. 安装ftp yum
install -y vsftpd                                              #安装vsftpd软件包 sy
vsftpd配置文件讲解
jxfgh的专栏
11-02
*
1162
本文根据RedKing的帖子整理节选而来。原文地址在http://bbs.51cto.com/thread-717151-1.html。vsftpd作为一个主打安全的FTP服务器，有很多的选项设置。下面介绍了vsftpd的配置文件列表，而所有
的配置都是基于vsftpd.conf这个配置文件的。本文将提供完整的vsftpd.conf的中文说明。学习本文的内容将有助于你初步了解vsftpd的配置文件，但针对具体情况还需要制定具体的配置方法。51CTO推荐
专题：vsftpd入门——安装、配置、案例与常见问题vsf
FTP 的安装与配置
dingjiayi 有幸识之
04-14
*
1196
FTP 的安装与配置 1. 参考内容 1.1 https://help.aliyun.com/document_detail/51998.html 1.2 http://wiki.ubuntu.org.cn/Vsftpd 1.3
http://wiki.ubuntu.org.cn/Vsftpd%E8%99%9A%E6%8B%9F%E7%94%A8%E6%88%B7%E8%AE%BE%E...
Linux中安装vsftpd
daydrawn的博客
04-05
*
2297
一 安装vsftpd组件yum -y install vsftpd 二 添加一个ftp用户useradd ftpuser这样一个用户建完，可以用这个登录，记得用普通登录不要用匿名了。登录后默认的路径为 /home/ftpuser 三 给ftp用户
添加密码 passwd ftpuser（ftpuser） 四 防火墙开启21端口 因为ftp默认的端口为21，而centos默认是没有...
©️2022 CSDN 皮肤主题：程序猿惹谁了 设计师：我叫白小胖 返回首页
*
木大白易 CSDN认证博客专家 CSDN认证企业博客
码龄7年
*
暂无认证

197
 原创

2万+
 周排名

1617
 总排名

131万+
 访问

*
 等级

1万+
 积分

254
 粉丝

556
 获赞

172
 评论

616
 收藏

GitHub
专栏达人
持之以恒
勤写标兵Lv1
私信
关注

*

热门文章

* yum -y install与yum install有什么不同
*
 105052
* 如何使用Tensorboard查看远程服务器的训练情况
*
 57047
* Android SDK目录及版本号区别
*
 46752
* RxJava 2.0 使用详解
*
 43975
* 关于Linux环境下安装配置vsftpd服务全攻略（踩坑）
*
 40138

分类专栏

*
*
 音视频 2篇
*
*
 FFmpeg 2篇
*
*
 c++ 8篇
*
*
 React Native入门 15篇
*
*
 Socket网络编程 5篇
*
*
 OkHttp3源码分析 4篇
*
*
 JAVA学习笔记 24篇
*
*
 Android学习笔记 124篇
*
*
 iOS学习笔记 3篇
*
*
 TensorFlow 1篇
*
*
 React Native入门 19篇
*
*
 Python学习笔记 5篇
*
*
 图像处理 3篇
*
*
 常用的Android开发工具类 19篇
*
*
 RxJava 2篇
*
*
 算法 6篇
*
*
 数据结构 8篇
*
*
 Socket网络编程——简单聊天系统 5篇
*
*
 数据库 7篇
*
*
 Linux OS 10篇
*
*
 Node.js 1篇
*
*
 BI 6篇
*
*
 跨平台移动应用开发 3篇
*
*
 JavaScript 1篇
*
*
 AngularJS 1篇
*
*
 没事聊聊天呗 1篇
*
*
 Windows小贴士 1篇
*
*
 Git 2篇
*
*
 工具 4篇

*

最新评论

* 关于Linux环境下安装配置vsftpd服务全攻略（踩坑）

 羊洋杨耶！: 匿名用户的那个/var/ftp/pub是自动创建的还是需要手动创建呀，我的/var里就没有这个目录

* Android获取应用通知栏权限，并跳转通知设置页面（全版本适配）

 Lyjun123: NotificationManagerCompat.from(this).areNotificationsEnabled(); 重点就在这个

* RecyclerView中含有CheckBox多选、单选和RadioGoup全解

 dragon_and_tree: 看了好几个只有你这个指出了优先级的问题

* RecyclerView中含有CheckBox多选、单选和RadioGoup全解

 dragon_and_tree: 赞赞赞

* 关于Linux环境下安装配置vsftpd服务全攻略（踩坑）

 wjt123125: 感谢博主!

您愿意向朋友推荐“博客详情页”吗？

*
*
*
 强烈不推荐
*
*
*
 不推荐
*
*
*
 一般般
*
*
*
 推荐
*
*
*
 强烈推荐

                                         提交

最新文章

* H.264编解码浅析
* CMake构建类型和编译选项
* loadLibrary动态库加载过程分析

2022年1篇
2021年16篇
2020年13篇
2019年24篇
2018年10篇
2017年61篇
2016年69篇
2015年55篇

目录

目录

分类专栏

*
*
 音视频 2篇
*
*
 FFmpeg 2篇
*
*
 c++ 8篇
*
*
 React Native入门 15篇
*
*
 Socket网络编程 5篇
*
*
 OkHttp3源码分析 4篇
*
*
 JAVA学习笔记 24篇
*
*
 Android学习笔记 124篇
*
*
 iOS学习笔记 3篇
*
*
 TensorFlow 1篇
*
*
 React Native入门 19篇
*
*
 Python学习笔记 5篇
*
*
 图像处理 3篇
*
*
 常用的Android开发工具类 19篇
*
*
 RxJava 2篇
*
*
 算法 6篇
*
*
 数据结构 8篇
*
*
 Socket网络编程——简单聊天系统 5篇
*
*
 数据库 7篇
*
*
 Linux OS 10篇
*
*
 Node.js 1篇
*
*
 BI 6篇
*
*
 跨平台移动应用开发 3篇
*
*
 JavaScript 1篇
*
*
 AngularJS 1篇
*
*
 没事聊聊天呗 1篇
*
*
 Windows小贴士 1篇
*
*
 Git 2篇
*
*
 工具 4篇

打赏作者
*

*

木大白易

你的鼓励将是我创作的最大动力

¥2 ¥4 ¥6 ¥10 ¥20
输入1-500的整数
*
*
余额支付 (余额：-- )
*
*
扫码支付
扫码支付：¥2
*
获取中
*
*
扫码支付

您的余额不足，请更换扫码支付或充值

打赏作者

实付元
使用余额支付
*
点击重新获取
*
*
*
扫码支付
SVG Image
[ ] 钱包余额 0
*

抵扣说明：

1.余额是钱包充值的虚拟货币，按照1:1的比例进行支付金额的抵扣。
2.余额无法直接购买下载，可以购买VIP、C币套餐、付费专栏及课程。

*
余额充值
