* DHCP


动态主机设置协议（Dynamic Host Configuration Protocol，缩写：DHCP）是一个用于局域网的网络协议，位于OSI模型的应用层，使用UDP协议工作，主要有两个用途：

- 用于内部网或网络服务供应商自动分配IP地址给用户

- 用于内部网管理员对所有电脑作中央管理


DHCP用一台或一组DHCP服务器来管理网络参数的分配，这种方案具有容错性。即使在一个仅拥有少量机器的网络中，DHCP仍然是有用的，因为一台机器可以
几乎不造成任何影响地被增加到本地网络中。

甚至对于那些很少改变地址的服务器来说，DHCP仍然被建议用来设置它们的地址。如果服务器需要被重新分配地址（RFC 2071）的时候，就尽可能不去做更
改。对于一些设备，如路由器和防火墙，则不应使用DHCP。把TFTP或SSH服务器放在同一台运行DHCP的机器上也是有用的，目的是为了集中管理。

DHCP也可用于直接为服务器和桌面计算机分配地址，并且透过一个PPP代理，也可为拨接及宽带的主机，以及住宅NAT网关和路由器分配地址。DHCP一般不适
用于使用在无边际路由器和DNS服务器上。

** 历史

DHCP于1993年10月成为标准协议，其前身是BOOTP协议。当前的DHCP定义可以在RFC 2131中找到，而基于IPv6的建议标准（DHCPv6）可以在RFC 3315中找
到。

** 原理

动态主机设置协议（DHCP）是一种使网络管理员能够集中管理和自动分配IP网络地址的通信协议。在IP网络中，每个连接Internet的设备都需要分配唯一的IP地址。DHCP使网络管理员能从中心结点监控和分配IP地址。当某台计算机移到网络中的其它位置时，能自动收到新的IP地址。

DHCP使用了租约的概念，或称为计算机IP地址的有效期。租用时间是不定的，主要取决于用户在某地连接Internet需要多久，这对于教育行业和其它用户频繁改变的环境是很实用的。透过较短的租期，DHCP能够在一个计算机比可用IP地址多的环境中动态地重新配置网络。DHCP支持为计算机分配静态地址，如需要永久性IP地址的Web服务器。

DHCP和另一个网络IP管理协议BOOTP类似。当前两种配置管理协议都得到了普遍使用，其中DHCP更为先进。某些操作系统，如Windows NT/2000，都带有DHCP服务器。DHCP或BOOTP客户端是装在计算机中的一个程序，这样就可以对其进行配置操作。

#+BEGIN_SRC bash
[C:\~]$ ipconfig /all

Windows IP 配置

   主机名  . . . . . . . . . . . . . : wcc0021z673252
   主 DNS 后缀 . . . . . . . . . . . : oa.cmbccd.cmbchina.com
   节点类型  . . . . . . . . . . . . : 混合
   IP 路由已启用 . . . . . . . . . . : 否
   WINS 代理已启用 . . . . . . . . . : 否
   DNS 后缀搜索列表  . . . . . . . . : oa.cmbccd.cmbchina.com

以太网适配器 以太网 2:

   连接特定的 DNS 后缀 . . . . . . . :
   描述. . . . . . . . . . . . . . . : ASIX AX88179 USB 3.0 to Gigabit Ethernet Adapter
   物理地址. . . . . . . . . . . . . : 00-0E-C6-DC-F6-84
   DHCP 已启用 . . . . . . . . . . . : 否
   自动配置已启用. . . . . . . . . . : 是
   IPv6 地址 . . . . . . . . . . . . : fd88:b423:8f24::4bc(首选)
   获得租约的时间  . . . . . . . . . : 2020年4月8日 8:20:13
   租约过期的时间  . . . . . . . . . : 2156年5月15日 17:29:10
   IPv6 地址 . . . . . . . . . . . . : fd88:b423:8f24:0:2811:cc8d:3822:638f(首选)
   临时 IPv6 地址. . . . . . . . . . : fd88:b423:8f24:0:6c30:a0d0:92db:345e(首选)
   本地链接 IPv6 地址. . . . . . . . : fe80::2811:cc8d:3822:638f%18(首选)
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.91(首选)
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . :
   DHCPv6 IAID . . . . . . . . . . . : 83889862
   DHCPv6 客户端 DUID  . . . . . . . : 00-01-00-01-25-72-18-F4-00-0E-C6-DC-F6-84
   DNS 服务器  . . . . . . . . . . . : fd88:b423:8f24::1
                                       fd88:b423:8f24::1
   TCPIP 上的 NetBIOS  . . . . . . . : 已启用
#+END_SRC



https://en.wikipedia.org/wiki/Dynamic_Host_Configuration_Protocol

https://zh.wikipedia.org/wiki/%E5%8A%A8%E6%80%81%E4%B8%BB%E6%9C%BA%E8%AE%BE%E7%BD%AE%E5%8D%8F%E8%AE%AE
