* SMP

Symmetric multiprocessing (SMP) involves a multiprocessor computer hardware and software architecture where two or more identical processors are connected to a single, shared main memory, have full access to all input and output devices, and are controlled by a single operating system instance that treats all processors equally, reserving none for special purposes. Most multiprocessor systems today use an SMP architecture. In the case of multi-core processors, the SMP architecture applies to the cores, treating them as separate processors.

称多处理是一种多处理机硬件架构，有两个或更多的相同的处理机（处理器）共享同一主存，由一个操作系统控制。当前最常见的多处理机系统使用了对称多处理架构。以多核处理器为例，对称多处理架构就是这些核，它把这些核当作不同的处理器。不同的处理器之间可以由总线、矩阵开关或片上mesh网络来连接。使用总线或矩阵开关的对称多处理架构有可扩展性方面的瓶颈，它是由处理器之间连接的带宽、能耗，以及内存和磁盘阵列等引起的。使用mesh连接的架构避免了这些瓶颈。它能够支持更多数量的处理器，具有几乎线性的可扩展性，代价是牺牲可编程性。

优点是并发度很高，但是由于系统总线的带宽是有限的，故处理器的数目是受限的。


* 多核系统

芯片厂商在生产多核处理器时一厢情愿地认为软件开发者将为多核处理器开发软件，问题是目前的桌面系统软件不能有效地利用多核处理器，因为开发者需要利用并行编程技术才能充分利用多核处理器的处理能力。除专业的科学计算软件外，并行软件并不普及，而且并行编程技术也相对难以掌握。一种更好的方法是重新考虑操作系统管理多核处理器的方式，“问题不在于并行编程，而在于操作系统如何管理处理器”，微软正在开发针对多核处理器的全新一代多核操作系统。从目前来看，多核操作系统滞后于多核处理器的发展，而多核技术作为一个系统，其中的“短板”将严重制约计算机整体性能的提升。可以说，多核操作系统技术的突破，将会带来从嵌入式领域到桌面计算机、服务器等所有计算机系统的性能的一个整体性提高，因此对于多核操作系统的研究意义非常重大。



* 从多核到众核处理器

集成度还在以摩尔定律的速度增长，但是性能的增长遇到了三个物理规律的限制。第一是功耗，第二是互连线延时，第三是设计复杂度。

** 功耗限制

晶体管的主要工作就以翻转提供信息计算，要让晶体管翻转就是给他们提供能量，而他们一翻转就要发热。从Intel 80286到Pentium 4的路线一直是让晶体管翻转得越来越快（约两千倍的差别），处理器频率随之不断上升，也就是意味单位时间提供给芯片的能量——功耗，会逐步上升，发热也越来越厉害。一个很明显的现象是，286不需要散热，但是Pentium IV却需要散热片加强劲的风扇。这种靠不断增加翻转速度的方式带来的最大好处是同一个程序，你什么优化也不做，买一个下一代的芯片就可以让程序跑快很多。但是与此同时，翻转速度的上升带来功耗的急剧增长，所散热超过了风扇散热的热预算。不幸地是，散热的能力却不能够同步增长，这限制了处理器所发热的总功耗，从而使得传统地提高处理器频率的老法子不再具有可扩展性。单核处理器的性能发展走到了尽头。那摩尔定律提供的多余的处理器怎么办呢？最简单的办法就是用来增加单片集成处理器核的数量而不是性能。

** 互联线延迟

芯片上除了晶体管就是互连线。它的主要工作是把一个晶体管干活儿的结果给另一个晶体管，是个车间搬运工的角色。曾几何时，晶体管是很慢的，所以没人在乎这种搬运工带来的任何延时影响。但是随着晶体管越来越小，越来越快，互连线的延迟并不随之变块，这就成了问题了。以前晶体管每翻转一次的时间互连线能够把数据从芯片的一头送到另一头，而如今这种对角线传输得花好几个晶体管翻转的时间。摩尔定律说晶体管集成度越来越高，但是互连线却相对的越来越慢了。这带来的最大问题是干一件事情需要花的步骤更多了，打个比方就是工厂里的流水线级数越来越多，很多步骤都花在把东西从一个车间搬到另一个车间上。在Pentium IV的时候，干一件事情（执行一条指令）要花20级流水线。流水线级数长不是什么好事，因为一旦当流水线级前面处理的东西出了问题，后面正在处理的那些东西就得重头来做。当年AMD Athon之所有能够在与Intel Pentium 4争夺中占领一席之地，就是因为虽然AMD的晶体管翻得慢，但流水线级数少，因此那种重头来做的机会和代价都小，因此性能还很高。 克服互联线延迟增加的最好办法就是把一个大厂房分成很多个小厂房，事情都在一个小厂房里解决，这样运输的距离就变短了。换句话说，使用较小的核组成一个多核的芯片，而不是以往的单核芯片。

设计复杂度：随着晶体管数量的增加，芯片设计的设计空间、设计复杂度和验证难度都是大幅度增加的。话说Intel六核的iCore7上集成了超过十亿个晶体管，其设计难度之大可想而知。如果采用多个重复设计处理器核，那么设计的复杂度就会大大降低，从而使得设计成本降低，出错的机会也减小了。

总结一下，多核系统的出现是摩尔定律与物理规律限制相互作用的结果，三个主要的限制是：功耗、互连、设计复杂度。一个处理器上的晶体管数越来越多，但是他们却因为功耗和互连线的限制并不能直接提供很高的性能，那么怎么办呢？一个最简单的办法就是用在一个处理器中集成多个简单的处理器核。这样既把多出来的晶体管用上了，而每个处理器核就像前一代的处理器一样简单，因此不必提高他们的翻转速度，各个处理器核只需要自己交换数据，因此没有很长的连线延迟。这也就是Intel放弃Pentium IV采用Core 2结构的缘由，也是本篇文章最本质的原理。


从单核到多核乃至未来众核的变化并不是芯片设计公司根据客户需求，市场趋势做出的主动选择，而是在物理规律限制不得已的情况下被逼走上的道路。这意味着以前那种处理器频率越来越高的时代已经一去不复返了。在那个已经过去的黄金时代，程序员不需要怎么优化程序，因为优化程序所花的功夫和时间还不一定值得去市场上买一个新款处理器。这也就使得Microsoft敢于做越来越慢的软件。他不怕因为软件太慢卖不出去，因为处理器的翻转速度的增长会使得他本来很慢的软件，不久就会快得可以接受。但是这个故事已经结束了，现在的新款处理器跑老程序并不会快到哪里去，而当你买了新处理器还得对老程序作进一步的优化才能利用上新增的晶体管。这可能也就是微软的Vista按照老路子设计，但卖得没那么好的原因，也带来了微软裁员5000人，但是linux却还是比较红火的结果。下面这个图是09年初Redhat Linux和Windows的股票走势，可以比较明显的看出来，当处理器速度不再翻倍的时候，当人们没钱总是换硬件的时候，微软的表现就不是那么好了。因为Windows Vista是微软沿用了以前处理器发展规律设计的操作系统，因此并不叫座。微软公司不得不花大力气重写了他们的内核代码，推出了Windows 7来收拾Vista的残局。
