* 命令列表

圆括号内为助记符

The following commands are supported in GNU sed. Some are standard POSIX commands, while other are GNU extensions. Details and examples for each command are in the following sections. (Mnemonics) are shown in parentheses.

s 替换指定字符
h 拷贝模板块的内容到内存中的缓冲区。
H 追加模板块的内容到内存中的缓冲区。
g 获得内存缓冲区的内容，并替代当前模板块中的文本。
G 获得内存缓冲区的内容，并追加到当前模板块文本的后面。
l 列表不能打印字符的清单。
L 同l，不显示非打印字符
n 读取下一个输入行，用下一个命令处理新的行而不是用第一个命令。
N 追加下一个输入行到模板块后面并在二者间嵌入一个新行，改变当前行号码。
p 打印模板块的行。
P(大写) 打印模板块的第一行。
q 退出Sed。
b lable 分支到脚本中带有标记的地方，如果分支不存在则分支到脚本的末尾。
r file 从file中读行。
t label if分支，从最后一行开始，条件一旦满足或者T，t命令，将导致分支到带有标号的命令处，或者到脚本的末尾。
T label 错误分支，从最后一行开始，一旦发生错误或者T，t命令，将导致分支到带有标号的命令处，或者到脚本的末尾。
w file 写并追加模板块到file末尾。
W file 写并追加模板块的第一行到file末尾。
! 表示后面的命令对所有没有被选定的行发生作用。
= 打印当前行号码。
# 把注释扩展到下一个换行符以前。


** a

Append text after a line. 在当前行下面插入文本。

#+BEGIN_SRC bash
a\
text
# or
a text
#+END_SRC

*** demo

#+BEGIN_SRC bash
# 其中的1i表明，其要在第1行前插入一行（insert）
$ sed "1 i hello" my.txt
$ sed "1,$ i hello" my.txt

# 其中的a表明，其要在最后一行后追加一行（append）
sed "$ a hello" my.txt
#+END_SRC

** b


#+BEGIN_SRC bash
b label
#+END_SRC

Branch unconditionally to label. The label may be omitted, in which case the next cycle is started.

** c

Replace (change) lines with text. 把选定的行改为新的文本。

#+BEGIN_SRC bash
c\
text

# or
c text
#+END_SRC

** d
#+BEGIN_SRC bash
d
#+END_SRC

删除，删除选择的行。 Delete the pattern space; immediately start next cycle.

** D

#+BEGIN_SRC bash
D
#+END_SRC

如果 pattern spaces中有多行，删除 pattern space中的所有内容，直至最新的一行，并以  pattern space中的结果重新开启新一轮的cycle

如果 pattern space中没有内容，效果与d相同

删除模板块的第一行。

If pattern space contains newlines, delete text in the pattern space up to the first newline, and restart cycle with the resultant pattern space, without reading a new line of input.

If pattern space contains no newline, start a normal new cycle as if the d command was issued.

** e

#+BEGIN_SRC bash
e
#+END_SRC

Executes the command that is found in pattern space and replaces the pattern space with the output; a trailing newline is suppressed.

** e command

#+BEGIN_SRC bash
e command
#+END_SRC

Executes command and sends its output to the output stream. The command can run across multiple lines, all but the last ending with a back-slash.

** F

#+BEGIN_SRC bash
F
#+END_SRC
(filename) Print the file name of the current input file (with a trailing newline).

** g
#+BEGIN_SRC bash
g
#+END_SRC

Replace the contents of the pattern space with the contents of the hold space.

** G

#+BEGIN_SRC bash
G
#+END_SRC

Append a newline to the contents of the pattern space, and then append the contents of the hold space to that of the pattern space.

** h
#+BEGIN_SRC bash
h
#+END_SRC

(hold) Replace the contents of the hold space with the contents of the pattern space.

用pattern space空间的内容替换hold space 空间的内容

** H

#+BEGIN_SRC bash
H
#+END_SRC

Append a newline to the contents of the hold space, and then append the contents of the pattern space to that of the hold space.

在 hold space区域追加一个换行，然后再加入pattern space中的内容追加到 hold space之中

** i

#+BEGIN_SRC bash
i\
text
#or
i text
#+END_SRC

insert text before a line. 在当前行上面插入文本。与 ~a~ 命令类似

** l

Print the pattern space in an unambiguous form.

以明确的形式打印 pattern space

** n

(next) If auto-print is not disabled, print the pattern space, then, regardless, replace the pattern space with the next line of input. If there is no more input then sed exits without processing any more commands.

用inptut中的新一行来替换pattern space 中的内容。

** N
#+BEGIN_SRC bash
N
#+END_SRC

pattern space中添加一行，并把input的新一行添加进去 pattern Space

Add a newline to the pattern space, then append the next line of input to the pattern space. If there is no more input then sed exits without processing any more commands.

*** demo

下面的的示例会把原文本中的偶数行纳入奇数行匹配，而s只匹配并替换一次，所以，就成了下面的结果：

#+BEGIN_SRC bash
$ sed 'N;s/my/your/' pets.txt
#+END_SRC

原文件
#+BEGIN_SRC txt
This is my cat
  my cat's name is betty
This is my dog
  my dog's name is frank
This is my fish
  my fish's name is george
This is my goat
  my goat's name is adam
#+END_SRC

新文件

#+BEGIN_SRC txt
This is your cat
  my cat's name is betty
This is your dog
  my dog's name is frank
This is your fish
  my fish's name is george
This is your goat
  my goat's name is adam
#+END_SRC


也就是说，N处理原文件时，是这样的。

#+BEGIN_SRC txt
This is my cat\n  my cat's name is betty
This is my dog\n  my dog's name is frank
This is my fish\n  my fish's name is george
This is my goat\n  my goat's name is adam
#+END_SRC

** p

#+BEGIN_SRC bash
p
#+END_SRC

Print the pattern space. 打印 ~pattern space~

** P
#+BEGIN_SRC bash
P
#+END_SRC

Print the pattern space, up to the first <newline>.

** q[exit-code]

#+BEGIN_SRC bash
q[exit-code]
#+END_SRC

 (quit) Exit sed without processing any more commands or input.

** Q[exit-code]
#+BEGIN_SRC bash
Q[exit-code]
#+END_SRC

 (quit) This command is the same as q, but will not print the contents of pattern space. Like q, it provides the ability to return
 an exit code to the caller.

** r filename

#+BEGIN_SRC bash
r filename
#+END_SRC

Reads file filename.

** R filename

#+BEGIN_SRC bash
R filename
#+END_SRC

Queue a line of filename to be read and inserted into the output stream at the end of the current cycle, or when the next input line is read.

** s替换 s/regexp/replacement/[flags]

#+BEGIN_SRC bash
s/regexp/replacement/[flags]
#+END_SRC

substitute 替换，对pattern space的使用正则表达式，如果发现了，就替换。

(substitute) Match the regular-expression against the content of the pattern space. If found, replace matched string with replacement.

** t label

 (test) Branch to label only if there has been a successful substitution since the last input line was read or conditional branch
 was taken. The label may be omitted, in which case the next cycle is started.

** T label

 (test) Branch to label only if there have been no successful substitutions since the last input line was read or conditional branch
 was taken. The label may be omitted, in which case the next cycle is started.

** v [version]

 (version) This command does nothing, but makes sed fail if GNU sed extensions are not supported, or if the requested version is not
 available.

** w filename

 Write the pattern space to filename.

** W filename

Write to the given filename the portion of the pattern space up to the first newline

** x

Exchange the contents of the hold and pattern spaces.

** y/src/dst/

Transliterate any characters in the pattern space which match any of the source-chars with the corresponding character in dest-chars.

** z

(zap) This command empties the content of pattern space.

** # 注释

A comment, until the next newline.

** 多个命令

#+BEGIN_SRC bash
{ cmd ; cmd ... }
#+END_SRC

Group several commands together.

** =

Print the current input line number (with a trailing newline).

** : label

Specify the location of label for branch commands (b, t, T).
