* 指令集


** 地址模式



#+BEGIN_SRC C
mov r1, r0 把r1中的内容放入到r0
mov (r1), r0, 把r1指向的内存地址上的内容传入到r0
#+END_SRC

** pdp11-process-handbook


*** 单操作数寻址模式

#+BEGIN_SRC ditaa :file assets/par-desc.png :cmdline -r :exports results

+-------------------------------------------------------------------------------+
|                                                 |              |              |
| 15 | 14 | 13 | 12 | 11 | 10 |  9 |  8 |  7 |  6 |  5 |  4 |  3 |  2 |  1 |  0 |
|                                                 |              |              |
|             OP CODE                             |    MODE      |      Rn      |
+-------------------------------------------------------------------------------+

#+END_SRC

15 - 6位指定了是哪些操作

5 - 3 指定了寻址模式

3 - 0 指定了哪个寄存器。 第3位指定了是直接寻址还是间接寻址（direct or indirect）

***  双操作数寻址模式


#+BEGIN_SRC ditaa :file assets/par-desc.png :cmdline -r :exports results

+-------------------------------------------------------------------------------+
|                   |              |              |              |              |
| 15 | 14 | 13 | 12 | 11 | 10 |  9 |  8 |  7 |  6 |  5 |  4 |  3 |  2 |  1 |  0 |
|                   |              |              |              |              |
|       OP CODE     |    MODE      |      Rn      |    MODE      |      Rn      |
+-------------------------------------------------------------------------------+

#+END_SRC


- ?? 双操作数难道只有 2^4 = 16个


***  symbols


#+CAPTION: PSW 处理器状态字各字段的含义
#+NAME:   tab:basic-data
| SYMBOLS   | meanning        |
|-----------+----------------------|
| ()        | consists of          |
| SS        | source address       |
| DD or dst | destination address  |
| loc       | locatiion            |
| ←         | becomes              |
| ↑         | is popped from stack |
| ↓         | is pushed onto stack |
| Reg or R  | register             |
| B         | Byte                 |

*** 单操作数寻址模式

#+BEGIN_SRC ditaa :file assets/par-desc.png :cmdline -r :exports results

+-------------------------------------------------------------------------------+
|                                                 |              |              |
| 15 | 14 | 13 | 12 | 11 | 10 |  9 |  8 |  7 |  6 |  5 |  4 |  3 |  2 |  1 |  0 |
|                                                 |              |              |
|             OP CODE                             |    MODE      |      Rn      |
+-------------------------------------------------------------------------------+

#+END_SRC

15 - 6位指定了是哪些操作

5 - 3 指定了寻址模式

3 - 0 指定了哪个寄存器。 第3位指定了是直接寻址还是间接寻址（direct or indirect）


** Two's complement 补码








** Two-pass assemblers

[[http://users.cis.fiu.edu/~downeyt/cop3402/two-pass.htm][tow-pass assemblers]]

An assembler is a translator, that translates an assembler program into a conventional machine language program. Basically, the assembler goes through the program one line at a time, and generates machine code for that instruction. Then the assembler procedes to the next instruction. In this way, the entire machine code program is created. For most instructions this process works fine, for example for instructions that only reference registers, the assembler can compute the machine code easily, since the assembler knows where the registers are.

Consider an assembler instruction like the following

          JMP  LATER
          ...
          ...
LATER:
This is known as a forward reference. If the assembler is processing the file one line at a time, then it doesn't know where LATER is when it first encounters the jump instruction. So, it doesn't know if the jump is a short jump, a near jump or a far jump. There is a large difference amongst these instructions. They are 2, 3, and 5 bytes long respectively. The assembler would have to guess how far away the instruction is in order to generate the correct instruction. If the assembler guesses wrong, then the addresses for all other labels later in the program woulds be wrong, and the code would have to be regenerated. Or, the assembler could alway choose the worst case. But this would mean generating inefficiency in the program, since all jumps would be considered far jumps and would be 5 bytes long, where actually most jumps are short jumps, which are only 2 bytes long.
Soooooooo, what is to be done to allow the assembler to generate the correct instruction? Answer: scan the code twice. The first time, just count how long the machine code instructions will be, just to find out the addresses of all the labels. Also, create a table that has a list of all the addresses and where they will be in the program. This table is known as the symbol table. On the second scan, generate the machine code, and use the symbol table to determine how far away jump labels are, and to generate the most efficient instruction.

This is known as a two-pass assembler. Each pass scans the program, the first pass generates the symbol table and the second pass generates the machine code. I have created a listing of an assembler program that has the machine code listed, and the symbol table listed.



Example Assembler Listing

Assembly listing with machine code

By counting the bytes generated, it is possible to see how the numbers in the symbol table were derived.

#+BEGIN_SRC C
                            DOSSEG
                            .MODEL    SMALL,C

                    DGROUP  GROUP     _DATA,STACK

 0000                    _DATA     SEGMENT   WORD PUBLIC    'DATA'
 0000  000A [            ARR  DB   10 DUP(?)
        00
       ]
 000A                    _DATA     ENDS

 0000                    STACK     SEGMENT   PARA STACK     'STACK'
 0000  0400 [                    DB   1024 DUP(?)
        00
       ]
 0400                    STACK     ENDS

 0000                    _TEXT     SEGMENT   WORD PUBLIC 'CODE'
                         ASSUME    CS:_TEXT,DS:DGROUP,SS:DGROUP

 0000  BA ---- R         START:  MOV       DX,DGROUP      ;SET UP DS REGISTER
 0003  8E DA                     MOV       DS,DX

                    ;READS AT MOST 10 CHARACTERS
                    ;WILL ACCEPT LESS IF ESC IS PRESSED
                                
 0005  B9 000A      MOV  CX,10
 0008  8D 1E 0000 R      LEA  BX,ARR
 000C  B4 01             MOV  AH,01H
 000E  CD 21        TOP: INT  21H
 0010  88 07             MOV  [BX],AL
 0012  3C 1B             CMP  AL,01BH
 0014  74 03             JZ   DONE
 0016  43           INC  BX  
 0017  E2 F5             LOOP TOP
 0019               DONE:                   
 0019  B8 4C00      MOV       AX,4C00H            ;TERMINATE PROGRAM
 001C  CD 21             INT       21H

 001E               _TEXT     ENDS
                              END       START
Symbol Table

                N a m e          	Type 	Value	Attr

ARR  . . . . . . . . . . . . . .   	Byte 	0000   _DATA   
DONE . . . . . . . . . . . . . .   	L Near	0019   _TEXT   
START  . . . . . . . . . . . . .   	L Near	0000   _TEXT   
TOP  . . . . . . . . . . . . . .   	L Near	000E   _TEXT   
#+END_SRC


** list of instructions

*** single operand

**** General




** double operand


** program control

*** Branch

*** signed Conditional Branch

*** Unsigned Conditional Branch

*** Jump & Subroutine


**** JSR

  jsr register, destination

有下面经常使用的方法：
#+BEGIN_SRC asm
#+END_SRC

指令的操作如下：
#+BEGIN_SRC asm
(temp)  <- (dst)

()
#+END_SRC



步骤：

  1. (tmp) ← (dst) (tmp is an internal processor register)

  1. ↓(SP) ← reg (push reg contents onto processor shck)

  1. reg ← PC (PC holds location following JSR; this address now put in reg)

  1. PC  ← (tmp) (PC now points to subroutine destination)

JSR RX, label

Rx的值被压入到栈，当前的PC被放到入reg之中，新的label被放入到PC

JSR PC, label 用法就比较特殊

旧PC的值压入到栈中，新的label被放入到PC



In execution of the JSR, the old contents of the specified register (the "LINKAGE POINTER") are automatically pushed onto the processor stack and new linkage information placed in the register. Thus subroutines nested within subroutines to any depth may all be called with the same linkage register. There is no need either to plan the maximum depth at which any particular subroutine will be called or to include instructions in each routine to save and restore the linkage pointer. Further, since all linkages are saved in a reentrant manner on the processor stack execution of a subroutine may be interrupted, the same subroutine reentered and executed by an interrupt service routine. Execution of the initial subroutine can then be resumed when other requests are satisfied. This process (called nesting) can proceed to any level.

JSR在执行时，指定寄存器内的内容（注：link pointer，函数调用后要回来的，所以要存一下）被放到栈上，新的跳转(linkage pointer)，新的linkage 信息被放到

A subroutine called with a JSR reg,dst instruction can access the arguments following the call with either autoincrement addressing, (reg)+, (if arguments are accessed sequentially) or by indexed addressing, X(reg), (if accessed in random order). These addressing modes may also be deferred,  @(reg)+ and @X(reg) if the parameters are operand ad¡dresses rather than the operands themselves.

JSR PC, dst is a special case of the PDP-11 subroutine call suitable for subroutine calls that transmit parameters through the general registers. The SP and the PC are the only registers that may be modified by this call.

Another special case of the JSR instruction is JSR PC, @(SP) + which exchanges the top element of the processor stack and the contents of the program counter. Use of this instruction allows two routines to swap program control and resume operation when recalled where they left off. Such rou¡tines are called "co-routines."

Return from a subroutine is done by the RTS instruction. RTS reg loads the contents of reg into the PC and pops the top element of the processor stack into the specified register.


*** Trap & Interrupt

**** RTI
return from interrupt 从中断中跳回

操作：从栈顶pop出PC和PS（leo 猜测：这个操作其实就是个理论上是双操作，但必须保证原子性，所以有一个操作）。

  1. PC <- (SP)↑

  1. PS <- (SP)↑



**** RTT

return from interrupt 从中断中跳回，与RTI一样

操作：从栈顶pop出PC和PS

  1. PC <- (SP)↑

  1. PS <- (SP)↑

RTI会保留着TRACE trap，而RTT则不会。


*** Miscellaneous

*** Condition Code


