* 布尔类型

https://stackoverflow.com/questions/2953646/how-can-i-declare-and-use-boolean-variables-in-a-shell-script

使用方式
#+BEGIN_SRC bash
bool=true

if [ "$bool" = true ]
#+END_SRC


** Issues with Miku's (original) answer

I do not recommend the accepted answer1. Its syntax is pretty, but it has some flaws.

Say we have the following condition.

#+BEGIN_SRC bash
if $var; then
  echo 'Muahahaha!'
fi
#+END_SRC

In the following cases2, this condition will evaluate to true and execute the nested command.

#+BEGIN_SRC bash
# Variable var not defined beforehand. Case 1
var=''  # Equivalent to var="".        Case 2
var=    #                              Case 3
unset var  #                           Case 4
var='<some valid command>'  #          Case 5
#+END_SRC

Typically you only want your condition to evaluate to true when your "Boolean" variable, var in this example, is explicitly set to true. All the others cases are dangerously misleading!

The last case (#5) is especially naughty because it will execute the command contained in the variable (which is why the condition evaluates to true for valid commands3, 4).

Here is a harmless example:

#+BEGIN_SRC bash
var='echo this text will be displayed when the condition is evaluated'
if $var; then
  echo 'Muahahaha!'
fi

# Outputs:
# this text will be displayed when the condition is evaluated
# Muahahaha!
#+END_SRC

Quoting your variables is safer, e.g. if "$var"; then. In the above cases, you should get a warning that the command is not found. But we can still do better (see my recommendations at the bottom).

Also see Mike Holt's explanation of Miku's original answer.

Issues with Hbar's answer
This approach also has unexpected behaviour.

#+BEGIN_SRC bash
var=false
if [ $var ]; then
  echo "This won't print, var is false!"
fi

# Outputs:
# This won't print, var is false!
#+END_SRC

You would expect the above condition to evaluate to false, thus never executing the nested statement. Surprise!

Quoting the value ("false"), quoting the variable ("$var"), or using test or [[ instead of [, do not make a difference.

What I do recommend:
Here are ways I recommend you check your "Booleans". They work as expected.

#+BEGIN_SRC bash
bool=true

if [ "$bool" = true ]; then
if [ "$bool" = "true" ]; then

if [[ "$bool" = true ]]; then
if [[ "$bool" = "true" ]]; then
if [[ "$bool" == true ]]; then
if [[ "$bool" == "true" ]]; then

if test "$bool" = true; then
if test "$bool" = "true"; then
#+END_SRC

They're all pretty much equivalent. You'll have to type a few more keystrokes than the approaches in the other answers5, but your code will be more defensive.
