* 线程


** 主要概念

  - 对进程进行改造，其中有线程的数组

*** 线程的实现

  1. 用户可动态创建、销毁、挂起、恢复、退出线程。

  1．每个进程启动时，至少有一个线程，那就是主线程（入口函数是main）。程序可以创建其他线程，当线程执行函数返回后，线程也就退出了。当所有线程都退出后，进程才会退出，但有一种情况例外，那就是主线程退出。一旦主线程退出，进程就退出了。

  1．每当线程退出时，它占用的用户栈会被释放，但分配的堆内存不会释放，这是由于当前内存分配时并没有线程记录（当然如果要加上也可以）。

  1. 每个线程都有自己的用户栈和内核栈，并且内核栈大小固定，不可调节；用户栈大小可由调用者在创建线程时设定，但线程运行期间也不可调节。

     - 当用户栈溢出时，MMU 不能检测到它并触发栈违例自陷。但内核会定期检查它（频率是60HZ），从而触发SIGSTK 信号。这样的实现是基于目前的虚存机制，如果采用页式虚存，则栈溢出监测和大小自动调节的实现会容易得多。而且PDP 11/40 只提供了SLR 寄存器来监测内核模式下的栈指针，对于用户模式下栈指针的监控，目前没有更好的手段。

  1．一个线程不仅可以挂起、恢复或终止本进程内线程；而且可以挂起、恢复或终止其他进程内线程，但必须有root（超级用户）权限。

  1．只有当进程内所有线程都处于挂起状态时，进程才被认为是挂起状态，否则处于运行状态。

  1．当进程换出后，其数据段被释放，其内所有线程均无法运行。

线程相关系统调用包括CreateThread、SuspendThread、ResumeThread、ExitThread 和 TerminateThread。


** 一个线程的实现

#+BEGIN_SRC C
struct proc
{
  char p_stat;
  char p_flag;
  char p_nice; /* nice for scheduling */
  char p_time; /* resendial time for scheduler */
  char p_sig;  /* signal number sent to this process */
  char p_uid;  /* user id, used to direct tty signals */
  int p_ttyp; /* controlling tty */
  int p_pid;  /* unique process id */
  int p_ppid; /* process id of parent */
  int p_addr; /* address of swappable image */
  int p_size; /* size of swappable image (*64 bytes) */
  int *p_textp;/* pointer to text structure */
  struct Thread *p_threads[NTHREAD_PROC];
  int p_threadNum;	//总线程数
  int p_actThreadNum; //运行着的线程数
  int *p_thdsysentry; /* pointer to sys entry ThreadSysEntry*/
  struct MsgQueue msgQue;
  struct  SharedMemory  *p_shm[MEM_MAP_COUNT_PROC];
  struct MemMap *p_mmap[MEM_MAP_COUNT_PROC];
} proc[NPROC];
#+END_SRC C

*** 与v6的 proc.h 的比较

  - 多个 p_threads 这个数组

  - 少了p_chan，线程才会在某个资源上挂起


#+BEGIN_SRC C
struct Thread
{
  char t_stat;
  char t_flag;
  char t_pri;  /* priority, negative is high */
  char t_time; /* resident time for scheduling */
  char t_cpu;  /* cpu usage for scheduling */
  char t_nice; /* nice for scheduling */
  int t_tid;  /* unique thread id */
  int t_ttyp; /* controlling tty */
  int t_index; /* internal index from 0 to NTHREAD_PROC-1 */
  int t_pid; /* process id of parent */
  int t_ustackaddr; /* address of stack in userspace */
  int t_ustacksize; /* size of userstack (*64 bytes) */
  int t_wchan;/* event thread is awaiting */
  char t_name[12];
  ThreadProc t_entry;/* pointer to user entry */
  int *t_param; /* param passed to thread proc */
  struct proc *t_proc; /*parent process pointer */
}Threads[NTHREAD];

/*
 * 线程上下文
 */
struct U_Thread
{
  int u_rsav[2];    /* save r5,r6 when exchanging stacks */
  int u_fsav[25];   /* save fp registers */
/* rsav and fsav must be first in structure */
  char u_segflg;    /* flag for IO; user or kernel space */
  char u_error;     /* return error code */
  char u_uid;/* effective user id */
  char u_gid;/* effective group id */
  char u_ruid;/* real user id */
  char u_rgid;/* real group id */
  int u_threadp;/* pointer to Thread structure */
  char *u_base;     /* base address for IO */
  char *u_count;    /* bytes remaining for IO */ //read/write to/from u_base
  char *u_offset[2];/* offset in file for IO */
  int *u_cdir; /* pointer to inode for current directory */
  char u_dbuf[DIRSIZ];/* current pathname component */
  char *u_dirp;     /* current pointer to inode */
  struct     {/* current directory entry */
    int	  u_ino;		//the directory u_name's inode number in the disk.
    char     u_name[DIRSIZ];
  } u_dent;
  int *u_pdir;/* inode of parent directory of dirp */
  int u_ofile[NOFILE]; /* pointers to file structures of open files */
  int u_arg[5];     /* arguments to current system call */

  int u_qsav[2];  /* label variable for quits & interrupts */
  int u_ssav[2];    /* label variable for swapping */
  int u_utime;/* this process user time */
  int u_stime;/* this process system time */
  int u_cutime[2];  /* sum of childs’ utimes */
  int u_cstime[2];  /* sum of childs’ stimes */
  int *u_ar0;/* address of users saved R0 */
  int u_prof[4];    /* profile arguments */
  char u_intflg;    /* catch intr from sys */
  char u_pad;
  char u_kernstack[802]; // 每个线程的内核栈
};

/*
 * 进程u变量，其总大小大约4K, 位于内核虚拟地址[0o140000, 0o150000]。
 */
struct
{
  // 所有线程的“u变量”
  struct U_Thread u_threads[NTHREADS_PROC];

  //signal是进程级的，但处理过程运行在线程上下文中
  int u_signal[NSIG];/* disposition of signals */

  //新创建线程默认的u/gid
  char u_uid;/* effective user id */
  char u_gid;/* effective group id */
  char u_ruid;/* real user id */
  char u_rgid;/* real group id */

  int u_uisa[16];   /* prototype segmentation addresses */
  int u_uisd[16];   /* prototype segmentation descriptors */
  int u_tsize;/* text size (*64) */
  int u_dsize;/* data size (*64) */
  int u_ssize;/* stack size (*64) */

//线程栈分配记录，为了提高效率，可采用链表实现。这里简单起见，采用数组。
  struct map u_stackmap[NTHREAD_PROC];
  int u_sep;/* flag for I and D separation */

  int u_osema [4];	//  记录信号量打开的句柄数组：
  int u_rsema[4];	//以及已经获得的信号量个数
  int u_oevent[MAX_EVENTS_PROC];
  int u_ombx[MBX_COUNT_PROC];

  struct proc *u_procp;

  int u_curthd;	//Index for current thread structure in u_threads
} u;
#+END_SRC C


*** 创新线程

**** 用户实现 CreateThread

用户实现的创建线程

  - ThreadProc entry 线程的入口函数 （非常重要）

#+BEGIN_SRC C
#int CreateThread(char *name, int iPriority, int iStatus, ThreadProc entry, int *pParam, int iStackSize)
#{
.globl _CreateThread
.globl _ThreadSysEntry
_CreateThread:
        mov	r5,-(sp)
        mov	sp,r5
        mov	4(r5),0f
        mov	6(r5),0f+2
        mov	8(r5),0f+4
        mov	10(r5),0f+6
        mov	12(r5),0f+8
        mov	12(r5),0f+10

        #把ThreadSysEntry作为附加参数传入给内核实现，这样线程首次执行时会调用它
        mov _ThreadSysEntry, 0f+12
        sys	0; 9f
        bec	1f
        jmp	cerror
1:
        mov	(sp)+,r5
        rts	pc
9:
        sys 73; 0:	..;..;..;..;..;..;..
#}
#+END_SRC C

**** ThreadSysEntry

在 =用户实现的CreateThread= 被作为参数，传递给 =内核实现的CreateThread=

#+BEGIN_SRC C
// 系统线程入口，它的主要作用是调用用户线程入口函数，并在函数返回后调用
// ExitThread退出线程。
void ThreadSysEntry(ThreadProc UserEntry, int *pParam)
{
        int exitCode = (*UserEntry)(pParam);
        ExitThread(exitCode);
}
#+END_SRC C

#+BEGIN_SRC C
/*
 * 系统调用CreateThread的内核实现
 */
void CreateThread()
{
        char name[12];
        register Thread *thread;
        register int id;
        register U_Thread *uthd = &u.u_threads[u.u_curthu];  // 当前线程的上下文
        char *stack;

        if(u.u_procp->p_threadNum == NTHREAD_PROC)   // 超过最大线程数
        {
                uthd->u_error = ENOTHDSPC;
                return;
        }

        //获得线程名称，getname见10.7.2.1.2节
        if(getname(name, 12))
                return;
        if(threadexist(name) != NULL) //该名称线程已存在
        {
                uthd->u_error = EEXIST;
                return;
        }

        if((id=threadalloc()) == -1) // 新建线程
        {
                return;
        }

        thread = &Threads[id];
        if(thread->t_index = thpalloc(u.u_procp) == -1)
        {
                return;
        }

        //分配用户栈空间
        stack = AllocStack(uthd->u_arg[5]);
        if(stack == NULL)
        {
                uthd->u_error = ENOSPC;
                return;
        }
        thread->t_ustackaddr = stack;
        thread->t_ustacksize = uthd->u_arg[5];
        u.u_procp->p_threads[thread->t_index] = thread;
        strcpy(thread->t_name, name);

        thread->t_pri = uthd->u_arg[1];		//用户程序传递的iPriority参数
                thread->t_cpu = 0;
        thread->t_time = 0;
        thread->t_nice = u.u_procp->t_nice;
        thread->t_ttyp = u.u_procp->p_ttyp;

        //从进程继承uid、gid等
        u.u_threads[thread->t_index].u_uid = u.u_uid;
        u.u_threads[thread->t_index].u_gid = u.u_gid;
        u.u_threads[thread->t_index].u_ruid = u.u_ruid;
        u.u_threads[thread->t_index].u_rgid = u.u_rgid;

        if(u.u_threads[u.u_curthu].u_arg[2] == THREAD_RUN)
        {
                thread->t_stat = SRUN;
                ++u.u_procp->p_actThreadNum;
                rp->p_stat = SRUN;
            if(thread->t_pri < curpri)	//新创建线程优先级更高，则设置调度标志
                runrun++;
        }
        else
        {
                        spl6();
                thread->t_wchan = &thread->t_tid;
                thread->t_stat = SSLEEP;
                thread->t_pri = SUSPPRI;
        }

        thread->t_flag = SLOAD;

        //为了避免t_tid值固定
        if((thread->t_tid % NTHREAD) == id)
                thread->t_tid += NTHREAD;
        else
                thread->t_tid = id;
        if(thread->t_tid < 0)
                thread->t_tid = id;

        thread->t_pid = u.u_procp->p_pid;
        thread->t_proc = u.u_procp;
        thread->t_entry = uthd->u.u_arg[3];
        thread->t_param = uthd->u_arg[4];
        u.u_procp->p_thdsysentry = uthd->u_arg[6];

        //搭建内核栈，为首次执行做准备
        u.u_threads[thread->t_index].u_threadp = thread;
        SetupKernStack(&u.u_threads[thread->t_index]);

        //设置r6和r5的值
        u.u_threads[thread->t_index].u_rsav[0] =
                        &u.u_threads[thread->t_index].u_kernstack[790];
        u.u_threads[thread->t_index].u_rsav[1] =
        &u.u_threads[thread->t_index].u_kernstack[798];

        uthd->u_ar0[R0] = thread->t_tid;//返回线程ID
        return;
}
#+END_SRC C



* 线程

  这里记录一下自己关于线程的遐想。

  - 发现问题比解决问题更重要。

  - 思考模式比解决结果更重要。

  - 答案中忽略的部分比想到的部分更重要，计算机中严谨是关键的概念

** 线程解决了什么问题，为什么存在?

   1. 有需要任务分解，有需要共享数据的场景

** 我来实现线程时会怎么做？


*** 哪些点？

  1. 思路：

      1. 借鉴v6进程的实现

      1. 线程也有类似的user结构体

  1. 如何切换

  1. 优先级

  1. 如果共享数据

  1. 如何修改数据，如何防止数据污染

  1. 线程可以嵌套么？

*** 模式一

怎么入手？

  1. 定义线程的数据结构

    - 执行时间 （用于）



** 常见的线程处理不当是哪些？编程时需要注意哪些问题？
