* futex

  http://blog.foool.net/2021/04/futex-%E7%BB%BC%E8%BF%B0/

** 简介

futex 全称为 ~Fast User-space Mutex~ ，是Linux 2.5.7 内核引入的锁原语。

不同于其他进程间通信IPC原语（如信号量Semaphore、信号Signal和各种锁pthread_mutex_lock），futex更轻量级、快速，一般应用开发人员可能很少用到，但可基于futex实现各类读写锁、屏障（barriers）和信号机制等。

** 相关背景

在Linux的早期版本（内核Linux 2.5.7 版本以前），进程间通信（Inter-Process Communication，IPC）沿用的是传统Unix系统和System V 的IPC，如信号量（Semaphores）和Socket 等，这些IPC 均基于系统调用（System Call）。这类方法的缺点是当系统竞争度较低时，每次都进行系统调用，会造成较大系统开销。

** 原理和做法

用户程序每次调用IPC机制都会产生系统调用，程序发生用户态和内核态的切换，futex 的基本思想是竞争态总是很少发生的，只有在竞争态才需要进入内核，否则在用户态即可完成。futex的两个目标是：1）尽量避免系统调用；2）避免不必要的上下文切换（导致的TLB失效等）。

具体而言，任务获取一个futex 将发起带锁的减指令，并验证数值结果值是否为0（加上了锁），如果成功则可继续执行程序，失败（为已经占用的锁继续加锁）则任务在内核被阻塞。为相同futex 变量的加锁的任务被阻塞后放在同一个队列，解锁任务通过减少变量（只有一个加锁且锁队列为空）或进入内核从锁队列唤醒任务。

注意：futex 在Linux 的内核实现为一个系统调用（SYS_futex），用户程序如果直接调用它肯定会进入内核态，它还需要和其他语句（如原子操作）配合使用，新手在未理解其futex 原理和并发控制机制时极易犯错，这也是为什么不推荐直接使用它的原因。


本节介绍的futex 基于Linux 2.5.7内核版本，和最新的futex 在实现上原理基本相同，但实现更为简单（代码更少）。

Futex 本质上是希望实现一个用户态的高性能锁。锁（Lock）是实现进程同步的最基本方法，锁可以实现为多个任务共享的一块内存（由mmap() 和shmat() 分配 ）。如果用一个ulock_t 类型代表用户锁，那么它至少包含一个状态字：

#+BEGIN_SRC c
typedef struct ulock_t {
    long status;
} ulock_t;
#+END_SRC

锁至少包含两个状态（status），可以用整数表示：

#+BEGIN_SRC c
status == 1    // 无锁
status != 1   // 有锁
#+END_SRC

这样，就可以定义两个基本操作usema_up() 和usema_down() ，实现解锁和加锁（注意下面代码是用户态的）。

#+BEGIN_SRC c
static inline int usema_down(ulock_t *ulock)
{
    if (!__ulock_down(ulock))
        return 0;
    return futex_down(ulock);                 // system call
}

static inline int usema_up(ulock_t *ulock)
{
    if (!__ulock_up(ulock))
        return 0;
    return futex_up(ulock);                  // system call
}
#+END_SRC

其中，__ulock_down(ulock) 和__ulock_up(ulock) 是用户态的原子性操作（类似于atomic_compare_exchange_strong() 、__sync_fetch_and_add() 和__sync_add_and_fetch() 等），实现对ulock 的值的修改，如果不成功则通过系统调用futex_down() 或futex_up() 进入内核。内核中futex_down() 和futex_up() 基本功能如下

futex_down() ：将status 减1（status 由1 变为0 ，代表程序其占有锁；如果status 由0 变为-1，代表程序等待）。
futex_up() ：将status 设置为1（即解锁）。
