* 常见问题

** gcc 与 g++ 之间有什么区别


gcc and g++ are compiler-drivers of the 'Gnu Compiler Collection' (which was once upon a time just the 'Gnu C Compiler').

Even though they automatically determine which backends (cc1 cc1plus ...) to call depending on the file-type, unless overridden with -x language, they have some differences.

The probably most important difference in their defaults is which libraries they link against automatically.

According to GCC's online documentation link options and how g++ is invoked, =g++= is equivalent to  =gcc -xc++ -lstdc++ -shared-libgcc= (the 1st is a compiler option, the 2nd two are linker options). This can be checked by running both with the -v option (it displays the backend toolchain commands being run).

g++ 可以完成编译阶段

看下面一段程序 =helloworld.cpp=
#+BEGIN_SRC cpp
#include <iostream>

using namespace std;

int main()
{
  cout << "Hello, world!" << endl;
  return 0;
}
#+END_SRC

指定使用的共享库，可以正常编译
#+BEGIN_SRC sh
gcc -xc++ -lstdc++ -shared-libgcc helloworld.cpp
#+END_SRC


而直接对cpp文件进行gcc编译，会有问题
#+BEGIN_SRC sh
gcc helloworld.cpp

;; 出现了一系列的报错信息
/tmp/ccifYexQ.o: In function `main':
helloworld.cpp:(.text+0xa): undefined reference to `std::cout'
helloworld.cpp:(.text+0xf): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)'
helloworld.cpp:(.text+0x14): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::endl<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&)'
helloworld.cpp:(.text+0x1c): undefined reference to `std::ostream::operator<<(std::ostream& (*)(std::ostream&))'
/tmp/ccifYexQ.o: In function `__static_initialization_and_destruction_0(int, int)':
helloworld.cpp:(.text+0x4a): undefined reference to `std::ios_base::Init::Init()'
helloworld.cpp:(.text+0x59): undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status
#+END_SRC

下面分步来探讨

1. 预处理阶段
正常通过
#+BEGIN_SRC sh
gcc -E helloworld.cpp -o helloworld.i
#+END_SRC

2. 编译阶段
出错
#+BEGIN_SRC sh
gcc -S helloworld.i -o helloworld.s
#+END_SRC

3. 汇编阶段


