* Sysfs

Sysfs  是Linux2.6所提供的一种虚拟文件系统。这个文件系统不仅可以把设备（devices）和驱动程序（drivers）的信息从内核输出到用户空间，也可以用来对设备和驱动程序做设置。

** 历史

引用自https://zh.wikipedia.org/zh-cn/Sysfs

Linux内核开发团队在Linux 2.5的开发过程中引入了“Linux驱动程序模型”（Linux driver model），以解决2.4核心遭遇的以下问题：

1. 没有统一的机制表达驱动程序和设备的关系。

1. 不存在一般的热插拔（hotplug）机制。

1. procfs文件系统过度混乱，包含了许多不是行程（process）的信息。

sysfs的目的是把一些原本在procfs中的，关于设备的部分，独立出来，以‘设备层次结构架构’（device tree）的形式呈现。这个文件系统由Patrick Mochel所写，之后Maneesh Soni撰写“sysfs backing store path”，以降低在大型系统中对存储器的需求量。

sysfs一开始ramfs为基础，也是一个只存在于存储器中的文件系统。ramfs是在2.4核心处于稳定阶段时加入的。ramfs是一个优雅的实现，证明了要在当时仍很新的虚拟文件系统下写一个简单的文件系统是多么容易的一件事。由于ramfs的简洁以及使用了VFS，稍后的一些存储器形式的文件系统都以它作为开发基础。

sysfs刚开始被命名成ddfs(Device Driver Filesystem)，当初只是为了要对新的驱动程序模型调试而开发出来的。它在调试时，会把设备架构（device tree）的信息输出到procfs文件系统中。但在Linus Torvalds的急切督促下，ddfs被转型成一个以ramfs为基础的文件系统。在新的驱动程序模型被集成进2.5.1核心时，ddfs被改名成driverfs，以更确切描述它的用途。

在2.5核心开发的次年，新的“驱动程序模型”和"driverfs"证明了对核心中的其他子系统也有用处。kobjects被开发出来，作为核心对象的中央管理机制，而此时driverfs也被改名成sysfs。

编译为外部模块(ko文件)在加载后会出现对应的/sys/module/<module_name>/，并且在这个目录下会出现一些属性文件和属性目录来表示此外部模块的一些信息，如版本号、加载状态、所提供的驱动程序等；
编译为内联方式的模块则只在当它有非0属性的模块参数时会出现对应的/sys/module/<module_name>，这些模块的可用参数会出现在/sys/modules/<modname>/parameters/<param_name> 中，
如/sys/module/printk/parameters/time这个可读写参数控制着内联模块printk在打印内核消息时是否加上时间前缀；
所有内联模块的参数也可以由"<module_name>.<param_name>=<value>"的形式写在内核启动参数上，如启动内核时加上参数"printk.time=1"与向"/sys/module/printk/parameters/time"写入1的效果相同；
没有非0属性参数的内联模块不会出现于此。
/sys/power

这里是系统中电源选项，这个目录下有几个属性文件可以用于控制整个机器的电源状态，如可以向其中写入控制命令让机器关机、重启等。



1. /sys/devices 这是内核对系统中所有设备的分层次表达模型，也是/sys文件系统管理设备的最重要的目录结构；

1. /sys/dev 这个目录下维护一个按字符设备和块设备的主次号码(major:minor)链接到真实的设备(/sys/devices下)的符号链接文件；

1. /sys/bus 这是内核设备按总线类型分层放置的目录结构， devices 中的所有设备都是连接于某种总线之下，在这里的每一种具体总线之下可以找到每一个具体设备的符号链接，它也是构成 Linux 统一设备模型的一部分；

1. /sys/class 这是按照设备功能分类的设备模型，如系统所有输入设备都会出现在/sys/class/input 之下，而不论它们是以何种总线连接到系统。它也是构成 Linux 统一设备模型的一部分；

1. /sys/kernel 这里是内核所有可调整参数的位置，目前只有 uevent_helper, kexec_loaded, mm, 和新式的slab 分配器等几项较新的设计在使用它，其它内核可调整参数仍然位于sysctl(/proc/sys/kernel) 接口中；

1. /sys/module 这里有系统中所有模块的信息，不论这些模块是以内联(inlined)方式编译到内核映像文件(vmlinuz)中还是编译为外部模块(ko文件)，都可能会出现在/sys/module 中：
