* http缓存相关属性


** http 1.0 时期的缓存方案

如果使用了Pragma: 'no-cache'的话，再设置Expires或者Cache-Control，就没有用了，说明Pragma的权值比后两者高。

Expires之后，客户端在需要请求数据的时候，首先会对比当前系统时间和这个Expires时间，如果没有超过Expires时间，则直接读取本地磁盘中的缓存数据，不发送请求。

*** Expires

Expires的值为服务端返回的到期时间，即下一次请求时，请求时间小于服务端返回的到期时间，直接使用缓存数据。

不过Expires 是HTTP 1.0的东西，现在默认浏览器均默认使用HTTP 1.1，所以它的作用 ~基本忽略~ 。

另一个问题是，到期时间是由服务端生成的，但是客户端时间可能跟服务端时间有误差，这就会导致缓存命中的误差。所以HTTP 1.1 的版本，使用Cache-Control替代。

** http 1.1 缓存方案

*** Cache-Control

Cache-Control 是最重要的规则。

常见的取值有private、public、no-cache、max-age，no-store，默认为private。




**** Cache request directives 在request 中的值


Standard Cache-Control directives that can be used by the client in an HTTP request.

#+BEGIN_SRC http
Cache-Control: max-age=<seconds>
Cache-Control: max-stale[=<seconds>]
Cache-Control: min-fresh=<seconds>
Cache-Control: no-cache
Cache-Control: no-store
Cache-Control: no-transform
Cache-Control: only-if-cached
#+END_SRC


**** Cache response directives

Standard Cache-Control directives that can be used by the server in an HTTP response.

#+BEGIN_SRC http
Cache-Control: must-revalidate
Cache-Control: no-cache
Cache-Control: no-store
Cache-Control: no-transform
Cache-Control: public
Cache-Control: private
Cache-Control: proxy-revalidate
Cache-Control: max-age=<seconds>
Cache-Control: s-maxage=<seconds>
#+END_SRC

**** Extension Cache-Control directives


Extension Cache-Control directives are not part of the core HTTP caching standards document. Check the compatibility table for their support; user-agents that don't recognize them should ignore them.

#+BEGIN_SRC http
Cache-Control: immutable
Cache-Control: stale-while-revalidate=<seconds>
Cache-Control: stale-if-error=<seconds>
#+END_SRC



**** response 中的值

1. public

The response may be stored by any cache, even if the response is normally non-cacheable.

任何情况下都可以缓存该资源

1.  private

The response may be stored only by a browser's cache, even if the response is normally non-cacheable.

If you mean to not store the response in any cache, use no-store instead. This directive is not effective in preventing caches from storing your response.

返回请求仅被某一个浏览器缓存，即便这个资源是non-cacheable的。

如果不想缓存任何资源，使用no-store

1. no-cache

The response may be stored by any cache, even if the response is normally non-cacheable. However, the stored response MUST always go through validation with the origin server first before using it, therefore, you cannot use no-cache in-conjunction with immutable. If you mean to not store the response in any cache, use no-store instead. This directive is not effective in preventing caches from storing your response.

需要使用对比缓存来验证缓存数据。

被存储的 response 需要在每次使用之前验证一下，不能与 ~immutable~ 一起使用。

1. no-store

不作缓存.


****  request 中的值

1. no-cache

使用no-cache指令的目的是为了防止从缓存中返回过期的资源。 客户端发送的请求中如果包含 no-cache指令，则表示客户端将不会接收缓存的资源。每次请求都是从服务器获取资源，返回304。

1. no-store


使用no-store 指令表示请求的资源不会被缓存，下次任何其它请求获取该资源，还是会从服务器获取，返回 200，即资源本身。


1. https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html

1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
