** 容器(Container)

[关于 Docker 进程隔离的基础](http://etherealmind.com/basics-docker-containers-hypervisors-coreos/)。容器 (Container) 之于虚拟机 (Virtual Machine) 就好比线程之于进程。

** 生命周期

  - create 创建容器但不启动它

  - rename 用于重命名容器

  - run 一键创建并同时启动该容器

  - rm 删除容器

  - update 调整容器的资源限制

通常情况下，不使用任何命令行选项启动一个容器，该容器将会立即启动并停止。

若需保持其运行，你可以使用 =docker run -td container_id= 命令。选项 =-t= 表示分配一个 pseudo-TTY 会话， =-d= 表示自动将容器与终端分离（也就是说在后台运行容器，并输出容器 ID）。

如果你需要一个临时容器，可使用 =docker run --rm= 会在容器停止之后删除它。

如果你需要映射宿主机 (host) 的目录到 Docker 容器内，可使用 =docker run -v $HOSTDIR:$DOCKERDIR= 。详见 [卷标(Volumes)](#卷标volumes) 一节。

如果你想同时删除与容器相关联的卷标，那么在删除容器的时候必须包含 =-v= 选项，像这样 =docker rm -v=。

从 Docker 1.10 起，其内置一套各容器独立的 [日志引擎](https://docs.docker.com/engine/admin/logging/overview/)，每个容器可以独立使用。你可以使用 =docker run --log-driver=syslog= 来自定义日志引擎（例如以上的 =syslog=）。

** 启动和停止


- [=docker start=](https://docs.docker.com/engine/reference/commandline/start) 启动已存在的容器。

- [=docker stop=](https://docs.docker.com/engine/reference/commandline/stop) 停止运行中的容器。

- [=docker restart=](https://docs.docker.com/engine/reference/commandline/restart) 重启容器。

- [=docker pause=](https://docs.docker.com/engine/reference/commandline/pause/) 暂停运行中的容器，将其「冻结」在当前状态。

- [=docker unpause=](https://docs.docker.com/engine/reference/commandline/unpause/) 结束容器暂停状态。

- [=docker wait=](https://docs.docker.com/engine/reference/commandline/wait) 阻塞地等待某个运行中的容器直到停止。

- [=docker kill=](https://docs.docker.com/engine/reference/commandline/kill) 向运行中的容器发送 SIGKILL 指令。

- [=docker attach=](https://docs.docker.com/engine/reference/commandline/attach) 连接到运行中的容器。

如果你想将容器的端口 (ports) 暴露至宿主机，请见 [暴露端口](#暴露端口exposing-ports) 一节。

关于 Docker 实例崩溃后的重启策略，详见 [本文](http://container42.com/2014/09/30/docker-restart-policies/)。

#### CPU 限制

你可以限制 CPU 资源占用，无论是指定百分比，或是特定核心数。

例如，你可以设置 [=cpu-shares=](https://docs.docker.com/engine/reference/run/#/cpu-share-constraint)。该配置看起来有点奇怪 -- 1024 表示 100% CPU，因此如果你希望容器使用所有 CPU 内核的 50%，应将其设置为 512：

===
docker run -ti --c 512 agileek/cpuset-test
===

更多信息请参阅 <https://goldmann.pl/blog/2014/09/11/resource-management-in-docker/#_cpu>。

通过 [=cpuset-cpus=](https://docs.docker.com/engine/reference/run/#/cpuset-constraint) 可使用特定 CPU 内核。

===
docker run -ti --cpuset-cpus=0,4,6 agileek/cpuset-test
===

请参阅 <https://agileek.github.io/docker/2014/08/06/docker-cpuset/> 获取更多细节以及一些不错的视频。

注意，Docker 在容器内仍然能够 **看到** 全部 CPU -- 它仅仅是不使用全部而已。请参阅 <https://github.com/docker/docker/issues/20770> 获取更多细节。

#### 内存限制

同样，亦可给 Docker 设置 [内存限制](https://docs.docker.com/engine/reference/run/#/user-memory-constraints)：

===
docker run -it -m 300M ubuntu:14.04 /bin/bash
===

#### 能力(Capabilities)

Linux 的 Capability 可以通过使用 =cap-add= 和 =cap-drop= 设置。请参阅 <https://docs.docker.com/engine/reference/run/#/runtime-privilege-and-linux-capabilities> 获取更多细节。这有助于提高安全性。

如需要挂载基于 FUSE 的文件系统，你需要结合 =--cap-add= 和 =--device= 使用：

===
docker run --rm -it --cap-add SYS_ADMIN --device /dev/fuse sshfs
===

授予对某个设备的访问权限：

===
docker run -it --device=/dev/ttyUSB0 debian bash
===

授予对所有设备的访问权限：

===
docker run -it --privileged -v /dev/bus/usb:/dev/bus/usb debian bash
===

有关容器特权的更多信息请参阅 [本文](https://docs.docker.com/engine/reference/run/#/runtime-privilege-and-linux-capabilities)。

### 信息

* [=docker ps=](https://docs.docker.com/engine/reference/commandline/ps) 查看运行中的所有容器。
* [=docker logs=](https://docs.docker.com/engine/reference/commandline/logs) 从容器中读取日志。（你也可以使用自定义日志驱动，不过在 1.10 中，它只支持 =json-file= 和 =journald=）。
* [=docker inspect=](https://docs.docker.com/engine/reference/commandline/inspect) 查看某个容器的所有信息（包括 IP 地址）。
* [=docker events=](https://docs.docker.com/engine/reference/commandline/events) 从容器中获取事件 (events)。
* [=docker port=](https://docs.docker.com/engine/reference/commandline/port) 查看容器的公开端口。
* [=docker top=](https://docs.docker.com/engine/reference/commandline/top) 查看容器中活动进程。
* [=docker stats=](https://docs.docker.com/engine/reference/commandline/stats) 查看容器的资源使用量统计信息。
* [=docker diff=](https://docs.docker.com/engine/reference/commandline/diff) 查看容器文件系统中存在改动的文件。

=docker ps -a= 将显示所有容器，包括运行中和已停止的。

=docker stats --all= 同样将显示所有容器，默认仅显示运行中的容器。

### 导入 / 导出

* [=docker cp=](https://docs.docker.com/engine/reference/commandline/cp) 在容器和本地文件系统之间复制文件或目录。
* [=docker export=](https://docs.docker.com/engine/reference/commandline/export) 将容器的文件系统打包为归档文件流 (tarball archive stream) 并输出至标准输出 (STDOUT)。

### 执行命令

* [=docker exec=](https://docs.docker.com/engine/reference/commandline/exec) 在容器内执行命令。

例如，进入正在运行的 =foo= 容器，并连接 (attach) 到一个新的 Shell 进程： =docker exec -it foo /bin/bash= 。
