* 高级IO

** Introduction



** Nonblocking I/O

1.同步 & 异步

- 同步异步是针对应用程序和内核的交互而言的。

  同步指的是用户进程触发IO操作，等待/轮询的去查看IO操作是否完成。同步阻塞IO是等待，同步非阻塞是轮询

  异步指的是用户进程出发IO操作便开始做别的事，IO操作已经完成的时候会得到IO完成的通知。

2.阻塞非阻塞概念

- 阻塞非阻塞是针对于进程在访问数据的时候，根据IO操作的就绪状态采用的不同操作方式。

- 阻塞状态下，读取/写入函数将一直等待IO操作就绪。

- 非阻塞状态下，读取/写入函数会立即返回一个状态值。

*** 程序清单

**** 程序清单14-1 exitstatus.c

演示了轮询方式的非阻塞，效率较差。

** Record Locking 记录锁

https://en.wikipedia.org/wiki/Record_locking

Record 这个术语有歧义，因为底层无 Recode, byte-range locking

fcntl  -- file control

#+BEGIN_SRC C
int fcntl(int fd, int cmd, ... /* arg */ );
#+END_SRC


1. 历史



***  建议性锁和强制性锁


建议性锁flock，不具备强制性。一个进程使用flock将文件锁住，另一个进程可以直接操作正在被锁的文件，修改文件中的数据。内核和系统总体上都坚持不使用建议性锁，它们依靠程序员遵守这个规定。

flock只是用于检测文件是否被加锁，针对文件已经被加锁，另一个进程写入数据的情况，内核不会阻止这个进程的写入操作，也就是建议性锁的内核处理策略。

flock主要三种操作类型：

- LOCK_SH，共享锁，多个进程可以使用同一把锁，常被用作读共享锁；
- LOCK_EX，排他锁，同时只允许一个进程使用，常被用作写锁；
- LOCK_UN，释放锁；

进程使用flock尝试锁文件时，如果文件已经被其他进程锁住，进程会被阻塞直到锁被释放掉，或者在调用flock的时候，采用LOCK_NB参数，在尝试锁住该文件的时候，发现已经被其他服务锁住，会返回错误，errno错误码为EWOULDBLOCK。即提供两种工作模式：阻塞与非阻塞类型。


建议性锁的限制
只能对整个文件进行加锁。这种粗粒度的加锁会限制协作进程间的并发。假如存在多个进程，其中各个进程都想同时访问同一个文件的不同部分。




** STREAMS

system V的机制

https://en.wikipedia.org/wiki/STREAMS

** I/O Multiplexing

** Asynchronous I/O

** readv and writev Functions

** readn and writen Functions

** Memory-Mapped I/O
