* 类

** 接口和实现

Objective-C的类分为接口定义和实现两个部分。

1. 接口定义（Interface）放在头文件中，文件扩展名是.h

1. 实现（implementation）放在实现文件中，文件扩展名是.m（也有.mm的扩展名，表示Objective-C和C++混编的代码）。

#+BEGIN_COMMENT
接口定义也可以写在.m文件中，但最好不要这么干
#+END_COMMENT

需要注意的是，与Objective-C的interface概念最接近的是C和C++里的头文件，它与implementation是成双成对出现的，作用是声明类的成员变量和方法。它与Java的interface概念完全不同：

- Objective-C里，interface有且只有一个实现，Java的interface可以有0-N个实现

- Objective-C里，interface可以定义成员属性，Java里不可以

在Objective-C里，和Java的Interface概念相似的是Protocol，下文会讲到。

请看示例：

#+BEGIN_SRC C
  // Interface
  @interface MyClass {
    int memberVar1;
    id  memberVar2;
  }

  -(return_type) instance_method1;
  -(return_type) instance_method2: (int) p1;
  -(return_type) instance_method3: (int) p1 andPar: (int) p2;
  @end
#+END_SRC

#+BEGIN_SRC C
  //Implementation

  @implementation MyClass {
    int memberVar3;
  }

  -(return_type) instance_method1 {
    //....
  }
  -(return_type) instance_method2: (int) p1 {
    //....
  }
  -(return_type) instance_method3: (int) p1 andPar: (int) p2 {
    //....
  }
  @end
#+END_SRC

接口和实现以@interface、@implementation开头，都以@end结束。“@”符号在Objective-C中是个很神奇的符号。

冒号也是方法名的一部分，method和method:是两个不同的方法名，不是overload，第二个带参数。

上述代码对应的Java版：

        public class MyClass {
                protected int memberVar1;
                protected pointer memberVar2;
                private int memberVar3;

                public (return_type) instance_method1() {
                        ....
                }

                public (return_type) instance_method2(int p1) {
                        ....
                }

                public (return_type) instance_method3andPar(int p1, int p2) {
                        ....
                }
        }

#### 私有方法和公开方法

写在.h头文件里的方法都是公开的，Objective-C里 _没有私有方法的概念_ 。

官方并没有提到Objective-C怎么实现私有方法，我查阅了stackoverflow，统一的答案是，要实现私有方法的效果只能借助Category，不过，根据我的测试，即使采用了Category，也不能阻止外部的代码调用这个“私有方法”，只是Xcode不支持“私有方法”的自动完成，并会有警告提示，运行的时候，还是会成功的。各位看官知道有这么回事就可以了，这里不深讲。

#### 变量和属性

#### 类方法和实例方法
##### 类方法
类方法就是Java、PHP里的Static Method，不用实例化就能调。类方法有一个加号前缀。
示例：

类定义

        @interface MyClass
                +(void) sayHello;
        @end

        @implementation MyClass

        +(void) sayHello {
        NSLog(@"Hello, World");
        }
        @end

使用

        [MyClass sayHello];

##### 实例方法
实例方法就是Java、PHP里的普通方法，必须实例化才能调。实例方法有一个减号前缀。
示例：

类定义

        @interface MyClass : NSObject
        -(void) sayHello;
        @end

        @implementation MyClass

        -(void) sayHello {
        NSLog(@"Hello, World");
        }
        @end

使用

        mycls = [MyClass new];
        [mycls sayHello];

#### Selector
selector就是一个方法指针，类似PHP里的动态方法名：

        <?php
        class Hello {
                public function sayHello() {}

                public function test() {
                        $fun_name = "sayHello";
                        $this->$fun_name();
                }
        }

在Objective-C里，selector主要用来做两类事情：

##### 绑定控件触发的动作

        @implementation DemoViewController
        - (void)downButtonPressed:(id)sender {//响应“按钮被按下事件”的方法
                UIButton *button = (UIButton*)sender;
                [button setSelected:YES];
        }

        - (void)drawAnButton {
                UIButton *btn = [UIButton buttonWithType:UIButtonTypeCustom];
                btn.frame = _frame;
                btn.tag = 1;
                btn.backgroundColor = [UIColor clearColor];
                [btn addTarget: self
                         action: @selector(downButtonPressed:)
                         forControlEvents: UIControlEventTouchUpInside];//当这个按钮被按下时，触发downButtonPressed:方法
        }
        @end

##### 延时异步执行

        @implementation ETHotDealViewController
        - (void)viewDidLoad {

                //获取数据源
                HotDealDataSource *ds = [[HotDealDataSource alloc]init];
                [ds reload];
                _items = ds.items;

                [self performSelector: @selector(refreshTable)
                          withObject: self
                          afterDelay: 0.5];//延迟0.5秒调用refreshTable方法
        }

        -(void)refreshTable
        {
                [self.tableView reloadData];
        }
        @end

这个例子中，获取数据源是通过ASIHTTP组件异步调用服务端HTTP接口，refreshTable要用到数据源返回回来的数据，如果不延迟0.5秒，就会立刻执行，执行的时候数据还在路上呢，页面就要变空白了。

### 继承
继承是写在Interface定义里面的。语法为：子类名在左，父类名在右，中间用冒号分隔。
示例：

        @interface MyClass : NSObject
        @end

对应的Java版本是：

        public class MyClass extends NSObject {
        }





### 协议（Protocol）
就是Java、PHP里的Interface。

#### 协议的定义
协议的定义用@protocol关键字：

        @protocol Printable
                -(void)print:(NSString)str;
        @end

对应的Java版本是：

        publilc interface Printable {
                public void print(String str);
        }

##### 协议的继承
协议本身也可以继承别的协议：

        @protocol Printable <NSObject>
                -(void)print:(NSString)str;
        @end

对应的Java版本：

        public interface Printable extends NSObject {
                public void print (String str);
        }

##### 可选方法
协议可以包含可选方法，顾名思义，可选方法可以不被类实现：

        @protocol Printable
        @optional
                -(void)print:(NSString)str;
        @end

加了@optional关键字，一个类在implements这个协议时，便可以不实现print:方法。

Java里没有类似的实现，除了Collection里会有一些方法带有optional的注释，但Collection是个特例。
