* 协议（Protocol）

就是Java、PHP里的Interface。

** 协议的定义
协议的定义用@protocol关键字：

#+BEGIN_SRC C
  @protocol Printable
          -(void)print:(NSString)str;
  @end
#+END_SRC

对应的Java版本是：

#+BEGIN_SRC java
  publilc interface Printable {
          public void print(String str);
  }
#+END_SRC

*** 协议的继承
协议本身也可以继承别的协议：

#+BEGIN_SRC C
  @protocol Printable <NSObject>
          -(void)print:(NSString)str;
  @end
#+END_SRC

对应的Java版本：

#+BEGIN_SRC java
  public interface Printable extends NSObject {
          public void print (String str);
  }
#+END_SRC

*** 可选方法

协议可以包含可选方法，顾名思义，可选方法可以不被类实现：

#+BEGIN_SRC C
  @protocol Printable
  @optional
          -(void)print:(NSString)str;
  @end
#+END_SRC

加了@optional关键字，一个类在implements这个协议时，便可以不实现print:方法。

Java里没有类似的实现，除了Collection里会有一些方法带有optional的注释，但Collection是个特例。

** 协议的实现

一个类实现某些协议是写在Interface定义里面的。语法为：协议名用尖括号包裹，多个协议名用逗号隔开，协议写在父类的右边（如果没有父类就直接写在子类右边）。

示例：

#+BEGIN_SRC C
  @interface MyClass : NSObject <Printable, Drawable>
  @end
#+END_SRC

Printable, Drawablw就是两个协议。

对应的Java版本是：

#+BEGIN_SRC java
  public class MyClass extends NSObject implements Printable, Drawable {
  }
#+END_SRC

**  分类（Category）

分类可以给一个已经存在的类增加方法，而不用去改它的源码。Java和PHP中都没有类似的特性。

比如说，NSObject是一个Objective-C内置的系统类，我们想给它增加toJson方法，就像这样：

头文件：NSObject+Json.h

#+BEGIN_SRC C
        @interface NSObject (Json)
                -(NSString)toJson;
        @end
#+END_SRC

实现文件：NSObject+Json.m

#+BEGIN_SRC C
@implementation NSObject (Json)
                -(NSString)toJson {
                        //...
                }
        @end
#+END_SRC

使用的时候，只要包含NSObject+Json.h，实例化NSObject类，就可以使用toJson方法了：

#+BEGIN_SRC C
        import "NSObject+Json.h"
        @implementation XYZController
                -(void)test {
                        NSObject *obj = [[NSObject alloc]init];
                        NSString *str = [obj toJson];
                }
        @end
#+END_SRC

当然了，NSObject本来的那些方法依然还是可以用的，什么都没变，只是多了个toJson方法。看起来是不是和继承没太多差别呢（除了使用的时候实例化的是NSObject，而不是JsonObject）？再看一个继承实现不了的例子：

头文件：NSObject+Json+XML.h

#+BEGIN_SRC C
        @interface NSObject (Json)
                -(NSString)toJson;
        @end

        @interface NSObject (XML)
                -(NSString)toXML;
        @end
#+END_SRC

实现文件：NSObject+Json+XML.m

#+BEGIN_SRC C
        @implementation NSObject (Json)
                -(NSString)toJson {
                        //...
                }
        @end

        @implementation NSObject (XML)
                -(NSString)toXML {
                        //...
                }
        @end
#+END_SRC

使用：

#+BEGIN_SRC C
        import "NSObject+Json+XML.h"
        @implementation XYZController
                -(void)test {
                        NSObject *obj = [[NSObject alloc]init];
                        NSString *json = [obj toJson];
                        NSString *xml = [obj toXML];
                }
        @end
#+END_SRC
