* sed 概览

** sed介绍与基本原理

SED - Stream EDitor

- 文本替换

- 选择性的输出文本文件

- 从文本文件的某处开始编辑

- 无交互式的对文本文件进行编辑等

** 命令行选项

*** 基础语法

SED可以用下列两种方式调用：

#+BEGIN_SRC bash
sed [-n] [-e] 'command(s)' files
sed [-n] -f scriptfile files
#+END_SRC

sed 也允许多个文件处理， The following example prints the first line of the first file (one.txt) and the last line of the last file (three.txt). Use -s to reverse this behavior.

#+BEGIN_SRC bash
sed -n  '1p ; $p' one.txt two.txt three.txt
#+END_SRC

*** 选项

**** 标准选项

- ~-n~ 默认情况下， ~模式空间~ 中的内容在处理完成后将会打印到标准输出，该选项用于阻止该行为

#+BEGIN_SRC bash
sed -n '' quote.txt
#+END_SRC

- ~-e~ 指定要执行的命令，使用该参数，我们可以 _指定多个命令(否则只能由引号包含一个命令)_ ，让我们打印每一行两次

#+BEGIN_SRC bash
$ sed -e '' -e 'p' quote.txt
There is only one thing that makes a dream impossible to achieve: the fear of failure.
There is only one thing that makes a dream impossible to achieve: the fear of failure.
 - Paulo Coelho, The Alchemist
 - Paulo Coelho, The Alchemist
#+END_SRC

- ~-f~ 指定包含要执行的命令的脚本文件

#+BEGIN_SRC bash
$ echo "p" > commands

$ sed -n -f commands quote.txt
There is only one thing that makes a dream impossible to achieve: the fear of failure.
 - Paulo Coelho, The Alchemist
#+END_SRC

**** GNU选项

这些选项是GNU规范定义的，可能对于某些版本的SED并不支持。

***** - ~n~ ， ~--quiet~ , ~--slient~

与标准的-n选项相同

每个cycle时，sed都会打印 pattern space中的内容。 这个命令会禁止automatic printing。

sed只会由p命令来打印内容。

By default, sed prints out the pattern space at the end of each cycle through the script. These options disable this automatic printing, and sed only produces output when explicitly told to via the p command.

***** ~-e script~ , ~--expression=script~

与标准的-e选项相同

***** ~-f script-file~ , ~--file=script-file~

与标准的-f选项相同

***** ~--follow-symlinks~

如果提供该选项的话，在编辑的文件是符号链接时，SED将会跟随链接

***** ~-i[SUFFIX]~ , ~--in-place[=SUFFIX]~

该选项用于对当前文件进行编辑，如果提供了SUFFIX的话，将会备份原始文件，否则将会覆盖原始文件

***** ~-l N~ , ~--line-lenght=N~

该选项用于设置行的长度为N个字符

***** ~--posix~

该选项禁用所有的GNU扩展

***** ~-r~ , ~--regexp-extended~

该选项将启用扩展的正则表达式

***** ~-u~ , ~--unbuffered~

指定该选项的时候，SED将会从输入文件中加载最少的数据，并且更加频繁的刷出到输出缓冲区。在编辑`tail -f`命令的输出，你不希望等待输出的时候该选项是非常有用的。

*****  ~-z~ , ~--null-data~

默认情况下，SED对每一行使用换行符分割，如果提供了该选项的话，它将使用NULL字符分割行

**** 示例A

#+BEGIN_SRC bash
$ cat quote.txt
There is only one thing that makes a dream impossible to achieve: the fear of failure.
     - Paulo Coelho, The Alchemist
#+END_SRC

为了理解SED的工作流，我们首先使用SED显示出quote.txt文件的内容，该示例与 ~cat~ 命令类似

#+BEGIN_SRC bash
$ sed '' quote.txt
There is only one thing that makes a dream impossible to achieve: the fear of failure.
    - Paulo Coelho, The Alchemist
#+END_SRC

在上面的例子中，quote.txt是输入的文件名称，两个单引号是要执行的SED命令。

首先，SED将会读取quote.txt文件中的一行内容存储到它的模式空间中，然后会在该缓冲区中执行SED命令。在这里，没有提供SED命令，因此对该缓冲区没有要执行的操作，最后它会删除模式空间中的内容并且打印该内容到标准输出


**** 示例B

在本例中，SED会从标准输入流接受输入

#+BEGIN_SRC bash
sed ''
#+END_SRC

当上述命令被执行的时候，将会产生下列结果

#+BEGIN_SRC bash
hello, world
hello, world

#+END_SRC

在这里，第一行内容是通过键盘输入的内容，第二行是SED输出的内容。

从SED会话中退出，使用组合键`ctrl-D (^D)`

**** 示例C

本例使用多个命令

#+BEGIN_SRC bash
cat books.txt
# 1) A Storm of Swords, George R. R. Martin, 1216
# 2) The Two Towers, J. R. R. Tolkien, 352
# 3) The Alchemist, Paulo Coelho, 197
# 4) The Fellowship of the Ring, J. R. R. Tolkien, 432
# 5) The Pilgrimage, Paulo Coelho, 288
# 6) A Game of Thrones, George R. R. Martin, 864

sed -e '1d' -e '2d' -e '5d' books.txt
# 3) The Alchemist, Paulo Coelho, 197
# 4) The Fellowship of the Ring, J. R. R. Tolkien, 432
# 6) A Game of Thrones, George R. R. Martin, 864
#+END_SRC

**** 示例D

本例使用 ~-f~ 指定命令文件

#+BEGIN_SRC bash
cat commands.txt
# 1d
# 2d
# 5d

sed -f commands.txt books.txt
# 3) The Alchemist, Paulo Coelho, 197
# 4) The Fellowship of the Ring, J. R. R. Tolkien, 432
# 6) A Game of Thrones, George R. R. Martin, 864
#+END_SRC
