* 低频命令

** 文件写入命令 ~w~

SED提供了 ~write~ 命令用于将模式空间中的内容写入到文件，与 ~delete~ 命令类似，下面是 ~write~ 命令的语法

    [address1[,address2]]w file

~w~ 指定是写命令， ~file~ 指的是存储文件内容的文件名。使用 ~file~ 操作符的时候要小心，当提供了文件名但是文件不存在的时候它会自动创建，如果已经存在的话则会~覆盖~原文件的内容。

下面的SED命令会创建文件books.txt的副本，在 ~w~ 和 ~file~ 之间只能有一个空格

    $ sed -n 'w books.bak' books.txt

上述命令创建了一个名为 ~books.bak~ 的文件，验证一下两个文件的内容是否相同

    $ diff books.txt books.bak
    $ echo $?

一旦执行上述的代码，你将会得到下列输出

    0

聪明的你可能已经想到了，这不就是 ~cp~ 命令做的事情吗！确实如此， ~cp~ 命令也做了同一件事情，但是SED是一个成熟的工具，使用它你可以只复制文件中的某些行到新的文件中，如下代码会存储文件中的奇数行到另一个文件

    $ sed -n '2~2 w junk.txt' books.txt
    $ cat junk.txt
    2) The Two Towers, J. R. R. Tolkien, 352
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    6) A Game of Thrones, George R. R. Martin, 864

假设你希望存储所有独立作者的书到单独的文件。如果人工去做的话，肯定是非常无聊而且没有技术含量的，但是使用SED，你就有了更加聪明的方法去实现

    $ sed -n -e '/Martin/ w Martin.txt' -e '/Paulo/ w Paulo.txt' -e '/Tolkien/ w Tolkien.txt' books.txt

    $ cat Martin.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    6) A Game of Thrones, George R. R. Martin, 864

    $ cat Paulo.txt
    3) The Alchemist, Paulo Coelho, 197
    5) The Pilgrimage, Paulo Coelho, 288

    $ cat Tolkien.txt
    2) The Two Towers, J. R. R. Tolkien, 352
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432


** 追加命令 ~a~

文本追加命令语法：

    [address]a\
    Append text

在第四行之后追加一本新书：

    $ sed '4 a 7) Adultry, Paulo Coelho, 234' books.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) The Alchemist, Paulo Coelho, 197
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    7) Adultry, Paulo Coelho, 234
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

在命令部分，4指的是行号，~a~ 是append命令，剩余部分为要追加的文本。

在文件的结尾插入一行文本，使用 ~$~ 作为地址

    $ sed '$ a 7) Adultry, Paulo Coelho, 234' books.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) The Alchemist, Paulo Coelho, 197
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864
    7) Adultry, Paulo Coelho, 234

除了行号，我们也可以使用文本模式指定地址，例如，在匹配 ~The Alchemist~ 的行之后追加文本

    $ sed '/The Alchemist/ a 7) Adultry, Paulo Coelho, 234' books.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) The Alchemist, Paulo Coelho, 197
    7) Adultry, Paulo Coelho, 234
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

** 行替换命令 ~c~

SED通过 ~c~ 提供了 ~change~ 和 ~replace~ 命令，该命令帮助我们使用新文本替换已经存在的行，当提供行的地址范围时，所有的行都被作为一组被替换为单行文本，下面是该命令的语法

    [address1[,address2]]c\
    Replace text

比如，替换文本中的第三行为新的内容

    $ sed '3 c 3) Adultry, Paulo Coelho, 324' books.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) Adultry, Paulo Coelho, 324
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

SED也接受模式作为地址

    $ sed '/The Alchemist/ c 3) Adultry, Paulo Coelho, 324' books.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) Adultry, Paulo Coelho, 324
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

多行替换也是支持的，下面的命令实现了将第4-6行内容替换为单行

    $ sed '4, 6 c 4) Adultry, Paulo Coelho, 324' books.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) The Alchemist, Paulo Coelho, 197
    4) Adultry, Paulo Coelho, 324

** 插入命令 ~i~

插入命令与追加命令类似，唯一的区别是插入命令是在匹配的位置前插入新的一行。

    [address]i\
    Insert text

下面的命令会在第四行前插入新的一行

    $ sed '4 i 7) Adultry, Paulo Coelho, 324' books.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) The Alchemist, Paulo Coelho, 197
    7) Adultry, Paulo Coelho, 324
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

** 转换命令 ~y~

转换（Translate）命令 ~y~ 是唯一可以处理单个字符的sed编辑器命令。转换命令格式 如下

    [address]y/inchars/outchars/

转换命令会对inchars和outchars值进行一对一的映射。inchars中的第一个字符会被转换为outchars中的第一个字符，第二个字符会被转换成outchars中的第二个字符。这个映射过程会一直持续到处理完指定字符。如果inchars和outchars的长度不同，则sed编辑器会产生一 条错误消息。

    $ echo "1 5 15 20" | sed 'y/151520/IVXVXX/'
    I V IV XX

** 输出隐藏字符命令 ~l~

你能通过直接观察区分出单词是通过空格还是tab进行分隔的吗？显然是不能的，但是SED可以为你做到这点。使用 ~l~ 命令（英文字母L的小写）可以显示文本中的隐藏字符（例如 ~\t~ 或者 ~$~ 字符）。

    [address1[,address2]]l
    [address1[,address2]]l [len]

为了测试该命令，我们首先将books.txt中的空格替换为tab。

    $ sed 's/ /\t/g' books.txt > junk.txt

接下来执行 ~l~ 命令

    $ sed -n 'l' junk.txt
    1)\tStorm\tof\tSwords,\tGeorge\tR.\tR.\tMartin,\t1216\t$
    2)\tThe\tTwo\tTowers,\tJ.\tR.\tR.\tTolkien,\t352\t$
    3)\tThe\tAlchemist,\tPaulo\tCoelho,\t197\t$
    4)\tThe\tFellowship\tof\tthe\tRing,\tJ.\tR.\tR.\tTolkien,\t432\t$
    5)\tThe\tPilgrimage,\tPaulo\tCoelho,\t288\t$
    6)\tA\tGame\tof\tThrones,\tGeorge\tR.\tR.\tMartin,\t864$

使用 ~l~ 命令的时候，一个很有趣的特性是我们可以使用它来实现文本按照指定的宽度换行。

    $ sed -n 'l 25' books.txt
    1) Storm of Swords, Geor\
    ge R. R. Martin, 1216 $
    2) The Two Towers, J. R.\
     R. Tolkien, 352 $
    3) The Alchemist, Paulo \
    Coelho, 197 $
    4) The Fellowship of the\
     Ring, J. R. R. Tolkien,\
     432 $
    5) The Pilgrimage, Paulo\
     Coelho, 288 $
    6) A Game of Thrones, Ge\
    orge R. R. Martin, 864$

上面的示例中在 ~l~ 命令后跟了一个数字25，它告诉SED按照每行25个字符进行换行，如果指定这个数字为0的话，则只有在存在换行符的情况下才进行换行。

>  ~l~ 命令是GNU-SED的一部分，其它的一些变体中可能无法使用该命令。

** 文件读取命令 ~r~

在SED中，我们可以让SED使用Read命令从外部文件中读取内容并且在满足条件的时候显示出来。

    [address]r file

需要注意的是， ~r~ 命令和文件名之间必须只有一个空格。

下面的示例会打开*junk.txt*文件，将其内容插入到*books.txt*文件的第三行之后

    $ echo "This is junk text." > junk.txt
    $ sed '3 r junk.txt' books.txt
    1) A Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) The Alchemist, Paulo Coelho, 197
    This is junk text.
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

>  ~r~ 命令也支持地址范围，例如*3, 5 r junk.txt*会在第三行，第四行，第五行后面分别插入*junk.txt*的内容

** 执行外部命令 ~e~

如果你看过[三十分钟学会AWK][]一文，你可能已经知道了在AWK中可以执行外部的命令，那么在SED中我们是否也可以这样做？

答案是肯定的，在SED中，我们可以使用 ~e~ 命令执行外部命令

    [address1[,address2]]e [command]

下面的命令会在第三行之前执行*date*命令

    $ sed '3 e date' books.txt
    1) Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    2016年11月29日 星期二 22时46分14秒 CST
    3) The Alchemist, Paulo Coelho, 197
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

另一个示例

    $ sed '3,5 e who' books.txt
    1) Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    mylxsw   console  Nov 29 19:30
    mylxsw   ttys000  Nov 29 22:45
    3) The Alchemist, Paulo Coelho, 197
    mylxsw   console  Nov 29 19:30
    mylxsw   ttys000  Nov 29 22:45
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    mylxsw   console  Nov 29 19:30
    mylxsw   ttys000  Nov 29 22:45
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

如果你仔细观察 ~e~ 命令的语法，你会发现其实它的*command*参数是可选的。在没有提供外部命令的时候，SED会将模式空间中的内容作为要执行的命令。

    $ echo -e "date\ncal\nuname" > commands.txt
    $ cat commands.txt
    date
    cal
    uname
    $ sed 'e' commands.txt
    2016年11月29日 星期二 22时50分30秒 CST
        十一月 2016
    日 一 二 三 四 五 六
           1  2  3  4  5
     6  7  8  9 10 11 12
    13 14 15 16 17 18 19
    20 21 22 23 24 25 26
    27 28 29 30

    Darwin

** 排除命令 ~!~

感叹号命令 ~!~ 用来排除命令，也就是让原本会起作用的命令不起作用。

    $ sed -n '/Paulo/p' books.txt
    3) The Alchemist, Paulo Coelho, 197
    5) The Pilgrimage, Paulo Coelho, 288
    $ sed -n '/Paulo/!p' books.txt
    1) Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    6) A Game of Thrones, George R. R. Martin, 864

如上例所示， ~p~ 命令原先是只输出匹配*Paulo*的行，添加 ~!~ 之后，变成了只输出不匹配*Paulo*的行。

    $ sed -n '1!G; h; $p' books.txt
    6) A Game of Thrones, George R. R. Martin, 864
    5) The Pilgrimage, Paulo Coelho, 288
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    3) The Alchemist, Paulo Coelho, 197
    2) The Two Towers, J. R. R. Tolkien, 352
    1) Storm of Swords, George R. R. Martin, 1216

上面的命令实现了类似 ~tac~ 命令类似的输出，将文本内容倒序输出。看起来有些晦涩难懂，分解一下却十分简单：

1. *1!G* 这句的意思是出了第一行之外，处理每一行的时候都将保持空间中的内容追加到模式空间（正序->倒序）
2. *h* 将模式空间中的内容复制到保持空间以备下一行匹配的时候追加到下一行的后面
3. *$p* 如果匹配到最后一行的话则输出模式空间中的内容
4. 上述步骤不断重复直到文本结束刚好将文件内容翻转了一次

** 多行命令

在使用sed编辑器的基础命令时，你可能注意到了一个局限。所有的sed编辑器命令都是针对 ~单行~ 数据执行操作的。在sed编辑器读取数据流时，它会基于~换行符~的位置将数据分成行。sed编辑器根据定义好的脚本命令一次处理一行数据，然后移到下一行重复这个过程。

幸运的是，sed编辑器的设计人员已经考虑到了这种情况，并设计了对应的解决方案。sed编辑器包含了三个可用来处理多行文本的特殊命令。

- ~N~ ：将数据流中的下一行加进来创建一个多行组来处理
- ~D~ ：删除多行组中的一行
- ~P~ ：打印多行组中的一行

*** N - 加载下一行

默认情况下，SED是基于单行进行操作的，有些情况下我们可能需要使用多行进行编辑，启用多行编辑使用~N~命令，与~n~不同的是，~N~并不会清除、输出模式空间的内容，而是采用了追加模式。

    [address1[,address2]]N

下面的示例将会把*books2.txt*中的标题和作者放到同一行展示，并且使用逗号进行分隔

    $ sed 'N; s/\n/,/g' books2.txt
    A Storm of Swords ,George R. R. Martin
    The Two Towers ,J. R. R. Tolkien
    The Alchemist ,Paulo Coelho
    The Fellowship of the Ring ,J. R. R. Tolkien
    The Pilgrimage ,Paulo Coelho
    A Game of Thrones ,George R. R. Martin

*** D - 删除多行中的一行

sed编辑器提供了多行删除命令~D~，它只删除模式空间中的第一行。该命令会删除到换行符（含 换行符）为止的所有字符。

    $ echo '\nThis is the header line.\nThis is a data line.\n\nThis is the last line.' | sed '/^$/{N; /header/D}'
    This is the header line.
    This is a data line.

    This is the last line.

*** P - 输出多行中的一行

~P~命令用于输出~N~命令创建的多行文本的模式空间中的第一行。

    [address1[,address2]]P

例如下面的命令只输出了图书的标题

    $ sed -n 'N;P' books2.txt
    A Storm of Swords
    The Two Towers
    The Alchemist
    The Fellowship of the Ring
    The Pilgrimage
    A Game of Thrones

** 其它命令

*** n - 单行next

小写的n命令会告诉sed编辑器移动到数据流中的下一文本行，并且覆盖当前模式空间中的行。

    $ cat data1.txt
    This is the header line.

    This is a data line.

    This is the last line.
    $ sed '/header/{n ; d}' data1.txt
    This is the header line.
    This is a data line.

    This is the last line.

上面的命令中，首先会匹配包含*header*的行，之后将移动到数据流的下一行，这里是一个空行，然后执行~d~命令对改行进行删除，所有就看到了这样的结果：第一个空行被删除掉了。

*** v - SED版本检查

~v~命令用于检查SED的版本，如果版本大于参数中的版本则正常执行，否则失败

    [address1[,address2]]v [version]

例如

    $ sed --version
    sed (GNU sed) 4.2.2

    $ sed 'v 4.2.3' books.txt
    sed: -e expression #1, char 7: expected newer version of sed

    $ sed 'v 4.2.2' books.txt
    1) Storm of Swords, George R. R. Martin, 1216
    2) The Two Towers, J. R. R. Tolkien, 352
    3) The Alchemist, Paulo Coelho, 197
    4) The Fellowship of the Ring, J. R. R. Tolkien, 432
    5) The Pilgrimage, Paulo Coelho, 288
    6) A Game of Thrones, George R. R. Martin, 864

** 特殊字符

在SED中提供了两个可以用作命令的特殊字符：~=~ 和 ~&~ 。

** ~=~ 命令

~=~ 命令用于输出行号，语法格式为

    [/pattern/]=
    [address1[,address2]]=

例如为每一行输出行号

    $ sed '=' books2.txt
    1
    A Storm of Swords
    2
    George R. R. Martin
    ...

只为1-4行输出行号

    $ sed '1, 4=' books2.txt
    1
    A Storm of Swords
    2
    George R. R. Martin
    3
    The Two Towers
    4
    J. R. R. Tolkien
    The Alchemist
    Paulo Coelho
    The Fellowship of the Ring
    J. R. R. Tolkien
    The Pilgrimage
    Paulo Coelho
    A Game of Thrones
    George R. R. Martin

匹配Paulo的行输出行号

    $ sed '/Paulo/ =' books2.txt
    A Storm of Swords
    George R. R. Martin
    The Two Towers
    J. R. R. Tolkien
    The Alchemist
    6
    Paulo Coelho
    The Fellowship of the Ring
    J. R. R. Tolkien
    The Pilgrimage
    10
    Paulo Coelho
    A Game of Thrones
    George R. R. Martin

最后一行输出行号，这个命令比较有意思了，可以用于输出文件总共有多少行

    $ sed -n '$ =' books2.txt
    12

** ~&~ 命令

特殊字符~&~用于存储匹配模式的内容，通常与替换命令~s~一起使用。

#+BEGIN_SRC bash
$ sed 's/[[:digit:]]/Book number &/' books.txt
Book number 1) Storm of Swords, George R. R. Martin, 1216
Book number 2) The Two Towers, J. R. R. Tolkien, 352
Book number 3) The Alchemist, Paulo Coelho, 197
Book number 4) The Fellowship of the Ring, J. R. R. Tolkien, 432
Book number 5) The Pilgrimage, Paulo Coelho, 288
Book number 6) A Game of Thrones, George R. R. Martin, 864
#+END_SRC

上述命令用于匹配每一行第一个数字，在其前面添加 *Book number* 。而下面这个命令则匹配最后一个数字，并修改为~Pages =~。其中~[[:digit:]]* *$~可能比较费解，这一部分其实是：*匹配0个或多个数字+0个或多个空格+行尾*。

    sed 's/[[:digit:]]* *$/Pages = &/' books.txt
    1) Storm of Swords, George R. R. Martin, Pages = 1216
    2) The Two Towers, J. R. R. Tolkien, Pages = 352
    3) The Alchemist, Paulo Coelho, Pages = 197
    4) The Fellowship of the Ring, J. R. R. Tolkien, Pages = 432
    5) The Pilgrimage, Paulo Coelho, Pages = 288
    6) A Game of Thrones, George R. R. Martin, Pages = 864
