* overview

iproute2是Linux上有关TCP/IP网络的一系列工具，现时由Stephen Hemminger负责维护。这一系列工具的原作是Alexey Kuznetsov，他亦是Linux内核中有关QoS实现的作者。这一系列的工具包括了以下几个组件：

- ss
- ip
- lnstat
- nstat
- rdma
- routef
- routel
- ctstat
- rtstat
- tc
- bridge
- devlink
- rtacct
- rtmon
- tipc
- arpd
- genl


iproute2是linux下管理控制TCP/IP网络和流量控制的新一代工具包，旨在替代老派的工具链net-tools，即大家比较熟悉的ifconfig，arp，route，netstat等命令。

要说这两套工具本质的区别，应该是net-tools是通过procfs (/proc)和ioctl系统调用去访问和改变内核网络配置，而iproute2则通过netlink套接字接口与内核通讯。

其次，net-tools的用法给人的感觉是比较乱，而iproute2的用户接口相对net-tools来说相对来说，更加直观。比如，各种网络资源（如link、IP地址、路由和隧道等）均使用合适的对象抽象去定义，使得用户可使用一致的语法去管理不同的对象。

所以，net-tools和iproute2都需要去学习掌握了

** IP 命令的 Object

~address~ protocol (IP or IPv6) address on a device.

~addrlabel~ label configuration for protocol address selection.

~l2tp~ tunnel ethernet over IP (L2TPv3).

~link~ network device.

~maddress~ multicast address.

~monitor~ watch for netlink messages.

~mroute~ multicast routing cache entry.

~mrule~ rule in multicast routing policy database.

~neighbour~ manage ARP or NDISC cache entries.

~netns~ manage network namespaces.

~ntable~ manage the neighbor cache's operation.

~route~ routing table entry.

~rule~ rule in routing policy database.

~tcp_metrics/tcpmetrics~ manage TCP Metrics

~token~ manage tokenized interface identifiers.

~tunnel~ tunnel over IP.

~tuntap~ manage TUN/TAP devices.

~xfrm~ manage IPSec policies.
