FROM centos8

SHELL [ "/bin/bash", "-l", "-c" ]

        RUN apt-get update && apt-get install -y curl
        RUN curl --silent -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
        # this now works
RUN nvm install && nvm use
