* journalctl

** 简介

journalctl 用来查询 systemd-journald 服务收集到的日志。

~systemd-journald~ 服务是 ~systemd init~ 系统提供的收集系统日志的服务。

#+BEGIN_SRC bash
journalctl [OPTIONS…] [MATCHES…]

# 可以通过 man page 和 -h 选项来获得最直接的帮助文档：
$ man journalctl
$ journalctl -h
#+END_SRC

Systemd 统一管理所有 Unit 的启动日志。带来的好处就是 ，可以只用journalctl一个命令，查看所有日志（内核日志和 应用日志）。日志的配置文件  ~/etc/systemd/journald.conf~

** 查看日志

#+BEGIN_SRC bash
# 不带任何选项时，journalctl 输出所有的日志记录：
$ sudo journalctl

# 查看内核日志（不显示应用日志）
journalctl -k

# 查看系统本次启动的日志
journalctl -b

# 在您的服务器上启用了保存以前的引导时，journalctl提供了一些命令来帮助您将引导作为分割单位来使用。要查看journald知道的引导，请使用以下--list-boots选项journalctl：
journalctl --list-boots
# -1 00d066e11cb3412a912cb804cee123b5 Thu 2018-02-22 17:01:47 CST—Thu 2018-02-22 17:09:15 CST
# 0 63f75abbe94c4087bc2cc3cdb3b57100 Thu 2018-02-22 17:09:10 CST—Thu 2018-02-22 17:10:19 CST
#+END_SRC


在该[Journal]部分下，将该Storage=选项设置为“persistent”以启用持久记录， =/etc/systemd/journald.conf=

#+BEGIN_SRC bash
[Journal]
Storage=persistent
#+END_SRC


这将为每次启动显示一行。第一列是启动的偏移量，可用于轻松引用启动journalctl。如果您需要绝对参考，则启动ID位于第二列。您可以通过在结束时列出的两个时间规范来指出引导会话引用的时间。

要显示来自这些引导的信息，您可以使用来自第一列或第二列的信息。

例如，要查看上一次启动的日志，请使用-1带有该-b标志的相对指针：

#+BEGIN_SRC bash
journalctl -b -1
#+END_SRC

*** 查看指定时间的日志

可以使用--since和--until选项过滤任意时间限制，这些限制分别显示给定时间之前或之后的条目。

例如： #"显示2017年10月30号，18点10分30秒到当前时间之间的所有日志信息"

#+BEGIN_SRC bash
journalctl --since="2017-10-30 18:10:30"
#+END_SRC

另外，journal还能够理解部分相对值及命名简写。例如，大家可以使用“yesterday”、“today”、“tomorrow”或者“now”等表达。另外，我们也可以使用“-”或者“+”设定相对值，或者使用“ago”之前的表达。定义灵活的时间窗口来过滤您希望看到的条目相对容易。

#+BEGIN_SRC bash
# 获取昨天的日志如下：
journalctl –since yesterday

# 获取某一个时间段到当前时间的前一个小时的日志
journalctl --since 09:00 --until "1 hour ago"

# 获取当前时间的前20分钟的日志
journalctl --since "20 min ago"

# 获取某一天到某一个时间段的日志信息
journalctl --since "2017-01-10" --until "2017-01-11 03:00"
#+END_SRC

*** 按消息兴趣过滤

我们在上面学习了一些可以使用时间限制来过滤日记数据的方法。在本节中，我们将讨论如何根据您感兴趣的服务或组件来进行过滤。systemd日记提供了多种方法来执行此操作。

**** 按服务

也许最有用的过滤方式是你感兴趣的单位。我们可以使用这个-u选项来过滤。例如，查看httpd服务的日志信息

#+BEGIN_SRC bash
[root@centos7 ~]# journalctl -u httpd.service
-- Logs begin at Thu 2018-02-22 17:01:47 CST, end at Thu 2018-02-22 17:30:01 CST. --
Feb 22 17:29:27 centos7.localdomain systemd[1]: Starting The Apache HTTP Server...
Feb 22 17:29:27 centos7.localdomain httpd[1610]: AH00558: httpd: Could not reliably determine t
Feb 22 17:29:28 centos7.localdomain systemd[1]: Started The Apache HTTP Server.
#+END_SRC

也可以查看httpd服务当天的运行状况

-u 是 =--unit=UNIT|PATTERN= 的简写

#+BEGIN_SRC bash
journalctl -u httpd.service --since today
#+END_SRC

*** 按进程、用户或者群组ID

由于某些服务当中包含多个子进程，因此如果我们希望通过进程ID实现查询，也可以使用相关过滤机制。

这里需要指定_PID字段。例如，如果PID为8088，则可输入：

#+BEGIN_SRC bash
journalctl _PID=8088
#+END_SRC

有时候我们可能希望显示全部来自特定用户或者群组的日志条目，这就需要使用_UID或者_GID。例如，如果大家的Web服务器运行在www-data用户下，则可这样找到该用户ID，我们可以使用该ID返回过滤后的journal结果。

#+BEGIN_SRC bash
$ id -u www-data
2000

journalctl _UID=2000 --since today
#+END_SRC


Systemd journal拥有多种可实现过滤功能的字段。其中一些来自被记录的进程，有些则由journald用于自系统中收集特定时间段内的日志。

之前提到的_PID属于后一种。Journal会自动记录并检索进程PID，以备日后过滤之用。大家可以查看当前全部可用journal字段：

man systemd.journal-fields
下面来看针对这些字段的过滤机制。-F选项可用于显示特定journal字段内的全部可用值。

例如，要查看systemd journal拥有条目的群组ID，可使用以下命令：

[root@centos7 ~]# journalctl -F _GID
995
42
40
70
172
998
81
0
其将显示全部journal已经存储至群组ID字段内的值，并可用于未来的过滤需求。

按优先级
管理员们可能感兴趣的另一种过滤机制为信息优先级。尽管以更为详尽的方式查看日志也很有必要，不过在理解现有信息时，低优先级日志往往会分散我们的注意力并导致理解混乱。

大家可以使用journalctl配合-p选项显示特定优先级的信息，从而过滤掉优先级较低的信息。

例如，只显示错误级别或者更高的日志条目：

    [root@centos7 ~]# journalctl -p err -b
    -- Logs begin at Thu 2018-02-22 17:01:47 CST, end at Thu 2018-02-22 17:40:02 CST. --
    Feb 22 17:09:10 centos7.localdomain kernel: sd 0:0:0:0: [sda] Assuming drive cache: write throu
    Feb 22 17:09:12 centos7.localdomain kernel: piix4_smbus 0000:00:07.3: SMBus Host Controller not
    Feb 22 17:09:15 centos7.localdomain rsyslogd[593]: error during parsing file /etc/rsyslog.conf,
    Feb 22 17:09:47 centos7.localdomain pulseaudio[1232]: [alsa-sink-ES1371/1] alsa-sink.c: ALSA wo
    Feb 22 17:09:47 centos7.localdomain pulseaudio[1232]: [alsa-sink-ES1371/1] alsa-sink.c: Most li
    Feb 22 17:09:47 centos7.localdomain pulseaudio[1232]: [alsa-sink-ES1371/1] alsa-sink.c: We were
    Feb 22 17:09:48 centos7.localdomain spice-vdagent[1274]: Cannot access vdagent virtio channel /
    lines 1-8/8 (END)
这将只显示被标记为错误、严重、警告或者紧急级别的信息。Journal的这种实现方式与标准syslog信息在级别上是一致的。大家可以使用优先级名称或者其相关量化值。以下各数字为由最高到最低优先级：

    0: emerg
    1: alert
    2: crit
    3: err
    4: warning
    5: notice
    6: info
    7: debug

例如：
    [root@centos7 ~]# journalctl -p 3 -b
    -- Logs begin at Thu 2018-02-22 17:01:47 CST, end at Thu 2018-02-22 17:50:01 CST. --
    Feb 22 17:09:10 centos7.localdomain kernel: sd 0:0:0:0: [sda] Assuming drive cache: write throu
    Feb 22 17:09:12 centos7.localdomain kernel: piix4_smbus 0000:00:07.3: SMBus Host Controller not
    Feb 22 17:09:15 centos7.localdomain rsyslogd[593]: error during parsing file /etc/rsyslog.conf,
    Feb 22 17:09:47 centos7.localdomain pulseaudio[1232]: [alsa-sink-ES1371/1] alsa-sink.c: ALSA wo
    Feb 22 17:09:47 centos7.localdomain pulseaudio[1232]: [alsa-sink-ES1371/1] alsa-sink.c: Most li
    Feb 22 17:09:47 centos7.localdomain pulseaudio[1232]: [alsa-sink-ES1371/1] alsa-sink.c: We were
    Feb 22 17:09:48 centos7.localdomain spice-vdagent[1274]: Cannot access vdagent virtio channel /
    lines 1-8/8 (END)
修改journal显示内容
到这里，过滤部分已经介绍完毕。我们也可以使用多种方式对输出结果进行修改，从而调整journalctl的显示内容。

分页显示（默认）或者改为正常标准输出

分页显示，其中插入省略号以代表被移除的信息，使用–no-full选

journalctl --no-full

. . .

Feb 04 20:54:13 journalme sshd[937]: Failed password for root from 83.234.207.60...h2
Feb 04 20:54:13 journalme sshd[937]: Connection closed by 83.234.207.60 [preauth]
大家也可以要求其显示全部信息，无论其是否包含不可输出的字符。具体方式为添加-a标记：

journalctl -a
默认情况下，journalctl会在pager内显示输出结果以便于查阅。如果大家希望利用文本操作工具对数据进行处理，则可能需要使用标准格式。在这种情况下，我们需要使用–no-pager选项：

journalctl --no-pager
这样就可以用一些工具过滤出自己感兴趣的信息了

下面来介绍下输出格式
如果大家需要对journal条目进行处理，则可能需要使用更易使用的格式以简化数据解析工作。幸运的是，journal能够以多种格式进行显示，只须添加-o选项加格式说明即可。

例如，我们可以将journal条目输出为JSON格式：

    [root@centos7 ~]# journalctl -b -u httpd -o json
    { "__CURSOR" : "s=8fa6a8a1c6264c7b938e4d23584ae602;i=149d;b=63f75abbe94c4087bc2cc3cdb3b57100;m=46edf6e6;t=565c9ae1d38f7;x=b3a1eaebceb26d5b", "__REALTIME_TIMESTAMP" : "1519291767535863", "__MONOTONIC_TIMESTAMP"
    { "__CURSOR" : "s=8fa6a8a1c6264c7b938e4d23584ae602;i=149e;b=63f75abbe94c4087bc2cc3cdb3b57100;m=46f3506d;t=565c9ae22927d;x=91ef081943191196", "__REALTIME_TIMESTAMP" : "1519291767886461", "__MONOTONIC_TIMESTAMP"
    { "__CURSOR" : "s=8fa6a8a1c6264c7b938e4d23584ae602;i=149f;b=63f75abbe94c4087bc2cc3cdb3b57100;m=46f7a7e4;t=565c9ae26e9f5;x=1f0dc6e3105af151", "__REALTIME_TIMESTAMP" : "1519291768170997", "__MONOTONIC_TIMESTAMP"
这种方式对于工具解析非常重要。大家也可以使用json-pretty格式以更好地处理数据结构，这种方法易读性，显示的内容也比较全面：

    [root@centos7 ~]# journalctl -u httpd -o  json-pretty
    {
            "__CURSOR" :}}}}
