* net
** opensuse使用networkManager作为网络管理工具

  1. Run YaST and go to Network Devices > Network Settings.

  1. The Network Settings dialog opens. Go to the Global Options tab.

  1. In the Network Setup Method field, activate User Controlled with NetworkManager.

  1. Click Finish.

  1. After choosing the method for managing network connections, set up your network card using automatic configuration via DHCP or a static IP address or configure your modem (for dial-up connections, use Network Devices > Modem). To configure an internal or USB ISDN modem, select Network Devices > ISDN. To configure an internal or USB DSL modem, select Network Devices > DSL.


** cmb wifi

*** wifi

  - wifi clone

  - account & password

    1. =z673252= (连接时要有 =z= 这个字母)，密码为开机密码

    1. =/etc/NetworkManager/system-connections= 存放网络连接信息

*** wired connection 有线链接设置（仅用于一根网线连接两台主机之间的ssh）

- ipv4

  1. method = manual

  1. +Add address

     1. address 192.168.1.100, netmask 255.255.255.0, gateway 0, 0, 0, 0

  1. routes（这一步似乎可以不要）

     1. address 192.168.1.100, netmask 255.255.255.0, gateway 0.0.0.0, Metric 1000

文件 ~/etc/NetworkManager/system-connections/Wired\ connection\ 1~ 中展示了route添加的配置


- pc 192.168.1.91

- linux 192.168.1.95

#+BEGIN_SRC text
[connection]
id=Wired connection 1
uuid=93844899-e657-39d9-94ff-4ee91a4737ea
type=ethernet
autoconnect-priority=-100
permissions=
timestamp=1587000256

[ethernet]
duplex=half
mac-address=00:0E:C6:A0:A8:B3
mac-address-blacklist=
speed=100

[ipv4]
address1=192.168.1.95/24,192.168.1.1
dns-search=
may-fail=false
method=manual
route1=99.48.64.0/24,192.168.1.91,100
route2=99.47.192.0/22,192.168.1.91,100
route3=99.47.148.0/22,192.168.1.91,100

[ipv6]
addr-gen-mode=stable-privacy
dns-search=
method=auto
#+END_SRC


*** 无法连接常见问题

  1. firewall 挡住了开放的端口

#+BEGIN_SRC txt
vg3ExbcKGQ2M  # attention
IP address:104.224.145.252
SSH Port:26228
#+END_SRC

ss.simplecoder.xyz

wuzhi1234.synology.me

*** bwh的 黑名单检查

https://kiwivm.64clouds.com/main-exec.php?mode=blacklistcheck


** networkmanager

  1. Yast2

  1. Network setting

  1. Global Options

  1. Network setup -> _User Controlled with NetowrkManager_

  1. OK

** windows


*** 安装sshfs-win

  - https://github.com/billziss-gh/sshfs-win

  - 安装步骤

    1. winfsp-1.4.19049.msi

    1. sshfs-win-3.5.19106-x64.msi

*** 如何使用

[简而言之]：

  - 在explorer左侧的计算机图标上右击，会有映射网络驱动器

  - 选择驱动器为 Z:， 文件夹为： \\sshfs\leo@192.168.1.100 (应该是起了个\\sshfs的协议)

More Info:

使用教程请参见： http://makerlab.cs.hku.hk/index.php/en/mapping-network-drive-over-ssh-in-windows


** 安装 squid, shadowsocks, privoxy

参考 software下的文件
