#+TITLE: objective C intro


obj.method(argument);

[obj method: argument];


* 字符串


作为C语言的超集，Objective-C 支持 C 语言字符串方面的约定。也就是说，单个字符被单引号包括，字符串被双引号包括。然而，大多数Objective-C通常不使用C语言风格的字符串。

反之，大多数框架把字符串传递给NSString对象。NSString类提供了字符串的类包装，包含了所有你期望的优点，包括对保存任意长度字符串的内建内存管理机制，支持Unicode，printf风格的格式化工具，等等。因为这种字符串使用的非常频繁，Objective-C提供了一个助记符可以方便地从常量值创建NSString对象。要使用这个助记符，你需要做的全部事情，是在普通的双引号字符串前放置一个@符号，如下面的例子所示：

#+BEGIN_SRC c
NSString* myString = @"My String\n";
NSString* anotherString = [NSString stringWithFormat:@"%d %s", 1, @"String"];

// 从一个C语言字符串创建Objective-C字符串
NSString*  fromCString = [NSString stringWithCString:"A C string"
encoding:NSASCIIStringEncoding];
#+END_SRC


* 函数


函数调用
前文述及，不涉及面向对象时，它和C是完全一样的。以下是几个函数调用的示例：
#+BEGIN_SRC C
// 不带参数
startedBlock();

// 带参数
NSLog(@"decrypted string: %@", str);
CGRectMake(0,0,0,0);
#+END_SRC


* 消息传递

~[car fly]~ 典型的C++意义解读是"调用car类别的fly方法"。若car类别里头没有定义fly方法，那编译肯定不会通过。

但是Objective-C里，我们应当解读为"发提交一个fly的消息给car对象"，fly是消息，而car是消息的接收者。car收到消息后会决定如何回应这个消息，若car类别内定义有fly方法就运行方法内之代码，若car内不存在fly方法，则程序依旧可以通过编译，运行期则抛出异常。

此二种风格各有优劣。C++强制要求所有的方法都必须有对应的动作，且编译期绑定使得函数调用非常快速。缺点是仅能借由virtual关键字提供有限的动态绑定能力。Objective-C天生即具备鸭子类型之动态绑定能力，因为运行期才处理消息，允许发送未知消息给对象。可以送消息给整个对象集合而不需要一一检查每个对象的类型，也具备消息转送机制。同时空对象nil接受消息后默认为不做事，所以送消息给nil也不用担心程序崩溃。


#+BEGIN_SRC C
[obj method];
#+END_SRC

对应的Java版本

#+BEGIN_SRC java
obj.method();
#+END_SRC

** 带一个参数：

#+BEGIN_SRC C
[counter increase:1];
#+END_SRC

对应的Java版本

#+BEGIN_SRC java
counter.increase(1);
#+END_SRC

**  带多个参数

对C Family程序员来说，这是最难接受的，最反人类的：

#+BEGIN_SRC C
- (void) setColorToRed: (float)red Green: (float)green Blue:(float)blue {...} //定义方法
  [myObj setColorToRed: 1.0 Green: 0.8 Blue: 0.2]; //调用方法
#+END_SRC
对应的Java版

#+BEGIN_SRC java
public void setColorToRedGreenBlue(float red, float green, float blue) {...}
myObj.setColorToRedGreenBlue(1.0, 0.8, 0.2);
#+END_SRC

** 消息嵌套

#+BEGIN_SRC C
UINavigationBar *bar = [[[UINavigationBar alloc] init] autorelease];
#+END_SRC

对应的Java版

#+BEGIN_SRC java
UINavigationBar bar = UINavigationBar.alloc().init().autorelease();//Java没有指针，所以星号去掉了
#+END_SRC


* 类

** 接口和实现

Objective-C的类分为接口定义和实现两个部分。

1. 接口定义（Interface）放在头文件中，文件扩展名是.h

1. 实现（implementation）放在实现文件中，文件扩展名是.m（也有.mm的扩展名，表示Objective-C和C++混编的代码）。

#+BEGIN_COMMENT
接口定义也可以写在.m文件中，但最好不要这么干
#+END_COMMENT

需要注意的是，与Objective-C的interface概念最接近的是C和C++里的头文件，它与implementation是成双成对出现的，作用是声明类的成员变量和方法。它与Java的interface概念完全不同：

- Objective-C里，interface有且只有一个实现，Java的interface可以有0-N个实现

- Objective-C里，interface可以定义成员属性，Java里不可以

在Objective-C里，和Java的Interface概念相似的是Protocol，下文会讲到。

请看示例：

#+BEGIN_SRC C
  // Interface
  @interface MyClass {
    int memberVar1;
    id  memberVar2;
  }

  -(return_type) instance_method1;
  -(return_type) instance_method2: (int) p1;
  -(return_type) instance_method3: (int) p1 andPar: (int) p2;
  @end
#+END_SRC

#+BEGIN_SRC C
  //Implementation

  @implementation MyClass {
    int memberVar3;
  }

  -(return_type) instance_method1 {
    //....
  }
  -(return_type) instance_method2: (int) p1 {
    //....
  }
  -(return_type) instance_method3: (int) p1 andPar: (int) p2 {
    //....
  }
  @end
#+END_SRC

接口和实现以@interface、@implementation开头，都以@end结束。“@”符号在Objective-C中是个很神奇的符号。

冒号也是方法名的一部分，method和method:是两个不同的方法名，不是overload，第二个带参数。

上述代码对应的Java版：

        public class MyClass {
                protected int memberVar1;
                protected pointer memberVar2;
                private int memberVar3;

                public (return_type) instance_method1() {
                        ....
                }

                public (return_type) instance_method2(int p1) {
                        ....
                }

                public (return_type) instance_method3andPar(int p1, int p2) {
                        ....
                }
        }

#### 私有方法和公开方法

写在.h头文件里的方法都是公开的，Objective-C里 _没有私有方法的概念_ 。

官方并没有提到Objective-C怎么实现私有方法，我查阅了stackoverflow，统一的答案是，要实现私有方法的效果只能借助Category，不过，根据我的测试，即使采用了Category，也不能阻止外部的代码调用这个“私有方法”，只是Xcode不支持“私有方法”的自动完成，并会有警告提示，运行的时候，还是会成功的。各位看官知道有这么回事就可以了，这里不深讲。

#### 变量和属性

#### 类方法和实例方法
##### 类方法
类方法就是Java、PHP里的Static Method，不用实例化就能调。类方法有一个加号前缀。
示例：

类定义

        @interface MyClass
                +(void) sayHello;
        @end

        @implementation MyClass

        +(void) sayHello {
        NSLog(@"Hello, World");
        }
        @end

使用

        [MyClass sayHello];

##### 实例方法
实例方法就是Java、PHP里的普通方法，必须实例化才能调。实例方法有一个减号前缀。
示例：

类定义

        @interface MyClass : NSObject
        -(void) sayHello;
        @end

        @implementation MyClass

        -(void) sayHello {
        NSLog(@"Hello, World");
        }
        @end

使用

        mycls = [MyClass new];
        [mycls sayHello];

#### Selector
selector就是一个方法指针，类似PHP里的动态方法名：

        <?php
        class Hello {
                public function sayHello() {}

                public function test() {
                        $fun_name = "sayHello";
                        $this->$fun_name();
                }
        }

在Objective-C里，selector主要用来做两类事情：

##### 绑定控件触发的动作

        @implementation DemoViewController
        - (void)downButtonPressed:(id)sender {//响应“按钮被按下事件”的方法
                UIButton *button = (UIButton*)sender;
                [button setSelected:YES];
        }

        - (void)drawAnButton {
                UIButton *btn = [UIButton buttonWithType:UIButtonTypeCustom];
                btn.frame = _frame;
                btn.tag = 1;
                btn.backgroundColor = [UIColor clearColor];
                [btn addTarget: self
                         action: @selector(downButtonPressed:)
                         forControlEvents: UIControlEventTouchUpInside];//当这个按钮被按下时，触发downButtonPressed:方法
        }
        @end

##### 延时异步执行

        @implementation ETHotDealViewController
        - (void)viewDidLoad {

                //获取数据源
                HotDealDataSource *ds = [[HotDealDataSource alloc]init];
                [ds reload];
                _items = ds.items;

                [self performSelector: @selector(refreshTable)
                          withObject: self
                          afterDelay: 0.5];//延迟0.5秒调用refreshTable方法
        }

        -(void)refreshTable
        {
                [self.tableView reloadData];
        }
        @end

这个例子中，获取数据源是通过ASIHTTP组件异步调用服务端HTTP接口，refreshTable要用到数据源返回回来的数据，如果不延迟0.5秒，就会立刻执行，执行的时候数据还在路上呢，页面就要变空白了。

### 继承
继承是写在Interface定义里面的。语法为：子类名在左，父类名在右，中间用冒号分隔。
示例：

        @interface MyClass : NSObject
        @end

对应的Java版本是：

        public class MyClass extends NSObject {
        }





### 协议（Protocol）
就是Java、PHP里的Interface。

#### 协议的定义
协议的定义用@protocol关键字：

        @protocol Printable
                -(void)print:(NSString)str;
        @end

对应的Java版本是：

        publilc interface Printable {
                public void print(String str);
        }

##### 协议的继承
协议本身也可以继承别的协议：

        @protocol Printable <NSObject>
                -(void)print:(NSString)str;
        @end

对应的Java版本：

        public interface Printable extends NSObject {
                public void print (String str);
        }

##### 可选方法
协议可以包含可选方法，顾名思义，可选方法可以不被类实现：

        @protocol Printable
        @optional
                -(void)print:(NSString)str;
        @end

加了@optional关键字，一个类在implements这个协议时，便可以不实现print:方法。

Java里没有类似的实现，除了Collection里会有一些方法带有optional的注释，但Collection是个特例。

#### 协议的实现
一个类实现某些协议是写在Interface定义里面的。语法为：协议名用尖括号包裹，多个协议名用逗号隔开，协议写在父类的右边（如果没有父类就直接写在子类右边）。

示例：

        @interface MyClass : NSObject <Printable, Drawable>
        @end

Printable, Drawablw就是两个协议。

对应的Java版本是：

        public class MyClass extends NSObject implements Printable, Drawable {
        }
