* ntp

** 用法

#+BEGIN_SRC bash
sudo su
ntpdate -vd cn.pool.ntp.org
ntpdate -vd time.windows.com

# hardware clock write
hwclock -w
#+END_SRC

** 123端口被封

ntp走的是UDP协议123端口，公司的CMD-CCD网络中被限制

使用http返回头中的时间戳
#+BEGIN_SRC bash
alias updatecntime="sudo date -s \"$(wget --no-cache -S -O /dev/null baidu.com 2>&1 | sed -n -e '/  *Date: */ {' -e s///p -e q -e '}')\""
#+END_SRC

** China, Asia

https://www.ntppool.org/zh/  pool.ntp.org 是一个以时间服务器的大虚拟集群为上百万的客户端提供可靠的 易用的 网络时间协议（NTP）服务的项目

cn.pool.ntp.org


** assets

- doc https://linux.die.net/man/8/ntpdate


 1.本地修改时间
        date -s "2017/07/30 18:39"
        hwclock                     # 同步时间到服务器，即硬件同步
     2.同步互联网时间
        ntpdate time.windows.com   (ntpdate是一个内部的同步时间的代码)
       [可选] sntp –N time.windows.com   # 效果同上

#+BEGIN_SRC bash
ntpdate -vd time.windows.com
#+END_SRC



** Command Options


*** options


 -aKeyid  使用 Keyid 来认证全部数据包。
 -b  通过调用 settimeofday 子例程来增加时钟的时间。
 -d  指定调试方式。判断 ntpdate 命令会产生什么结果（不产生实际的结果）。
   结果再现在屏幕上。这个标志使用无特权的端口。
 -eAuthenticationDelay  指定延迟认证处理的时间秒数。
 -kKeyFile  当不使用缺省值 /etc/ntp.keys 文件时，为包含密钥的文件指定一个不同的
   名称。 请参阅文件KeyFile的描述。
 -oVersion  当轮询它的发出数据包时，指定使用的 NTP 版本实现。 Version 的值可以是
   1，2，3。缺省值是 3。
 -pSamples  指定从每个服务器获取的样本的数目。 Samples 的值在 1 和 8 之间，并包
   括 1 和 8。它的缺省值是 4。
 -s  指定日志操作 syslog 设施的使用，而不是使用标准输出。 当运行 ntpdate
   命令和 cron命令时，它是很有用的。
 -tTimeOut  指定等待响应的时间。给定 TimeOut 的值四舍五入为 0.2 秒的倍数。缺省值
   是 1 秒。
 -u  指定使用无特权的端口发送数据包。 当在一个对特权端口的输入流量进行阻
   拦的防火墙后是很有益的， 并希望在防火墙之外和主机同步。防火墙是一个
   系统或者计算机，它控制从外网对专用网的访问。
