*  wifi加密

** WEP

Wired Equivalent Privacy(有线等效保密)，是对在两台设备间无线传输的数据进行加密的方式，用以防止非法用户窃听或侵入无线网络。

LAN天生比WLAN安全，因为LAN的物理结构对其有所保护，部分或全部网络埋在建筑物里面也可以防止未授权的访问。经由无线电波的WLAN没有同样的物理结构，因此容易受到攻击、干扰。

WEP的目标就是通过对无线电波里的数据加密提供安全性，如同端-端发送一样。 WEP特性里使用了rsa数据安全性公司开发的rc4 ping算法。如果你的无线基站支持MAC过滤，推荐你连同WEP一起使用这个特性(MAC过滤比加密安全得多)。

WEP是一种根本的加密办法，其安全性没有WPA高。挑选WEP安全类型，路由器将运用802.11根本的WEP安全形式。这儿需求留意的是因为802.11N不支持此加密办法，假如您挑选此加密办法，路由器可能会工作在较低的传输速率上。

不同的无线加密办法对无线网络传输速率的影响也不尽相同。因为IEEE 802.11n规范不支持以WEP加密或TKIP加密算法的高吞吐率，所以假如用户挑选了WEP加密办法或WPA-PSK/WPA2-PSK加密办法的TKIP算法，无线传输速率将会主动限制在11g水平。

也就是说，假如用户运用的是契合IEEE 802.11n规范的无线商品，那么无线加密办法只能挑选WPA-PSK/WPA2-PSK的AES算法加密，不然无线传输速率将会显着下降。而假如用户运用的是契合IEEE 802.11g规范的无线商品，那么三种加密办法都能够极好的兼容，不过仍然不主张我们挑选WEP这种较老且现已被破解的加密办法，最好能够晋级一下无线路由。


** WPA

WPA 全名为 Wi-Fi Protected Access(Wi-Fi网络安全存取)，有WPA和WPA2两个标准，是一种保护无线电脑网络(Wi-Fi)安全的系统。

WPA是继承了WEP基本原理而又解决了WEP缺点的一种新技术。由于加强了生成加密密钥的算法，因此即便收集到分组信息并对其进行解析，也几乎无法计算出通用密钥。此外还追加了防止数据中途被篡改的功能和认证功能。由于具备这些功能，WEP中此前倍受指责的缺点得以全部解决。

完整的WPA实现是比较复杂的，由于操作过程比较困难，一般用户实现是不太现实。所以在家庭网络中采用的是WPA的简化版：WPA－PSK（预共享密钥）。

WPA 实作了 IEEE 802.11i标准的大部分，是在 802.11i 完备之前替代 WEP 的过渡方案。WPA 的设计可以用在所有的无线网卡上，但未必能用在第一代的无线取用点上。WPA2实作了完整的标准，但不能用在某些古老的网卡上。

由于WEP业已证明的不安全性，在802.11i协议完善前，采用WPA为用户提供一个临时性的解决方案。该标准的数据加密采用TKIP协议(Temporary Key Integrity Protocol)，认证有两种模式可供选择，一种是使用802.1x协议进行认证；一种是称为预先共享密钥PSK(Pre-Shared Key)模式。

    WPA（Wi-Fi Protected Access）加密方式目前有四种认证方式：WPA、WPA-PSK、WPA2、WPA2-PSK。采用的加密算法有二种：AES（Advanced Encryption Standard高级加密算法）和TKIP（Temporal Key Integrity Protocol临时密钥完整性协议）。

    WPA
    WPA是用来替代WEP的。WPA继承了WEP的基本原理而又弥补了WEP的缺点：WPA加强了生成加密密钥的算法，因此即便收集到分组信息并对其进行解析，也几乎无法计算出通用密钥；WPA中还增加了防止数据中途被篡改的功能和认证功能。

    WPA-PSK（预先共享密钥Wi-Fi保护访问）
    WPA-PSK适用于个人或普通家庭网络，使用预先共享密钥，秘钥设置的密码越长，安全性越高。WPA-PSK只能使用TKIP加密方式。

    WPA2（WPA第二版）
    WPA2是WPA的增强型版本，与WPA相比，WPA2新增了支持AES的加密方式。

    WPA2-PSK
    WPA-PSK类似，适用于个人或普通家庭网络，使用预先共享密钥，支持TKIP和AES两种加密方式。

    WPA/WPA2
    WPA/WPA2是一种比WEP强壮的加密算法，挑选这种安全类型，路由器将选用Radius服务器进行身份认证并得到密钥的WPA或WPA2安全形式。因为要架起一台专用的认证服务器，价值对比贵重且保护也很杂乱，所以不推荐普通用户运用此安全类型。

    WPA-PSK/WPA2-PSK
    WPA-PSK/WPA2-PSK安全类型其实是WPA/WPA2的一种简化版别，它是依据同享密钥的WPA形式，安全性很高，设置也对比简单，合适普通家庭用户和小型企业运用。

*** 认证类型

    认证类型： 即主动、WPA-PSK、WPA2-PSK。
    主动：若挑选该项，路由器会依据主机恳求主动挑选WPA-PSK或WPA2-PSK安全形式。
    加密算法： 该项用来挑选对无线数据进行加密的安全算法，选项有主动、TKIP、AES。默许选项为主动，挑选该项后，路由器将依据实践需求主动挑选TKIP或AES加密办法。留意11N形式不支持TKIP算法。
    PSK暗码： 该项就是WPA-PSK/WPA2-PSK的初始密钥了，在设置时，需求为8-63个ASCII字符或8-64个十六进制字符。
    组密钥更新周期：该项设置播送和组播密钥的定时更新周期，以秒为单位，最小值为30，若该值为0，则表示不进行更新。
