* ssd


1. 物理接口

M.2 , U.2 , AIC, NGFF 这些属于物理接口。像 M.2 可以是 SATA SSD 也可以是 NVMe（PCIe） SSD。金手指上有一个 SATA/PCIe 的选择信号，来区分两者。很多笔记本的M.2 接口也是同时支持两种类型的盘的。 M.2 , 主要用在 笔记本上，优点是体积小，缺点是散热不好。U.2,主要用在 数据中心或者一些企业级用户，对热插拔需求高的地方。优点热插拔，散热也不错。一般主要是pcie ssd(也有sas ssd)，受限于接口，最多只能是 pcie 4laneAIC，企业，行业用户用的比较多。通常会支持pcie 4lane/8lane，带宽上限更高

2. 高速信号协议

SAS，SATA，PCIe 这三个是同一个层面上的，模拟串行高速接口。SAS 对扩容比较友好，也支持双控双活。接上SAS RAID 卡，一般在阵列上用的比较多。SATA 对热插拔很友好，早先台式机装机市场的 SSD基本上都是SATA的，现在的 机械硬盘也是SATA接口居多。但速率上最高只能到 6Gb/s，上限 550MB/s左右，现在已经慢慢被pcie取代。PCIe 支持速率更高，也离CPU最近。很多设备 如 网卡，显卡 也都走pcie接口，当然也有SSD。现在比较主流的是PCIe 3.0,8Gb/s 看起来好像也没比 SATA 高多少，但是 PCIe 支持多个LANE，每个LANE都是 8Gb/s，这样性能就倍数增加了。目前，SSD主流的是 PCIe 3.0x4 lane，性能可以做到 3500MB/s 左右。

3. 传输层协议

SCSI，ATA，NVMe 都属于这一层。主要是定义命令集，数字逻辑层。SCSI 命令集 历史悠久，应用也很广泛。U盘，SAS 盘，还有手机上 UFS 之类很多设备都走的这个命令集。ATA 则只是跑在SATA 协议上NVMe 协议是有特意为 NAND 进行优化。相比于上面两者，效率更高。主要是跑在 PCIe 上的。当然，也有NVMe-MI，NVMe-of之类的。是个很好的传输层协议。

4. 总结

M.2,U.2,AIC 是物理规格，像是 公路，铁路。PCIe，SATA，SAS 是 模拟高速接口，像是 县道，省道，高速这样。速率上限不同SCSI，ATA，NVMe 是传输层协议，命令集。就是跑在路上面的小车，只是有 跑车 和 面包车 之分。所以，如果要买SSD的话，不是只看 M.2就完事了 ，得分清了 是 SATA 的，还是 NVMe 的，看看主板支持的到底是哪种。否则，买回来的东西可能会用不了！原创手打，能力有限，欢迎大家指错。


固态硬盘（SSD）拥有比机械硬盘（HDD）更快的读写速度。目前大多数机器使用的是SATA总线标准，实际最高传输约为600MB/s。而支持PCIe总线，NVMe协议的SSD，实际传输速度将超过1000MB/s。


1、NVMe是为PCIe制定的标准接口协议。

2、解除了旧标准施放在SSD上的各种限制。

3、支持所有常见的操作系统。

4、良好的可拓展性。

5、具有低延迟，低能耗，高性能等优点。

传统的AHCI协议具有较强的兼容性，但是当与通过PCIe总线连接的SSD一起使用时，无法提供最佳的性能。而NVMe的设计充分利用了PCIe SSD的低延迟和并行性，并兼顾可CPU与平台构架，最大程度的发挥SSD的性能。

二、NVMe的发展历史

NVMe1.0标准与2011年3月推出，由NVMe规范组织成员公司（如Intel,戴尔,三星,镁光等共计100多家公司）合作开发。2012年10月推出了1.1的版本。在2014年11月推出1.2版本之后，时隔近3年，2017年5月，NVMe规范组织正式发布了最新版的NVMe 1.3版规范标准。在最新的1.3中添加了如设备自检、引导分区、虚拟化、主机操控散热管理等新特性，理论上能够大大改进SSD的性能。



目前，市面上主流的NVMe硬盘，采用的为1.2版本的规范标准。

上面这些说法太冠冕堂皇了，我还是用大白的语言翻译成小白能懂的语言吧！

第一：NVMe是一种接口协议，不是指的接口，所谓的协议就是某种规则，比如生活中不同的公路，可以看作是不同的接口，如果一条公路按照高速公路的规则来运行，那么就算是同样的路，也会比行人、自行车、汽车都能走的普通公路速度快得多；

第二：NVMe标准是面向PCI-E固态硬盘的，怎么理解这个呢，我们知道电脑的CPU是核心计算单元，所有程序指令的计算处理都是由CPU完成，PCI-E相当于一条直接跟CPU打交道的绿色通道，所以PCI-E固态硬盘实际上就是固态硬盘可以直接跟CPU打交道，意味着速度可以更快；

第三：除了高速公路上的绿色通道特性之外，NVMe还具有超宽的车道，意思是同一时间可以跑更多的数据在上面，不光跑得快，货还拉得多；

第四：还有一个重要特性是它的功耗很低，这里功耗低并不是指的省油，而是综合管理能力带来的能耗控制，由于在上面跑起来都非常快，所以一旦没数据了，立马让工作人员进入休息状态，长时间没数据，立马放假。对于平板跟笔记本来说，可显著提高电池续航能力。
