* units

** 比較常見的 systemd 的服務類型如下：

systemd根据他们描述的资源类型来分类单元。最简单的确定单元类型的方式是使用它们的类型后缀，其被附加在资源名后面。下面的列表介绍了systemd可用的单元类型：

.services:一个服务单元描述如何在服务器上管理一个服务或者应用。这将会包括如何开始或者停止服务、在哪些情况下应自动启动以及相关的软件依赖和排序信息。

.socket：一个套接字单元文件描述了systemd使用于基本套接字激活的一个网络或者IPC套接字，或者一个FIFO缓冲。.services文件将会在定义在这个单元里的套接字是活动时开始。
.devic：描述了一个设备被udev或者sysfs指定作为systemd管理器的单元。不是所有设置都有.device文件。一些情况下.device单元可能是命令、挂载及访问设备所必需的。
.mount：这个单元定义了一个在系统上systemd管理的挂载点。这个些文件以挂载路径来命名，并且把斜杠改成短划线。在/etc/fstab里的条目会有自动创建的单元。
.automount：一个.automount单元配置了一个将会自动挂载的挂载点。这些必须根据涉及的挂载点来命令并且必须有匹配的.mount单元来定义挂载的细节。
.swap：这个单元描述了系统里的交换空间。这些文件的名字必须体现设备或者空间文件。
.target：一个目标单元是在启动或者改变状态时为其他单元提供同步点的。他们也可以用于把系统带进一个新的状态。其他单元指定他们的相当目标来绑定目标的操作。
.path：这个单元定义了一个可用于基于路径激活的路径。默认情况下，当路径达到指定状态时一个相同基础名字的.service单元就会开始。这使用inotify来监控路径的变化。
.timer：一个.timer单元定义了一个被systemd管理的定时器，类似于一个cron工作来延时或者计划激活。一个匹配的单元将会在计时器到达时开始。
.snapshot：一个.snapshot单元是被systemctl snapshot命令自动创建的。它可以让你在进行更改后重建系统的当前状态。快照不会跨会话生存，快照是用于回滚临时状态的。
.slice：一个.slice单元是和Linux Control Group节点关联的，允许资源受到限制或者给关联的进程分匹配时间片。名字反映了它在cgroup树里的分层位置。单元默认根据他们的类型放在一定的位置。

.scope：作用域单元是systemd根据从它的总线接口接收到的信息自动创建的。这些被用于外部创建的系统进程的管理集。


不同的单元文件类型里面的配置项不同，通用的配置项有 Unit和Install。

单元文件可以使用Boolean作为参数作为变量值。正值可以是1、yes、true、on,负值可以是0、no、false、off。

单元文件中时间变量值可以带时间单位，例如:s、min、h、d、w、ms、us。2min 200ms等同于120200 ms。如果时间变量的值没有给单位，则默认单位是s。

以#或;开头的行会被忽略掉。你可以用这种方式写备注。在行尾添加反斜线将链接下面一行的内容。

有一些单元的名称包含一个 @ 标记（例如： `name@string.service），这意味着它是模板单元name@.service的一个 实例。 string 被称作实例标识符，在 systemctl 调用模板单元时，会将其当作一个参数传给模板单元，模板单元会使用这个传入的参数代替模板中的%I指示符。 在实例化之前，systemd 会先检查name@string.suffix文件是否存在（如果存在，就直接使用这个文件，而不是模板实例化）。大多数情况下，包含 @ 标记都意味着这个文件是模板。如果一个模板单元没有实例化就调用，该调用会返回失败，因为模板单元中的%I` 指示符没有被替换。

单元之间存在隐形依赖，依赖关系取决于单元类型和单元配置。这些隐形依赖可以时单位文件更简洁。不同单元文件类型中的隐形依赖关系可能不一样。例如，对于.service服务类型单元文件，Type=dbus自动获取获取对dbus.socket的Requires=和After=依赖关系。

在系统模式下单元文件可以从下面两个地方加载，优先级从低到高：

/usr/lib/systemd/system/ ：软件包安装的单元
/etc/systemd/system/ ：系统管理员安装的单元
注意： 用户运行时模式下加载路径不一样。




** config


*** [Unit] 部分

Unit部分包含了单元文件不依赖单元类型的部分。主要是描述单元的启动顺序和依赖关系。

1. ~Description=~

单元在用户界面下的介绍信息。帮助用户快速了解单元文件用途。

1. ~Documetation=~

单位文件或配置的URL引用路径，接收以空格分隔的多个URL。URL支持的类型有:http://、https://、file:、info:、man:。

1. ~Requires=~

描述此单元强依赖的单元列表（多个单元文件用空格分隔）。如果此单位被激活，则它依赖的单元也会被激活。

此字段一般结合After=、Before=描述依赖顺序的字段一起使用。如果依赖的单元并没有写进顺序启动字段中，那么此单位和依赖的单元会同时被激活没有任何延迟。

如果依赖单元启动失败则此单位也会被退出。为了系统的稳定性，最好的选择是使用Wants=字段。描述的此单元文件弱依赖的单位文件，如果依赖的单位文件启动失败或异常退出不影响此单位文件。

1. ~Wants=~

描述此单元的弱依赖单位列表。如果这个列表中的有单位启动失败或异常退出，并不影响此单位正常的运行。

1. ~Requisite=~

描述单位文件超强依赖单位列表。如果列表中的没有启动，他们则不会立即启动而整个业务失败。

1. ~BindsTo=~

描述相互绑定的单位列表，如果关联中的单位有停止，这此单位也会停止。

1. ~PartOf=~

描述关联的单位。如果这个单元被停止或重启了，此单元也会被停止或重启。这个关联是单向的，改变此单元并不影响关联的单元。

1. ~Conflicts=~

描述相冲突的单元列表。如果冲突列表中单元有启动中的，则会停止此单元。反之，如果此单元启动，停止冲突单元列表中在运行的单元。

1. ~Before=, After=~

这两个字段设置此单元依赖的其他单元的顺序列表。例如：如果foo.service单位文件配置了Before=bar.service。然后这两个单元同时启动，则bar.service需要等到foo.service完全启动了再启动。这个两个字段只定义单元之间的启动顺序，不涉及单元依赖。

1. ~OnFailure=~

描述了当此单元状态进入failed时需要激活的单元列表。

*** ~[Service]部分~

Service部分是写在.service结尾的服务类型单元中的。.service结尾的单位负责管理和监控systemd进程。

隐形依赖
服务定义Type=dbus，则自动添加了Requirres=dbus.socket和After=dbus.socket
Socket激活的Services会自动在Socket单元激活后再启动。也就是自动将Service添加如.socket单元中的After=。
默认依赖
除非在[Unit]中设置DefaultDependencies=no，否则就存在下面默认依赖：

服务单元默认在Requires=和After=写入sysinit.target。basic.target默认写入After=,shutdown.target默认写入Conflicts=和Before=。这些依赖确保服务单元能够正常进入系统初始化和系统在关闭前被彻底关闭。
Type=
定义服务单元在启动是进程类型。拥有的类型有：simple、forking、oneshot、dbus，notify、idle。

simple（默认值）：ExecStart字段启动的进程为主进程
forking：ExecStart字段将以fork()方式启动，此时父进程将会退出，子进程将成为主进程
oneshot：类似于simple，但只执行一次，Systemd 会等它执行完，才启动其他服务
dbus：类似于simple，但会等待 D-Bus 信号后启动
notify：类似于simple，启动结束后会发出通知信号，然后 Systemd 再启动其他服务
idle：类似于simple，但是要等到其他任务都执行完，才会启动该服务。一种使用场合是为让该服务的输出，不与其他服务的输出相混合
RemainAfterExit=
接收一个Boolean值。说明是否在服务进程都退出的情况下保留服务。默认是no

应用例子：

[Unit]
Description=Switch-off Touchpad

[Service]
Type=oneshot #只执行一次
ExecStart=/usr/bin/touchpad-off

[Install]
WantedBy=multi-user.target
上面例子是：笔记本电脑启动时，要把触摸板关掉。启动类型是oneshot表面这个服务只要运行一次就够了。但关闭后将来某个时间想打开，可以修改配置文件如下：

1
2
3
4
5
6
7
8
9
10
11
[Unit]
Description=Switch-off Touchpad

[Service]
Type=oneshot
ExecStart=/usr/bin/touchpad-off start
ExecStop=/usr/bin/touchpad-off stop
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
RemainAfterExit字段是yes，表明在进程退出后服务仍然保持执行。这样在执行systemctl stop命令停止服务时，ExecStop指定的命令就会执行，从而重新开启触摸板。

ExecStart=
启动进程时执行的命令。

除非Type是oneshot，则必须给个命令。可以定义多个ExecStart字段，但如果有ExecStart字段为空值，则这个字段上面定义的ExecStart字段将无效。

如果没有指定ExecStart=，则该服务必须具有RemainAfterExit=yes并且至少有一个ExecStop=。

每个指定的命令第一个参数必须是可执行的文件绝对路径。或者，这个文件名可能带有许多个特殊符前缀。

特殊的可执行文件前缀。

PrefixEffect
@可执行文件前缀是@，则第二个指定的标记将会作为参数argv[0]传递给进程
-退出后不会重启
on-success：只有正常退出时（退出状态码为0），才会重启
on-failure：非正常退出时（退出状态码非0），包括被信号终止和超时，才会重启
on-abnormal：只有被信号终止和超时，才会重启
on-abort：只有在收到没有捕捉到的信号终止时，才会重启
on-watchdog：超时退出，才会重启
always:不管是什么退出原因，总是重启
RestartSec=
重启服务之前，需要等待的时间。

[Install]部分
Install区块，定义如何安装这个配置文件，即怎样做到开机启动。

Alias=
创建匿名单位列表。列表中的单元名字后缀需要和单位文件后缀一致。在systemctl enable中会创建软连接将列表名字和单元文件名联系起来。

并不是所有单元类型都支持Alias。mount, slice, swap, 和 automount 单元类型不支持。

WantBy= RequiredBy=
这两个字段可以有多个或者使用单元列表。当执行systemclt enable时会在列出的每个单元的.wants/或.requires/目录下创建此单元的一个符号链接。

当列表中的单元启动时，此单元也会被启动。

这个两个字段表示Target，一个Target可以包含多个单元，但Target被启动时，里面所包含的单元也会跟在启动。

一般Target就是运行模式。

查看当前运行模式：

1
2
$ systemctl get-default
multi-user.target
查看 multi-user.target 包含的所有服务：

1
$ systemctl list-dependencies multi-user.target
切换target

1
$ sudo systemctl isolate shutdown.target
修改配置文件后重启
修改配置文件以后，需要重新加载配置文件，然后重新启动相关服务。
