* firewall


Firewalld is the new way of interacting with the iptables rules in RHEL 7. It allows to set new sucurity rules and activate them in runtime without disconnecting any existing connections.


** 命令格式

#+BEGIN_SRC bash
firewall-cmd [选项 ... ]
#+END_SRC

*** 选项

**** 通用选项

-h, --help    # 显示帮助信息；
-V, --version # 显示版本信息. （这个选项不能与其他选项组合）；
-q, --quiet   # 不打印状态消息；

**** 状态选项

--state                # 显示firewalld的状态；
--reload               # 不中断服务的重新加载；
--complete-reload      # 中断所有连接的重新加载；
--runtime-to-permanent # 将当前防火墙的规则永久保存；
--check-config         # 检查配置正确性；

**** 日志选项

--get-log-denied         # 获取记录被拒绝的日志；

--set-log-denied=<value> # 设置记录被拒绝的日志，只能为 'all','unicast','broadcast','multicast','off' 其中的一个；


**** 配置firewalld

firewall-cmd --version  # 查看版本
firewall-cmd --help     # 查看帮助

****  查看设置

firewall-cmd --state  # 显示状态
firewall-cmd --get-active-zones  # 查看区域信息
firewall-cmd --get-zone-of-interface=eth0  # 查看指定接口所属区域
firewall-cmd --panic-on  # 拒绝所有包
firewall-cmd --panic-off  # 取消拒绝状态
firewall-cmd --query-panic  # 查看是否拒绝


firewall-cmd --reload # 更新防火墙规则
firewall-cmd --complete-reload

~--reload~ ~--complete-reload~ 两者的区别就是第一个无需断开连接，就是firewalld特性之一动态添加规则，第二个需要断开连接，类似重启服务

**** 将接口添加到区域，默认接口都在public

# 永久生效再加上 --permanent 然后reload防火墙
firewall-cmd --zone=public --add-interface=eth0


# 设置默认接口区域，立即生效无需重启
firewall-cmd --set-default-zone=public

# 查看所有打开的端口：
firewall-cmd --zone=dmz --list-ports

# 加入一个端口到区域：
firewall-cmd --zone=dmz --add-port=8080/tcp
# 若要永久生效方法同上

# 打开一个服务，类似于将端口可视化，服务需要在配置文件中添加，/etc/firewalld 目录下有services文件夹，这个不详细说了，详情参考文档
firewall-cmd --zone=work --add-service=smtp

# 移除服务
firewall-cmd --zone=work --remove-service=smtp

# 显示支持的区域列表
firewall-cmd --get-zones

# 设置为家庭区域
firewall-cmd --set-default-zone=home

# 查看当前区域
firewall-cmd --get-active-zones

# 设置当前区域的接口
firewall-cmd --get-zone-of-interface=enp03s

# 显示所有公共区域（public）
firewall-cmd --zone=public --list-all

# 临时修改网络接口（enp0s3）为内部区域（internal）
firewall-cmd --zone=internal --change-interface=enp03s

# 永久修改网络接口enp03s为内部区域（internal）
firewall-cmd --permanent --zone=internal --change-interface=enp03s

服务管理

# 显示服务列表
Amanda, FTP, Samba和TFTP等最重要的服务已经被FirewallD提供相应的服务，可以使用如下命令查看：

firewall-cmd --get-services

# 允许SSH服务通过
firewall-cmd --new-service=ssh

# 禁止SSH服务通过
firewall-cmd --delete-service=ssh

# 打开TCP的8080端口
firewall-cmd --enable ports=8080/tcp

# 临时允许Samba服务通过600秒
firewall-cmd --enable service=samba --timeout=600

**** 显示当前服务

firewall-cmd --list-services


**** 添加HTTP服务到内部区域（internal）

firewall-cmd --permanent --zone=internal --add-service=http
firewall-cmd --reload     # 在不改变状态的条件下重新加载防火墙

**** 端口管理

# 打开443/TCP端口
firewall-cmd --add-port=443/tcp

# 永久打开3690/TCP端口
firewall-cmd --permanent --add-port=3690/tcp

# 永久打开端口好像需要reload一下，临时打开好像不用，如果用了reload临时打开的端口就失效了
# 其它服务也可能是这样的，这个没有测试
firewall-cmd --reload

# 查看防火墙，添加的端口也可以看到
firewall-cmd --list-all

直接模式

# FirewallD包括一种直接模式，使用它可以完成一些工作，例如打开TCP协议的9999端口

firewall-cmd --direct -add-rule ipv4 filter INPUT 0 -p tcp --dport 9000 -j ACCEPT
firewall-cmd --reload


** basic

*** Managing firewalld

#+BEGIN_SRC bash
# status
firewall-cmd --state                 -- Display whether service is running
systemctl status firewalld           -- Another command to display status of service

# restart
firewall-cmd --reload                -- To reload the permanent rules without interrupting existing persistent connections
systemctl restart firewall-cmd       -- To restart service
#+END_SRC


#+BEGIN_SRC bash
# To start/stop/status firewalld service
systemctl start firewalld.service
systemctl stop firewalld.service
systemctl status firewalld.service

# To enable/disable firewalld service at boot time, To enable firewalld service from starting at boot time.
systemctl enable firewalld

# To disable firewalld service from starting at boot time.
systemctl disable firewalld
#+END_SRC

*** zone

To list details of default and active zones

#+BEGIN_SRC bash
firewall-cmd --get-default-zone
firewall-cmd --get-active-zones
firewall-cmd --list-all
#+END_SRC

To add/remove interfaces to zones

To add interface “eth1” to “public” zone.

firewall-cmd --zone=public --change-interface=eth1

To list/add/remove services to zones

To list available services :

firewall-cmd --get-services

To add “samba and samba-client” service to a specific zone. You may include, “permanent” flag to make this permanent change.

firewall-cmd --zone=public --add-service=samba --add-service=samba-client --permanent

To list services configured in a specific zone.

firewall-cmd --zone=public --list-service

To list and Add ports to firewall

firewall-cmd --list-ports
firewall-cmd --zone=public --add-port=5000/tcp

Note:
You may restart the Network service followed by Firewall server.

systemctl restart network.service
systemctl restart firewalld.service
