* 简介

** 网络、分组和协议

  网络由通信信道互连的机器组成。

    - 主机 运行应用程序的计算机

    - 路由器也叫做网关(gateway)，它的职责是把信息从一条通信信道发送至另一条通信信道。他们有可能运行程序，但通常不运行应用程序。

    - 通信信道是把字节序列从一台主机传送到另一台主机的工具。它可能是有线的，无线或者其他连接。

    - 信息是由程序构建和解释的字节序列。

    - 协议是关于通信程序交换的分组及含义的协定。

** 地址

*** 字节

  Byte， 通过下表示8个位bit

**** 什么是 Byte

Byte在历史上有过6、7或者9个bit位

   amount used to represent one character; on modern architectures this is
   usually 8 bits, but may be 9 on 36-bit machines. Some older
   architectures used `byte' for quantities of 6 or 7 bits, and the PDP-10
   supported `bytes' that were actually bitfields of 1 to 36 bits! These
   usages are now obsolete, and even 9-bit bytes have become rare in the
   general trend toward power-of-2 word sizes.

   Historical note: The term was coined by Werner Buchholz in 1956 during
   the early design phase for the IBM Stretch computer; originally it was
   described as 1 to 6 bits (typical I/O equipment of the period used 6-bit
   chunks of information). The move to an 8-bit byte happened in late 1956,
   and this size was later adopted and promulgated as a standard by the
   System/360. The word was coined by mutating the word `bite' so it would
   not be accidentally misspelled as {bit}. See also {nybble}.


*** IPv4

32位地址，包含4字节的内容，每部分取值范围为0-255。

  - IPv6  16字节的IPv6

     2000:fdb8:0000:0000:0001:00ab:853c:39a1


   协议族 protocol suite.

**** IPv4中的专用预留地址

***** TODO

***** 为什么有这些地址


** 名称、域名 Names

  - 我们总是按域名引用web服务顺

  - 域名解析服务来源有

    1. DNS

    1. 本地配置的数据库


** client与server

client发起通信，服务器程序被动地等待

*** p2p

  p2p 点对点 peer to peer 点对点服务
